### ISSUE TITLE
cannot export notebooks in standalone mode

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1007]
I am running a server with `npm run start-and-serve`, and I made a quick test notebook & exported it from the menu item.

I get the following error in `validated-reducer.js`:

```
Error: [
 {
  "keyword": "type",
  "dataPath": ".notebookId",
  "schemaPath": "#/properties/notebookId/type",
  "params": {
   "type": "integer"
  },
  "message": "should be integer"
 }
]
bad values:
{
 "notebookId": null
}
```

My understanding from this is we haven't worked on actually changing the schema to support `notebookId` to be `null` (which is the case in standalone mode), so this error is getting thrown. 

Here is the notebook as I wrote it in the the editor & exported:

```html

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>test - iodide</title>
<link rel="stylesheet" type="text/css" href="http://localhost:8000//iodide.dev.css">
<base target="_blank" rel="noopener noreferrer">
</head>
<body>
<script id="jsmd" type="text/jsmd">
%% meta
{
  "title": "test",
  "lastExport": "2018-10-03T17:15:55.487Z"
}
%% js
var x = 10
</script>
<iframe
  id="eval-frame"
  src="http://localhost:8000//iodide.eval-frame.dev.html"
  sandbox="allow-scripts allow-same-origin"
  allowfullscreen="true"
  allowvr="yes"
></iframe>
<script src="http://localhost:8000//iodide.dev.js"></script>
</body>
</html>

```

**Comment by hamilton** [comment]
Experimented a bit with changing the `notebookId` field in the schema to only be null, but I get this pretty perplexing error:

![screen shot 2018-10-03 at 11 04 47 am](https://user-images.githubusercontent.com/95735/46429831-3f3fbc80-c6fc-11e8-9bf9-281034f034ad.png)

Which comes from changing in `editor-only-state-schemas.js` something that should probably work:

```javascript
...
  notebookId: {
    type: 'null',
    default: null,
  },
...
```

**Comment by bcolloran** [comment]
@hamilton just fyi: the problem was the parseInt in 
```
      const notebookId = (IODIDE_BUILD_TYPE && IODIDE_BUILD_TYPE === 'server') ?
        parseInt(window.location.pathname.split('/').filter(s => s.length).pop(), 10) : undefined;
```
in notebook-reducer.js wss returning a NaN, which the validator saw as a null. eek!!!! annoying tough little corner case to track down.

filing a new issue to clean up that line:
https://github.com/iodide-project/iodide/blob/5ec44be65f20a299eb2e9843fdb7e3a52e375fc3/src/reducers/notebook-reducer.js#L94
