### ISSUE TITLE
track server / standalone notebook status in `notebookInfo`

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1008]
At the moment, there is no clearly-defined way to say (from the client) that our notebook was served from an iodide server, or is in standalone mode. As such we have a handful of ad-hoc tactics for determining this:

- `IODIDE_BUILD_TYPE` is how we're managing it right now, but it's obviously going away with #979.
- `notebookInfo` in the store gets updated by the server upon some actions, and upon load. We could in theory look for a `connectionMode` or something like that, which gives you some direction on what the environment is. The default could be `standalone` unless explicitly set by the server. I would favor this approach.

Feedback welcome on this!

**Comment by bcolloran** [comment]
+1 on this. MVP for this could just be to set `connectionMode` with default `STANDALONE`that get's updated to `CONNECTED` when loading from a deployment (as you suggest);
and then down the road (separate issue and PR) add some kind of polling (or whatever is is the best practice, perhps @wlach has thoughts on this?) to see whether the connection has been lost.

@hamilton i'm happy with your proposal the first part, i think we can start work on that

**Comment by hamilton** [comment]
Great. I can take this on, given that it will block #979.
