### ISSUE TITLE
As a user, I want to effortlessly import my notebook onto the iodide server

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1010]
There are a number of ways a user might want to do this:

- via the REST API, it might be worthwhile to allow in the request body to take `content` and `title`, which would populate a notebook under `<server-url>/new` (but not save it). This will allow us to do things like create "open in iodide" buttons that doesn't use any url tricks.
- via the server interface, I want to be able to either click "upload a notebook" menu item or just drag a notebook to my user page and get some questions.
- via the client, I might want a menu item that lets me do the above, or something that just says "new notebook from clipboard" which takes copied jsmd and puts it into a notebook.

Some of these are probably more in-scope for the next month than others.

**Comment by bcolloran** [comment]
gonna close this one, b/c bow it's as easy as copy/paste jsmd!!!! :-D
