### ISSUE TITLE
we should get the notebookId in a more robust way than parsing it out of the URL

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1022]
re this statement in the code:
https://github.com/iodide-project/iodide/blob/5ec44be65f20a299eb2e9843fdb7e3a52e375fc3/src/reducers/notebook-reducer.js#L94

an integer parsing issue caused #1007, which is now fixed, but it seems like a brittle way of doing this. can we pass this in with the notebookInfo on the window object, or otherwise get the id via  an api response or something?

not top priority, but something to be aware of

**Comment by bcolloran** [comment]
fyi @hamilton and @wlach

**Comment by wlach** [comment]
Yeah we should probably just pass it down as metadata inside the document.

**Comment by hamilton** [comment]
closed by above-referenced PR.
