### ISSUE TITLE
Support async language plugin evaluators

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1025]
As suggested by @hamilton in a PM, it would be nice to be able to make a cell such as:

```
import numpy as np
x = np.array([1,2,3])
```

automatically load the Numpy package and then run the cell.

I'll ignore the Python-side magic necessary to make this happen (which I think is doable in 90%, but not 100% of cases), except to say that the fetch of the package has to happen asyncronously, and only after can the code content itself be executed.  Right now, the `evaluator` callback of a language plugin is synchronous, so we can't really do this.

I'd propose adding a new kind of evaluator to a language plugin `asyncEvaluator(code, messageCallback)` which returns a `Promise`.  (The old kind of sync `evaluator` would remain, since I think it's useful for the simple case -- only languages that cared to do something more sophisticated would have to implement `asyncEvaluator`).  The arguments would be:

- `code` a string of code (as in the current `evaluator`)
- `messageCallback` a callback that the evaluator can call to display progress messages

The messages would be displayed in the output console, each replacing the previous one, and ultimately be replaced by the output of the final Promise step.  Writing an evaluator would then be something like the following pseudocode:

```
function runPythonAsync(code, messageCallback) {
   messageCallback('fetching package')
   return fetch('package.js')
      .then((package) => {
          messageCallback('initializing package')
          return package.initialize()
      })
      .then((initPackage) => {
         messageCallback('running code')
         return runPython(code)
      )
}
```

It would be good to have @bcolloran and @hamilton 's thoughts before starting to implement this.

**Comment by bcolloran** [comment]
tbh, my main thought is that this will take a bit of thought to really digest and consider the implications. can we table this for a while? (until after MVP launch?)

**Comment by mdboom** [comment]
Sure.  I don't think it's a priority.  Just wanted to record my thoughts as it's an obvious follow-on to #1014.

**Comment by hamilton** [comment]
One issue to consider. This point came up from mikes PR that loads python
when you run a cell. It’s kind of a nice trick, but it isn’t useful if I
want to load numpy or matplotlib, since you have to run the pyodide
command, when as a user j just want to start working with matplotlib. So we
might want to consider making this a somewhat higher priority, since the
language loading doesn’t actually feel like enough for the feature to feel
baked.

**Comment by hamilton** [comment]
To folllow up with this, I don't think having the automatic python loading is actually that useful (or interesting) to users unless 

```
import numpy
```

also works out the box. That's what this issue will potentially fix. So I would be in favor of not giving this the `p4` label, maybe `p2` if we actually think the seamless pyodide integration is useful.

**Comment by bcolloran** [comment]
see #1058
