### ISSUE TITLE
let's use zilla slab for the "Iodide" at the top of any page

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1028]
it will match the "moz://a" word mark that we'll want to add to our pages somewhere, and the slab serif "I" will clear up the typographical ambiguity @hamilton has pointed out with "Lodide"

and it's a pretty good looking font too:
![image](https://user-images.githubusercontent.com/2380975/46564533-bde35800-c8bc-11e8-845f-6d7474c426b1.png)

**Comment by hamilton** [comment]
Sounds good to me
