### ISSUE TITLE
Notebook links are not clickable in Chrome (stable)

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1030]
I can't figure out why this is, but the notebook links on `/` and `/$USER/` aren't clickable on Chrome.  Works fine on Firefox.

![image](https://user-images.githubusercontent.com/38294/46611458-e2694b00-cadb-11e8-9c77-322fef2786a1.png)

**Comment by wlach** [comment]
Works ok for me on Chrome for Mac?

**Comment by bcolloran** [comment]
chromium on ubuntu seems to work for me

**Comment by mdboom** [comment]
Hmmm...  That's a heck of a thing.  :face_with_head_bandage:

The notebook title doesn't seem to have a class.  If I add the class from the username (`css-1aguclh`), it works.  But I don't see what in the default css for `a` is preventing the clicks...

![image](https://user-images.githubusercontent.com/38294/46627232-cbd8e900-cb07-11e8-80a2-9df56091298d.png)

**Comment by mdboom** [comment]
Best as I can tell, this is a bug in the interaction between Chrome and my Linux DE -- on both stable and unstable channels for me at the moment.  There is a similar behavior on Github, which leads me to believe it's nothing on our end.
