### ISSUE TITLE
need to be able to change from one code cell language to another via kbd shortcut

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1041]
the fix in #1020 was too aggressive, and caused breakage here: https://github.com/iodide-project/iodide/pull/1014#discussion_r222859713

the that changed in #1020 just needs a minor tweak to account for code cell languages
https://github.com/iodide-project/iodide/pull/1020/files#diff-d25573781184593c6cbed0a9c4badccdR135

**Comment by hamilton** [comment]
@bcolloran could you put more descriptive titles in PRs like #1020? Can't tell what it was just from clicking on it.

**Comment by bcolloran** [comment]
sure can do, sorry!
