### ISSUE TITLE
iodide silently fails to notify user if a language plugin collides with an existing one defined in the jsmd

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1058]
If I have a language plugin for `testLang`, for example, and I save a notebook after having used `testLang`, and I reopen the notebook & attempt to fetch `testLang` from a remote source that includes some modifications (such as an `asyncEvaluator`), iodide will still favor the jsmd-saved language definition. This is kind of a subtle bug, but we should probably at least alert a user in the console if a new language definition might collide with an existing one cached in `meta`.

@mdboom is this the correct formulation for this issue?

**Comment by mdboom** [comment]
Yep.  That formulation is correct, though I don't think I have the one clear solution yet.  

The reason we can't just always use the built-in definition always is that a user may want to use a different implementation (e.g. pypyjs) to support python, and we should support that.

Maybe we don't want to save language definitions in the metadata at all, but should require them to be in a plugin cell, which would be visible and more explicit/obvious to the user.

**Comment by bcolloran** [comment]
i think that including language plugins in meta is an antipattern, and that we should deprecate it when we move to jsmd editing. i can't recall why it was added, but i think it was just for code highlighting. as you say @hamilton, it adds a weird subtle implicity, and i think there are other solutions, esp now that we've add mike's work around "known" languages

**Comment by mdboom** [comment]
Yeah.  I think as long as we continue to support explicit language plugin cells so the user can override the default behavior, we don't need the implicit content that goes in meta.  It would simplify a lot of things, actually.
