### ISSUE TITLE
esc key does not close menu

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1067]
Tested on extremely-alpha.iodide.io.

**Comment by bcolloran** [comment]
which menu? the top level hambrgr? i think the cell menu may be affected too.

**Comment by hamilton** [comment]
yes, all the client menus - hamburger, cell, and user.

**Comment by dmoco** [comment]
Also can't back out of sub-menu without closing whole menu, not even using esc key.

**Comment by bcolloran** [comment]
@hamilton, had you mentioned that getting rid of the  command mode `esc` key binding on the jsmd branch will fix this?

**Comment by hamilton** [comment]
Yes, this was closed with the `direct-jsmd-editing` branch merge, but kind of coincidentally. Closing.
