### ISSUE TITLE
when I open a revision and save it, the notebook url should reset to the full url and that saved revision should be the most recent (default) one

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1074]
At the moment, opening a revision and then saving it does not update anything to reflect that this revision is now on the top of the stack. I believe this should be the preferred behavior, but am open to anything (including a modal or something).

**Comment by bcolloran** [comment]
i think this is superseded by more recent discussions of (auto)saving/versioning/branching etc
