### ISSUE TITLE
our various url tricks (ipynb, jsmd, gist, etc.) should be server-side, not client-side

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1079]
There have been discussions about deprecating some of the query params we used before we had the server. I'm all in favor of it if we have a worthwhile path to replacing or enhancing those features elsewhere.

I don't know what this might look like, so please chime in y'all.

**Comment by bcolloran** [comment]
i am in favor of being more aggressive here-- these are really legacy bits, and add mess to the client code. i think we should get rid of them asap as part of MVP code quality clean up, and we can add them back in later.

@wlach @mdboom are you guys down with pulling out the url, gist, jsmd, and ipynb tricks from the client side?
