### ISSUE TITLE
Clean out github pages deploy target repositories

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1092]
Now that we're serving static assets on Heroku for most things, we should delete the associated repositories, e.g. master, master-eval, dist, dist-eval, stable, stable-eval.

**Comment by mdboom** [comment]
I think we should retain `dist` indefinitely, but the others can go.

**Comment by bcolloran** [comment]
perfect, thanks @mdboom -- just removed master-eval, dist-eval, stable, stable-eval.
