### ISSUE TITLE
replace "no history" in empty console with "welcome to iodide!" + some easy links about getting to help menu, examples, etc.

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1105]
This is a big piece of real estate in an empty notebook that we could better utilize to onboard new users.

**Comment by iFlameing** [comment]
I am working at this issue.

**Comment by hamilton** [comment]
Appreciate that @iFlameing! I would hold off on tackling it right away. We'll need to figure out what the right content + copy will be before accepting any PRs on this issue. With that in mind, do you have any mockups or ideas here?

**Comment by iFlameing** [comment]
We should be pointing to some example link show that any user can understand how to use the iodide.With welcome message, what you think ?.

**Comment by bcolloran** [comment]
closed via #1390
