### ISSUE TITLE
separate code evaluation inputs from outputs in console

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1107]
This is a bit of a follow-on for #1106, and maybe blocks it.

When I run some async code, I want to separate the posting of code input from outputs when printing to the console, so that we see that the code has hit the console even if the code creates a long-running or async process. Right now, input and output are tightly coupled, which creates a number of UX limitations. Specifically, there's no clear way of giving users the immediate feedback that the code has hit the console. It looks something like this:

```javascript
function evaluateCodeCell() {
  ... 
  return ensureLanguageAvailable(...)
    .then(runCodeWithLanguage)
    .then(addInputAndOutputToHistory)
}

```

I can in theory create the history item before running the code, then update with an action. 

```javascript
function evaluateCodeCell() {
  ... 
  return ensureLanguageAvailable(...)
    .then(createCodeInputAndOutputInHistory)
    .then(runCodeWithLanguage)
    .then(updateOutputInHistoryWithNewValue)
}

```

But that would require some complexities if the language hasn't loaded, since we need to tell the user that we have to load the language plugin before running the code. Which means the output ends up something like this:

<img width="533" alt="screen shot 2018-10-25 at 3 40 14 pm" src="https://user-images.githubusercontent.com/95735/47534467-517cc880-d86c-11e8-92e1-4ee62fd631c3.png">

We could probably make some changes to handle this particular use-case more gracefully with our existing setup, but it really side-steps a more flexible system and rules out any sort of future `console.log` interception. Between the code input print and the code output print, there might actually be all sorts of messages that pop up. What I really want is to just be able to print to console the fragments I want during the moment I want them without thinking about inputs and outputs quite so explicitly. Something like this:

```javascript
function evaluateCodeCell() {
  ... 
  return ensureLanguageAvailable(...)
    .then(addCodeInputToHistory)
    .then(runCodeWithLanguage) // there could be more history pieces that go to console here, or console.log down the line
    .then(addOutputToHistory)
}

```

I think the solution would be simply to implement the following history types based on the pieces of the ones we have now:

`EVAL_INPUT` - fires first in code chunk evaluation.
`EVAL_OUTPUT` - fires last in code chunk evaluation, uses the `ValueRenderer`.

and remove the code-and-output history types in favor of this workflow.

@mdboom @wlach @bcolloran curious to see what y'all think of this idea.

**Comment by mdboom** [comment]
I'm not too familiar with these parts of the code, so I can't speak to how easy/hard what I'm suggesting is, but I think part of what makes this hard is the 1:1 coupling of inputs to outputs.  It might be simplest to be able to just push individual things to the history in order, then we don't have to deal with tracking where we want the output to go -- it would just always go to the end of the history pane.  So the event chain of evaluating an async code cell would be something like:

```
PUSH_INPUT "import numpy as np; np.empty(5)"
PUSH_PROGRESS "loading numpy" -- uses a component just for progress messages
PUSH_OUTPUT [1, 2, 3, 4, 5] -- uses the reps system
```

IIRC, only the input blocks need to link back to the cells in the editor pane.

I think this is pretty close to what @hamilton suggests above, with the slight modification for special handling of "progress messages" that don't need reps.

**Comment by hamilton** [comment]
@mdboom I think our current system actually supports the progress stuff by default, since each history item gets an ID, and you can update the value by ID (this happens elsewhere I believe). I'm going to implement this all as a separate PR (not part of #1106) and I'll let that PR close #1053.

ALSO orthogonal but complemented by this approach is applying the console family - `debug`,`info`,`log`,`warn`,`error`, etc. There are a lot of functions implemented in `console`, and a number of them aren't probably 100% in-scope for iodide, but I suspect a number of them actually are. For instance, `console.time` and families might be quite useful.

My favorite part of this proposal is that will actually be a simplification of what we have, so a PR that closes this issue should be a nice reduction of complexity.

**Comment by bcolloran** [comment]
Hold off on this until I can comment. Also, this is not top priority in
general

**Comment by hamilton** [comment]
@bcolloran it ain't tagged "proposal" for nothing.

**Comment by hamilton** [comment]
Could you provide more context for this not seeming like a priority to you? I have already found the tight coupling of input & output to be slowing me down considerably in the past week.

**Comment by bcolloran** [comment]
+1 that we should decouple the input from output implementation-wise -- inputs should be able to immediately display in the console. But just to make sure we're all on the same page: UX wise, we should keep the tight 1:1 coupling of inputs to outputs. This was one of Adam Rules UX points that i very much agree with: users need to be able to clearly see which code generated which outputs.

so to psuedocode modify @mdboom's proposal, it might be better to have e.g.:
```
inputId = PUSH_INPUT "import numpy as np; np.empty(5)"
progressId = PUSH_PROGRESS(inputId) "loading numpy" -- uses a component just for progress messages
...
PUSH_PROGRESS(progressId)  "numpy loaded" -- uses a component just for progress messages
PUSH_OUTPUT(inputId) [1, 2, 3, 4, 5] -- uses the reps system
```

just pushing everything in pure chronological order could make the console very confusing.

that said, there will be exceptions for things like console.log and app info messages, which are side effects and not tied to a cell/code-chunk/evaluation. But we should make every effort to ensure that any operation kicked off by a code-chunk has a clear visual connection back to that code chunk

**Comment by hamilton** [comment]
As of the merge of #1483, this is fixed.
