### ISSUE TITLE
create a more useful help message if a user tries to locally load as noteobook after export

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1132]
<img width="1679" alt="screen shot 2018-11-06 at 10 55 12 am" src="https://user-images.githubusercontent.com/95735/48086793-8d8c2380-e1b2-11e8-91b5-a201a1d62f03.png">

I tried exporting a notebook to see what would happen, opened the file, and got this. I think we can probably catch this error and put in something much more useful that doesn't look broken.

**Comment by hamilton** [comment]
Even if we don't support this way of looking at an exported notebook (probably doesn't work anyway because of the realities of iframes) a more useful error message could guide a user gracefully in a direction

**Comment by bcolloran** [comment]
for the time being, export and standalone mode are not being supported, and i don't know that we'll have the time to fix them maybe ever since we have such a formidable queue of more pressing priorities.  i'd like to wontfix this @hamilton, what do you think?

**Comment by bcolloran** [comment]
closing this b/c our previous strategy for export is not going to be revived. when we look at export again, it will essentially be green field, so this version of this issue won't be relevant.
