### ISSUE TITLE
Add documentation on removing record of user's account from iodide site

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1148]
We should add some way for users to delete their account from our site.

From Michael Feldman:

```
For GDPR compliance, we'll need a way to be able to delete our storage of user data if they ask for it. Are we storing any of the data on our servers, or is it all on Github, so that users have control over it?
```

I think this only makes sense on the public site, so this feature should be enabled only with a specific configuration flag.

**Comment by wlach** [comment]
So on reflection today I don't think we actually need or necessarily want to implement this as a feature in the frontend for the MVP. 

It should be sufficient just to ask people to email us (me?) if they want their account / data gone -- maybe we could do this in the docs, under some kind of explainer? Note that we already have an easy way for people to delete their individual notebooks from the site, and we don't use anything from github that isn't already public, so essentially all this would entail would be a way to delete any record of their github account name from our server.

**Comment by wlach** [comment]
Confirmed with legal that just providing documentation on doing this is enough. I recommend a blurb in the iodide documentation clarifying the following two things:

1. You can always delete any notebook you have created with iodide
2. After you log in, we store your github account name on our servers. If you wish to have any record of this scrubbed (along with any notebooks that you haven't yet removed), please contact us at `<address>` (`wlachance@mozilla.com` works for now, I guess?)

**Comment by mdboom** [comment]
Thanks, @wlach.  Looks good enough.  Since this is still assigned for me, I'm happy to make a PR with the doc changes.

**Comment by bcolloran** [comment]
closed with https://github.com/iodide-project/iodide/blob/master/docs/policies.md
