### ISSUE TITLE
Get an error if I run pyodide.py_import twice

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1151]
How to reproduce: Go to https://extremely-alpha.iodide.io/notebooks/132

"Run all", then try to run the js cell again. It should print the value of "v" again, but instead I'm getting a `RuntimeError: index out of bounds` error in my pyodide console.

@mdboom any ideas what might be happening here? This bug seriously affects my ability to use pyodide in conjunction with javascript, since I need to constantly reload the notebook as I move back and forth between python and my javascript visualization code.

**Comment by mdboom** [comment]
Fixed and merged in iodide-project/pyodide#252.
