### ISSUE TITLE
deprecate the meta tag, add title features to server side

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1156]
As we move to a pure jsmd editing environment, we are going to deprecate the meta block in jsmd. For one thing, it is redundant - the server saves the title of the notebook. On the other hand, theoretically users will export their notebooks to run standalone. In this case, exporting should simply fill the `<head>` tag with the relevant metadata - title, author, export date, etc.

**Comment by bcolloran** [comment]
this PR will also need to save the notebook title directly to the sever when it is edited, and load the notebook title from the server rather than from the JSMD meta section
