### ISSUE TITLE
fix material-ui warnings from the Typography component

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1164]
Renovate recently upgraded `material-ui`, which now surfaces as deprecation warning. The instructions from the warning on how to migrate the params that'll disappear is pretty straightforward. This should be a quick issue for anyone.

**Comment by iFlameing** [comment]
can I work on it ?

**Comment by iFlameing** [comment]
And where I can find the typography component because I searched a lot but couldn't fine any component named typography can you help?

**Comment by bcolloran** [comment]
@iFlameing the typography component is used in 3 files. Did you try searching for "typography" within the project src folder? `ctrl+shift+f` in most IDEs and editors that support "search within project"

**Comment by iFlameing** [comment]
@bcolloran thanks I find it.

**Comment by iFlameing** [comment]
@hamilton  I changed the code in all the three files where the typography component. As mention in documentation to remove the deprecation warning I changed the code to this 
const theme = createMuiTheme({
  typography: {
    useNextVariants: true,
  },
});
but the deprecation warning is still showing in console.

**Comment by hamilton** [comment]
@bcolloran this appears to be fixed. Closing.
