### ISSUE TITLE
Make brotli compression of static resources work in server deployment

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1184]
As @wlach mentioned [here](https://github.com/iodide-project/iodide/pull/1178#issuecomment-439198007), I don't think the static resources are actually being served compressed.  Our toolchain has the ability to do so, so we should probably get that working.

**Comment by wlach** [comment]
I was actually wrong on this, it appears that we *are* currently serving gzipped assets to the client. Brotli compression is currently broken though. For that to work, I think we just need to add the [Brotli](https://pypi.org/project/Brotli/) package.

I think the steps to do this from a working server installation are just:

```shell
make root-shell
pipenv install Brotli
```

Then just submit a PR with the changed files.

**Comment by pradeepgangwar** [comment]
I am working on this.

**Comment by wlach** [comment]
Done now
