### ISSUE TITLE
Server notebooks get stuck on old pyodide versions

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1187]
Just noticed that my prototype dashboard is stuck using an old version of pyodide:

https://extremely-alpha.iodide.io/notebooks/131/

looking at the source, I see that the language plugin is hard defined inside the jsmd:

```
%% meta
{
  "title": "is nightly up to date yet?",
  "lastSaved": "2018-11-09T19:31:06.969Z",
  "languageDefinitions": {
    "py": {
      "languageId": "py",
      "displayName": "Python",
      "codeMirrorMode": "python",
      "keybinding": "p",
      "url": "https://iodide.io/pyodide-demo/pyodide.js",
      "module": "pyodide",
      "evaluator": "runPython",
      "asyncEvaluator": "runPythonAsync",
      "pluginType": "language",
      "codeMirrorModeLoaded": true
    }
  },
  "lastExport": "2018-11-15T17:59:07.115Z"
}
```

Not sure what the right thing to do here is. I can see why we would want to do this (so that old notebooks are guaranteed to stay working even across upgrades to the pyodide "stack"), but it also sucks not to be able to use the latest stuff if you want to. :) This is also rather confusing (it took me 5-10 to figure out what was going on, and I'm an iodide developer).

I guess we could offer some kind of interface to select/upgrade the language definitions/plugins used by a notebook? Any thoughts @mdboom ?

**Comment by mdboom** [comment]
I thought this was fixed (by ignoring the thing in meta, which could still be overridden with an explicit plugin cell).  Let me look and see why that's still happening.

**Comment by mdboom** [comment]
I think maybe this was just discussed, but not implemented.  I'll have a PR soon.
