### ISSUE TITLE
Consider using prettier to lint/format code

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1199]
Some of the spacing issues in #1197 suggest to me that using the airbnb linter isn't quite enough to catch all the nits that one might have about how a react file is formatted.

IMO we should just switch to using [prettier](https://prettier.io/), which you can configure to "auto format" your code so you don't even have to worry about violating our conventions/style. I believe it's mostly the same as the best practices we currently have, the one exception being that it requires/adds semi-colons to the end of lines. This is easy to disable with the the `--no-semi` option though (I used to feel like using semicolons was the one true way to write javascript, I've since softened my stance).

@hamilton @bcolloran @mdboom thoughts?

**Comment by iFlameing** [comment]
can I work on this ?

**Comment by wlach** [comment]
@iFlameing we have been holding off on this until a large refactoring branch is merged into master. I think I'd rather take care of this myself -- it isn't very complicated or difficult to implement, but there might be some strange issues with tests or production deployment that will require fiddling. Going to assign it to myself to make that more clear.
