### ISSUE TITLE
Remove /new page, always create and save a notebook when created

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1201]
The `/new` page shows a blank notebook on the client which is not yet saved on the server. This is a bit confusing, I think it would be better to just create and save the notebook automatically when the user creates such an object. This is related to #1037: fixing this might be best done as part of tackling that issue.

**Comment by wlach** [comment]
> oops - looks like the previously-referenced PR auto-closed this.

Yup, github's autoclose usually does the right thing but not in this case. :)

**Comment by wlach** [comment]
I'm going to take this one.

**Comment by iFlameing** [comment]
ok
