### ISSUE TITLE
Disable logout if using oauth identification

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1205]
It's not really possible to log out if using oauth identification (as we are internally), so let's just disable the logout button entirely if this is the case.

**Comment by iFlameing** [comment]
@wlach  what do you want me to do in this  issue should I remove the logout menu item from the [user-menu.jsx](https://github.com/iodide-project/iodide/blob/master/src/shared/user-menu.jsx).

**Comment by wlach** [comment]
@iFlameing Correct, you will need to check for the presence of a variable which indicates whether we are using oauth or github for authentication in [webpack.config.js](https://github.com/iodide-project/iodide/blob/master/webpack.config.js), then export that state into the component, I'd probably recommend `USE_OPENIDC_AUTH` [per its use in settings.py](https://github.com/iodide-project/iodide/blob/351d4dd5be17811a139e161623807e9489b5165e/server/settings.py#L49).

**Comment by iFlameing** [comment]
ok
