### ISSUE TITLE
proxy file loads via iodide server (with API keys etc)

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1228]
Sometimes we want to be able fetch data from an HTTP URL where we do not want to reveal the source to just everyone (e.g. because it contains a private API key). For this case, we could have the server fetch it on behalf of the user and store it in a file object. It would be great if you could also have the server optionally check for updates for this file on some user-defined refresh interval.

Obviously the server would store the URL + credentials which might still be sensitive. We may want to disable parts of this feature (i.e. at least the part that hides the URL) on the public server, as I don't think we want the liability of storing this type of sensitive data.

**Comment by bcolloran** [comment]
blocked by #1833

**Comment by wlach** [comment]
This is just the file sources work from last summer.
