### ISSUE TITLE
Make iodide homepage minimally viable for public launch

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1229]
The current iodide homepage is just lists all the notebooks, which is ridiculous and won't scale.

Strawman proposal based on earlier discussions of onboarding flow from our workweek last September:

* Add a simple admin interface to iodide, allow designating users as admins
* Add a "featured" field to the notebook model and let admin users add it
* Have homepage show a curated set of featured notebooks along with (say) the 5 most recently modified ones, along with some basic onboarding text

Open to other ideas, this is just a "better than nothing" sort of proposal. Ideally whatever we would come up with would be usable for the internal server (which actually has some of the same needs as our public site -- showcase good content and onboard our users).

**Comment by bcolloran** [comment]
i think this seems reasonable, but in the short term i wonder if it'd be faster to hand/hard code the featured notbooks rather than building the admin interface and the extra permissions / user role stuff that we'd ned for that?

@hamilton what do you think?

**Comment by hamilton** [comment]
I'll be taking this on by mostly replicating what we have on iodide.io right now.

**Comment by wlach** [comment]
I added the necessary scaffolding for letting people designated as staff or admin modify/delete the notebooks objects after logging in, this would easily let us designate a set of notebooks as featured
