### ISSUE TITLE
Pressing "log in" from action bar does not show modal

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1230]
We just added a login modal in #1196. This works great (mostly) though I just noticed it doesn't popup if you click on the log in link in the action bar:

![image](https://user-images.githubusercontent.com/20569/49256668-c14b1980-f3fd-11e8-9d43-d62b821c14fa.png)

Unfortunately this isn't trivial to fix (it will require moving some logic from `user-menu.jsx` to some new shared component/file, I think) but it is something we need to resolve before we publicly launch.

**Comment by iFlameing** [comment]
I see the issue,  when we click it is popping the window but not logged in the user. I am working on it.

**Comment by wlach** [comment]
@iFlameing not sure how far you got, but please hold off on this for now, I see some refactoring that needs to happen and we should probably wait for #1302 to land before really working on this.

**Comment by iFlameing** [comment]
ok

**Comment by wlach** [comment]
Ok! one thing that I'd like to see in a PR would be moving to having all react components using the login/logout methods in `actions.js`. as it is there is a fair amount of duplication.
