### ISSUE TITLE
closing a paren in python chunk causes unnecessary indentation on next line

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1244]
Reported by a Mozillian. Follow the notebook below.

@bcolloran I think you'll be able to fix this pretty quickly, so I'll assign it to you. Otherwise feel free to un-assign it

```

%% py

import pandas as pd
from io import StringIO
from js import command_csv

# delete the last paren and re enter it, then hit enter.
df = pd.read_csv(StringIO(command_csv))
                 

df.head()


```

**Comment by shreyanshdwivedi** [comment]
@hamilton I'll like to take this up. May need some guidance as I'm about to make first contribution to this project

**Comment by bcolloran** [comment]
@hamilton i just saw this, somehow it got past me during the work week i think. this is actually perhaps a bit tricky -- the autoindent formatters are pretty jacked across the board right now (in js too). something to do with the jsmd syntax modae and passing in local state.

@shreyanshdwivedi you are welcome to try this, but it might be a hard problem, and will probably take getting into the internals of codemirror. You'd probably mostly have to go it alone and find your way by googling things, so I'm not sure I'd recommend taking it on as a first project.

**Comment by bcolloran** [comment]
i think the indent is actually desirable; or in any case, it's not our bug, because i get the same behavior in the latest iodide as i do if i enter that snippet in:
https://codemirror.net/mode/python/
