### ISSUE TITLE
Example given at Iodide website docs results in blank

### ISSUE THREAD

**Issue by iFlameing** [iodide-project/iodide#1255]
I am exploring the Iodide docs example so that I can understand it in better context I found docs at this [link](https://iodide.io/docs/jsmd-and-importing-notebooks.html) and start reading it when click on the given example it open a notebook which contains nothing.

### What I Expected
It must show me some example.
we can reproduce it by just going to above link and click on last example.

**Comment by hamilton** [comment]
Yes, this is the intended behavior now that we've moved away from a jupyter-style interface. An example notebook that shows our new paradigm is here:

https://extremely-alpha.iodide.io/notebooks/154/

We'll be putting together much better documentation as we get closer to alpha.
