### ISSUE TITLE
as a user, I'd like some onboarding from within the notebook

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1266]
Now that we have finally arrived at the new direct jsmd editing paradigm (and thus the last major user-facing workflow change for iodide for a minute), we'll need to focus on onboarding. I think we all agree that software is only as good as its documentation, and our goal is to make Iodide as simple as possible to get started. Here are a few places we can help redirect & clarify the onboarding for the MVP launch:

1. __create a "docs" menu item__ now that we've reduced the number of buttons on the top left of the notebook, we could actually have a very visible "docs" menu that takes you to (a) API docs for the iodide API / jsmd format, (b) example notebooks, and (c) tutorials.
2. __update all the docs that exist in the repo itself__. We haven't done this in a while and this is going help a lot. Many users will likely find Iodide through the github repo and will look there for docs, so might as well keep these up to date.
3. __an empty console can include some easy onboarding text + links__. If you're on a "/new" page and there's nothing that's been evaluated, you can provide some easy onboarding. There's an issue out #1105 where that progress is tracked.
4. __have a `/start` URL that has some templated jsmd to get people started__, which is distinct from `/new` in that you have a template notebook.
5. __have the root level path show best-in-class notebooks__ - tracked in #1229, but do something like what I did for the open-source page for Iodide (notebooks w/ images that prospective users can explore, etc.)

Core members, please edit this top level comment and add some or provide feedback in further comments.

**Comment by bcolloran** [comment]
re 1: let's use tabs in the existing help pane -- could change to the menu item title to "help and docs" if you wish

re 2: you mean our readme and stuff or do you have other docs in mind?

we should probably also mark the iodide/examples repo as archived

**Comment by hamilton** [comment]
(1) yeah a tab _could_ work as long as users see it. I thought an actual toolbar menu item would be very hard to miss for new users, and is where most users would be looking for that.
(2) yeah our readme etc. - things committed in the GH repo. I don't think there is much we'll have to update on this point since we don't have many docs anyway. Probably a broader question about where we keep docs (API, jsmd, etc.) we should figure out before MVP launch

**Comment by bcolloran** [comment]
i think adding a toolbar button that takes you straight to the help pane seems fine. our menu is getting pretty short at this point now that we don't need a zillion items for cell management :-) since we have so few things, top level menu bar buttons should be ok

also just noticed that the menu items need clean up to, what with export being disabled

**Comment by bcolloran** [comment]
closed via #1390
