### ISSUE TITLE
deprecate iodide.evalQueue

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1281]
With the `fetch` eval type, a big majority of async use cases have been taken care of. This api was built around the cell architecture, and if indeed it will be useful to halt further evaluation in some way, we will have to re-implement this in some way to make more sense.

Deprecating this will require removing the use of `iodide.evalQueue` in `pyodide.js`, so once that's done, I can remove the file entirely in PR #1250. @mdboom does this seem like a pretty quick task?

**Comment by mdboom** [comment]
What are we planning to replace it with?  We still need a way to halt execution of the next chunk until a promise resolves.  This is used by `pyodide.loadPackage`, which will fail if the Python code runs before the package finishes loading.

**Comment by bcolloran** [comment]
@hamilton @mdboom i think we decided that we do want to adopt the approach used by observable: that a chunk which returns a promise will hold further evaluation until the promise resolves. Can that be used to satisfy this requirement? @hamilton  any thoughts on this?

**Comment by mdboom** [comment]
That would work for Pyodide -- it will require changes, but trivial ones.

**Comment by hamilton** [comment]
For background, having `iodide.evalQueue` made a lot more sense when we were in the cell paradigm. Since the only way to evaluate code was to enter it into a cell, we wanted a way to square some of the async circles inherent in JS in the cell world. The JSMD-only world + the fetch cell kind of removes the need for lots of workflows that `iodide.evalQueue` solved, so we're deprecating it until there's a strong need to explore that functionality in another way.

So the thing that was blocking this deprecation was pyodide, but I believe we merged https://github.com/iodide-project/pyodide/pull/280 which removed `iodide.evalQueue.await` from `pyodide.loadPackage`. At this point we don't use any of the `iodide.evalQueue` functionality anywhere in iodide.

@mdboom are there other places in pyodide that utilize `iodide.evalQueue`? They can probably just be removed entirely, since the API is just a stub that doesn't do anything.

**Comment by bcolloran** [comment]
@mdboom perhaps check out https://github.com/iodide-project/iodide/pull/1282 and do a quick test that everything works as expected. @hamilton once mdboom gives R+ let's merge that
