### ISSUE TITLE
Consolidate login code

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1313]
We currently have two definitions of login/logout code inside iodide:

1. One initiated from the header bar in actions.js: 

https://github.com/iodide-project/iodide/blob/1718d634e47c08a987fa3e37586c6613b7b783d1/src/actions/actions.js#L270
https://github.com/iodide-project/iodide/blob/1718d634e47c08a987fa3e37586c6613b7b783d1/src/components/menu/header-messages.jsx#L105

2. Another initiated from the user menu:

https://github.com/iodide-project/iodide/blob/1718d634e47c08a987fa3e37586c6613b7b783d1/src/shared/user-menu.jsx#L55

It would be nice to consolidate the login/logout code inside a single file, maybe `src/shared/actions/. Obviously some parts of the business logic in the header and user menu would have to stay there, but the core pieces of interacting with the server should be shareable.

**Comment by iFlameing** [comment]
I am working in it.
