### ISSUE TITLE
When not logged in, saving the notebook (via meta-s) succeeds, even though it really failed

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1322]

**Comment by wlach** [comment]
The save menu item is currently not visible when not logged in, so I'm not sure how people could accidentally try to save a notebook that they're editing.

I think we need a bit of a re-think around how editing while not logged in actually works, it's pretty confusing as things stand.

**Comment by hamilton** [comment]
@wlach `meta+s` still triggers a UI event.

**Comment by wlach** [comment]
This is true, I feel like maybe the right solution here is to move towards autosaving (#1037) though, I think it might not be that hard.

**Comment by hamilton** [comment]
I agree, and perhaps tagged saving ("save as") or something can be handled with a keyboard shortcut like `meta+shift+s`.

**Comment by wlach** [comment]
Per discussion, our stopgap solution here will be to show an error in the snackbar if the user is not logged in and they try to save. This should also cover edge cases like the user logging out in another tab.
