### ISSUE TITLE
disable system spelling error highlighting in console

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1323]
@hamilton spotted this in #1293, adding follow-up issue here

![image](https://user-images.githubusercontent.com/2380975/50790505-f60b8580-1273-11e9-9000-c5b7138f498b.png)

**Comment by hamilton** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by iFlameing** [comment]
@hamilton How I can reproduce this issue I am not able to reproduce it ?

**Comment by iFlameing** [comment]
I found it sorry for the above question.
