### ISSUE TITLE
iodide server deployment is super slow

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1338]
The iodide server takes quite a while to build on heroku (15-30 mins?), the main culprit seems to be compressing the scipy.data file from pyodide (which is 190 megs big) to brotli. This makes testing changes a bit annoying.

I think we should be able to cache the results of the whitenoise step using this technique:

https://devcenter.heroku.com/articles/buildpack-api#caching

... but we need to be careful to make sure we're not using stale assets. The best thing would probably be to just cache the pyodide assets specifically, and key that on the currently used version.

/cc @mdboom

**Comment by bcolloran** [comment]
:+1:  ah yes, that explains it. it felt slow but i wasn't sure why.

**Comment by mdboom** [comment]
There may be little practical benefit to brotli, too, given that it's already LZ4 compressed.  Maybe there's a way to turn off the compression for pyodide assets?  

I'm sure the ratio with brotli is better, of course, but the block-based LZ4 compression is tightly integrated with the virtual filesystem that emscripten provides.  You could probably build that on top of brotli and maybe come out ahead at the end of the day, but that's a project...

**Comment by wlach** [comment]
I would need to double check the numbers but iirc the savings of brotli
(vs. gzip or raw) are quite considerable (like in the 10s of mbs for that
scipy file), so we probably want to continue to use it. Quite surprising
that there would still be such savings with lz4 compression but there you
go...

**Comment by mdboom** [comment]
The data files are LZ4 compressed in independent blocks of, IIRC, 4kb, so I'm not surprised anything that uses a bigger window does better.  The advantage of the block approach is that you only have to decompress what you use. 

Hopefully much of this will improve soon once we have cross dylib support in emscripten and the Scipy size should be more than halved.
