### ISSUE TITLE
fetch cell errors do not un-halt the evaluation queue, so nothing else can be evaluated after error

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1372]
@hamilton plz, take a look at:
https://extremely-alpha.iodide.io/notebooks/210/

i reckon since you have the most experience with the fetch cell and evaluation machinery you should be able to make quick work of this one, but lmk if you want me to take a look

**Comment by hamilton** [comment]
Looking into this now. This bug must have been introduced sometime after the fetch chunk feature landed. Writing tests around this bit of functionality is hard, but it seems obvious to me now that we'll have to figure out something here.
