### ISSUE TITLE
functionality: Import from notebook / export selected cells as gist

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#138]
Based on our various disparate feature influences, I wanted to bring in one from Pro Tools that is invaluable. Pro Tools lets you import individual tracks from other sessions, with all accompanying audio and playlists, which makes merging a studio session w/ another trivial. I have found on multiple occasions that it'd be great to be able to import a cell from another saved notebook. This would save me from having to switch between notebooks to copy an idea I used elsewhere into another notebook.

**Comment by hamilton** [comment]
This feels like we've kind of already dealt with this issue. For one thing, we can open a notebook pretty easily using our url trick, and for another, we have export functionality now via #620.

**Comment by bcolloran** [comment]
do we still potentially want some UI around exporting selected cell(s) to a gist?

**Comment by bcolloran** [comment]
marking wontfix, we've moved on in many ways since this issue :-)
