### ISSUE TITLE
document plugin chunks in docs

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1382]
need some docs about how plugin chunks work, with example plugin snippets

**Comment by bcolloran** [comment]
hey guys, plz add your thoughts here:

https://github.com/iodide-project/iodide/blob/master/docs/language_plugins.md

I actually think this part of our universe has been very stable since we added Pyodide about 9 months ago, so I think we can invest in writing pretty detailed docs about how this all works. For example, it would be great if we could point the Julia team at this and they would be like "oh that's easy" and just go for it :-)

**Comment by mdboom** [comment]
I'm filling in the details now.
