### ISSUE TITLE
still have a blue button on the sign in page-- but can we just get rid of that sign in page?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1414]
(@hamilton and @wlach )
follow up from #1390 

![image](https://user-images.githubusercontent.com/2380975/51584860-00d93380-1e8c-11e9-96ff-e3e720317e22.png)

minimally, we should make this match our purpley gradient, but maybe we can just dispense with this interstitial page. can we do this via a modal or something, or are there technical reasons that we need to visit this in between page?

**Comment by hamilton** [comment]
can't comment on the interstitial itself, but I do know that if we just move to a regular iodide-branded button we'll get __More Purple™__ for free. I could see this being a modal as well.

**Comment by wlach** [comment]
Yeah, let's just kill this page and redirect `/new/` to `/tryit/` for logged out users. I'll do up a patch.
