### ISSUE TITLE
iomd is not HTML-escaped, allowing arbitrary code execution

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1416]
re #382 (which this supercedes) -- now that we're not focused on the single runnable file/bundle user story, it's really not necessary to patch the IOMD into that script tag. We should just send the IOMD down as a string in a IOMD object or script, or whatever mechanism we're using to send over eg userData. This will solve #382 and also maybe simplify our start up code a teeny bit.

**Comment by wlach** [comment]
I'm not convinced that putting iomd in a script tag is inherently a problem, however we do need to escape the content of the iomd, to disallow arbitrary code execution as you can (currently) see in this example:

https://definitely-staging.iodide.io/notebooks/63/

**Comment by wlach** [comment]
Ironically we are currently marking the iomd as "safe":

https://github.com/iodide-project/iodide/blob/c08375515cfe7d48259498c66f53bcaf63a0c9b4/server/notebooks/templates/notebook.html#L7

Likely we should change this from "safe" to "escape": 

https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#escape

We would have to add some code in the client to unescape this tag, but that shouldn't be too hard.

We should also add unit tests on both the client and the server to make sure this is working as expected.

**Comment by bcolloran** [comment]
> I'm not convinced that putting iomd in a script tag is inherently a problem

ya, it's not a big problem, just a bit of code clean up -- it's not really necessary to pull the iomd out of the DOM at this point since we have not been optimizing for the single human-readable HTML file for quite some time.

**Comment by wlach** [comment]
> > I'm not convinced that putting iomd in a script tag is inherently a problem
> 
> ya, it's not a big problem, just a bit of code clean up -- it's not really necessary to pull the iomd out of the DOM at this point since we have not been optimizing for the single human-readable HTML file for quite some time.

It is actually more efficient to embed the iomd in the document on the server side (saves an API round-trip), so my vote would be to keep things this way.

**Comment by bcolloran** [comment]
oh i wasn't proposing that we stop embedding the iomd in the page, just that we not put it in the `<script type="iomd">` tag and then parse it out at as text. i thought we should do it more like in the example at https://facebook.github.io/create-react-app/docs/title-and-meta-tags#injecting-data-from-the-server-into-the-page -- by setting it as a variable directly on `window` in a script tag, because i thought that we'd already been doing that for e.g. notebookInfo and other stuff. But i now see that we're getting notebookInfo with

```
const notebookInfo = document.getElementById("notebookInfo");
```

so i guess if we're parsing things out of script tags as our standard practice, then it's not a big deal to do so for the iomd also

**Comment by wlach** [comment]
This wouldn't be too bad an issue for someone (@ZiyaoWei? @Samrose-Ahmed?) to work on, maybe as a second bug. You will need to edit some parts on both the server and client.

There are two components here, first modifying the server to escape the iomd differently (write a unit test verifying that a tag like `<script>` gets escaped in `server/tests`):

https://github.com/iodide-project/iodide/issues/1416#issuecomment-509322803

Then modify the internal code that parses out the iomd to unescape:

https://github.com/iodide-project/iodide/blob/582c2c32df9e179759e7196da4a49ef6019f6533/src/editor/initialization/handle-initial-iomd.js#L3

**Comment by ZiyaoWei** [comment]
@wlach this definitely looks fun and I'll be happy to take it on! @Samrose-Ahmed sorry for scooping :-)

**Comment by wlach** [comment]
Awesome @ZiyaoWei -- please let us know if you need any help

**Comment by ZiyaoWei** [comment]
Turns out I completely forgot about the preview window on the right - the script aren't showing up in `md` and `html` sections! Will look into this - should that be a separate PR?
