### ISSUE TITLE
a python chunk with all the code commented out / an empty chunk will throw an error if run

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1423]
h/t @teonbrooks 

This chunk of python will throw an error

```python
%% py

# x = [1,2,3,4]
```

**Comment by hamilton** [comment]
this could be a pyodide error, not iodide.

**Comment by bcolloran** [comment]
empty cells error as well, e.g.
```
%% py


%% py
1+1
...
```

**Comment by hamilton** [comment]
cc @mdboom

**Comment by mdboom** [comment]
Fix in https://github.com/iodide-project/pyodide/pull/303

**Comment by bcolloran** [comment]
going to close on the iodide side
