### ISSUE TITLE
Don't define PYODIDE_VERSION on Heroku

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1426]
We're still in a phase where the interface between Iodide and Pyodide is evolving, so it's necessary to track specific versions of Pyodide for use with specific versions of Iodide.  As we ran into earlier today, it's pretty easy to forget to update the `PYODIDE_VERSION` environment variable on Heroku when this happens.  I think if we remove the variable from the Heroku config, it will fall back on the version defined in `webpack.config.js` and we would just have a single place to update.  I think this a case where we don't necessarily need deployment specific configuration, since it's really the version of Iodide used that determines what version of Pyodide we want to use.

@wlach: What do you think?

**Comment by wlach** [comment]
So I defined this variable in #1380 to fix #1338. You can see where we use it here:

https://github.com/iodide-project/iodide/blob/f4faf01b845311776d9a4abba52b88f4939236a8/bin/post_compile

There's probably a way to autodiscover the pyodide directory and compare it with what's with the cache, and then have the same "only compress if we don't have a copy with the latest version in the cache" logic. If we can do that, I'd be fine with removing the variable -- but I'd be reluctant to go back to the slow deploys we had before.

**Comment by mdboom** [comment]
Ah -- I didn't realize that's why it was there, but that makes a lot of sense.

Maybe the easy thing for now is just to add a comment in `webpack.config.js` that the corresponding variable in Heroku also needs to be updated.

**Comment by wlach** [comment]
Yup that wfm

**Comment by wlach** [comment]
I think I've changed my mind on this-- it's pretty annoying to have to always think about changing the PYODIDE_VERSION variable on heroku. I can't imagine it would be *that* hard to somehow figure out what the variable should be at build time, somehow.
