### ISSUE TITLE
incorrect "This notebook is owned by another user" message after login

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1440]
when i visit a notebook owned by my user via URL in a non-logged in state, the yellow message header first correctly shows the "You can modify and experiment with this notebook freely. To save to this server, you need to login." message.

however, after logging in, i am incorrectly shown "This notebook is owned by another user. Make a copy to your account." This goes away on refresh, but it should never be displayed in the first place when you log in under the owning account

**Comment by Irelokeh** [comment]
Hi Everyone, I am a GSOC student and I wish to work on this Issue. I am looking for a proper way to introduce myself but I have no need to open a new Issue for that. I learn there is a PR https://github.com/iodide-project/iodide/pull/1435 which may solve this as @wlach suggested.

Is this a good first Issue for me? (I am comfortable writing JavaScript and have 1 year and 5 months Solid experience with UX Engineering).

I am sorry to drop in Like this but I am in need of guidance and really wish to become a frequent  contributor of the Iodide project, Thanks for reading this far.

**Comment by ThobyV** [comment]
Hi Everyone, I am a GSOC student and I wish to work on this Issue. I am looking for a proper way to introduce myself but I have no need to open a new Issue for that. I learn there is a PR #1435 which may solve this as @wlach suggested.

Is this a good first Issue for me? (I am comfortable writing JavaScript and have 1 year and 5 months hands-on experience with UX Engineering).

I am sorry to drop in Like this but I am in need of guidance and really wish to become a frequent contributor of the Iodide project, Thanks for reading this far.

**Comment by ThobyV** [comment]
Hi Everyone, I  am Thoby, a GSOC student and I wish to work on this Issue. I am looking for a proper way to introduce myself but I have no need to open a new Issue for that. I learn there is a PR #1435 which may solve this as @wlach suggested.

Is there already a person working on this Issue? Is this a good first Issue for me? (I am comfortable writing JavaScript and have 1 year and 5 months Solid experience with UX Engineering).

I am sorry to drop in Like this but I am in need of guidance and really wish to become a frequent contributor of the Iodide project, Thanks for reading this far.

**Comment by wlach** [comment]
@ThobyV unfortunately I don't think this is a great starter issue -- it's rather complex and has a lot of moving pieces. Note that we're not planning to do a gsoc for the iodide notebook this year. If you're still interested in this project, I'd recommend playing with the prototype we have on https://extremely-alpha.iodide.io and then either circling back here for an issue to solve or finding your own thing to work on.
