### ISSUE TITLE
CONTRIBUTING.md is out of date and content overlaps with more up-to-date documentation

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1454]
@DevinBayly just noted that our current set of instructions in CONTRIBUTING.md doesn't work:

https://github.com/iodide-project/iodide/blob/433afa700c7c5df91facdbf7db3b600ff7a4ffec/CONTRIBUTING.md

There's a big pile of overlap between the content there and our developer documentation:

https://github.com/iodide-project/iodide/blob/master/docs/developer.md

Confusingly I think we also include this contributing file inside our docs site? (I can't check because the site is down right now: #1453)

https://github.com/iodide-project/iodide/blob/433afa700c7c5df91facdbf7db3b600ff7a4ffec/docs/contributing.md

Ideally we would just have one set of documentation in this area for us to point to. My vote would be to kill the top-level contributing.md in favor of putting it in a section of the docs. For more mature projects like Iodide, I think it's better to just have a placeholder README.md with a few salient pieces of information, and relegate any other text to a well-maintained docs site.

**Comment by bcolloran** [comment]
sounds good to me will, thanks for spotting that!

**Comment by wlach** [comment]
I moved contributing to the iodide docs a while ago.

**Comment by ZiyaoWei** [comment]
The contributing instructions on the GitHub page site (https://iodide-project.github.io/docs/contributing/) still seems to be out of date - not sure if a regression of this issue or is it a separate bug?

**Comment by bcolloran** [comment]
@ZiyaoWei thanks for noticing that, I've updated the docs
