### ISSUE TITLE
Get rid of hamburger menu

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1458]
I don't think there's much value to the iodide hamburger menu anymore and we should just get rid of it:

![image](https://user-images.githubusercontent.com/20569/52011625-80778b80-24a6-11e9-9840-545127c89a19.png)

* Help already has its own button elsewhere on the toolbar
* New notebook could be included under the user icon
* Clear variables would probably better be placed inside the workspace pane

**Comment by hamilton** [comment]
Yep, we don't really need this menu anymore! gj everyone

**Comment by iFlameing** [comment]
@wlach can you assign me ?

**Comment by wlach** [comment]
> @wlach can you assign me ?

I can't assign it to you, but in general it's ok to just say you're working on something in an issue like this.

**Comment by iFlameing** [comment]
ok

**Comment by bcolloran** [comment]
@wlach @hamilton -- i wonder if some of the features we plan to add to the notebook on our immediate roadmap (upload data, version management, merge) means it make sense to hang on to the menu for a moment? or do we prefer to expose that functionality with buttons directly on the navbar?

**Comment by wlach** [comment]
Unclear to me right now -- there's probably a point where we have too many buttons on the navbar, on the other hand a menu with just one or two things in it is also kind of ridiculous. But maybe we should, in fact, hold off on this for now until we're more sure on where we're going.

**Comment by wlach** [comment]
Let's hold off on this for now, it seems like the hamburger menu (or something like it) is useful for the short term.
