### ISSUE TITLE
need an iodide template notebook to help people use iodide when coming from redash

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1465]
@hamilton and @openjck. This is related to #1397.

**Comment by hamilton** [comment]
This has been implemented and shared on private channels. Closing for now.

**Comment by jezdez** [comment]
Oh, where has this been shared specifically? @openjck

**Comment by openjck** [comment]
Ah, I'm not sure. Can you say more, @hamilton?

**Comment by openjck** [comment]
Ah, found the link. I'll send it to you privately, Jannis.
