### ISSUE TITLE
potential issue with circle CI caching and tagged repos

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1476]
from an email thread involving me and @wlach on 2019-02-04, subject `[Workflow] Failed: iodide-project/iodide on / test-and-deploy (529b9f1)`

"Looking at the log, it looks like there's some issue with circle ci caching and tagged repos. I'd rather not look at this right this second, but please file an issue and I'll look into it soon."

**Comment by wlach** [comment]
Link to failing job:

https://circleci.com/gh/iodide-project/iodide/3984?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by wlach** [comment]
Didn't see this the last time we deployed, hopefully it was just an intermittent. I took a close look at our circle config and the only problem I found was a typo, which I fixed in 6dbdb53. Going to close this for now.
