### ISSUE TITLE
new output reps requiring strings break both julia and jsx handlers

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1488]
@bcolloran @mdboom I'm noticing on `master` that all the Julia reps are broken now upon moving to this new model. Second-guessing this approach right now since I think we want other wasm languages to have more flexibility.

**Comment by mdboom** [comment]
Is Julia returned *real* DOM objects rather than an HTML string, maybe?  Sorry I didn't track that rep PR as closely as I would have liked...

**Comment by hamilton** [comment]
Yes, that's the case with both of these plugins. For what it's worth I think we supported real DOM objects before.

**Comment by mdboom** [comment]
@bcolloran had mentioned (can't find the link) that real DOM objects would be hard to support if console moves out of the eval context used for the report, so I don't think it's an accidental change.  But maybe there's a way to handle the DOM -> string conversion at a higher-level point to make this work again.

**Comment by Keno** [comment]
I'm also happy to do whatever else is necessary here. Nothing in the way the julia integration works was a deliberate choice ;)

**Comment by bcolloran** [comment]
@mdboom yeah this is an intentional change. as you said, to make things a bit more modular going forward, we want custom reps to return HTML strings rather than DOM objects. IIUC, both Pyodide and Julia are both using Jupyter's protocol (which I believe works with html strings?). So hopefully this is not a tricky transition.

Of course, the best solution is to use the slick type conversion that some bits of Pyodide already takes advantage of to use the js object inspector. 

Anyway, the change is not a bug, but it causing a crash _is_ a bug... so we'll need to make sure that folks don't blow up their session if they accidentally specify a custom rep incorrectly. I'll change the issue to reflect that.

**Comment by mdboom** [comment]
Would it be possible to convert the DOM object from the object handler to an HTML string and use that?  I think that's effectively what the old version did.  If an when we need to work remotely, we just perform the conversion to HTML before passing it over the wire.

Additionally, how will it distinguish between a string of HTML and a regular string to display verbatim?

**Comment by bcolloran** [comment]
> Would it be possible to convert the DOM object from the object handler to an HTML string and use that? I think that's effectively what the old version did. If an when we need to work remotely, we just perform the conversion to HTML before passing it over the wire.

@mdboom i suppose we could do that. Is there any advantage to that other than not having to make the code change in pyodide and the julia implementation to do that conversion? I'm afraid that keeping this in will cause breakage down the road if implementations begin to lean on something that is likely to go away. I'd rather deal with this now while we just have two implementations to think about.

IIUC, we'd only need to change the render function in this bit of pyodide --
https://github.com/iodide-project/pyodide/blob/a38bf8af9beebd099631c9239938b388da0ccb03/src/pyodide.js#L369
-- to *not* do the *extra* step of converting the an HTML string into a DOM

And it looks like Keno et al just followed along with your code @mdboom -- i think this i simple change too, perhaps with the exception of the Plotly handling:
https://github.com/Keno/julia-wasm/blob/0330394e2d4a3c6c85304e9a47d04995a622ee2d/julide/julide.js#L372 



> Additionally, how will it distinguish between a string of HTML and a regular string to display verbatim?

At this point we only treat the string as html if it is returned by either (a) `.iodideRender` or (b) by an user-defined output handler. IIUC, when pyodide returns a "regular" string to display, it's not using a custom renderer, the eval function just passes out a JS object using some emscripten type conversion magic.

Of course, we don't check whether the string is valid HTML, that is up to the `render` method.



I think we may be missing each other on this stuff, perhaps we can talk about it briefly during tomorrow's call.

**Comment by mdboom** [comment]
I think I get it.  Thanks for explaining.  The changes to Pyodide should be straightforward -- I just wanted to make sure we still had the same flexibility we had to handle strings vs. HTML etc.  Sounds like we do.

**Comment by bcolloran** [comment]
obsolete / fixed
