### ISSUE TITLE
"Sign up for free" button leads to a 404

### ISSUE THREAD

**Issue by mythmon** [iodide-project/iodide#1494]
On https://extremely-alpha.iodide.io/, the sign up for free button leads to a 404.

### What I Did

Clicked the "Sign up for free" button on the homepage.

![image](https://user-images.githubusercontent.com/305049/52447475-aa9ffd80-2ae5-11e9-92ae-310c6eabb65a.png)

### What I Expected

I expected to be presented with a register/login page.

### What Happened 

I got sent to a 404 page:

![image](https://user-images.githubusercontent.com/305049/52447494-b986b000-2ae5-11e9-99b3-362d9250b214.png)

I think this is probably related to #1414

**Comment by hamilton** [comment]
Yikes, @mythmon thanks for the issue, will investigate now

**Comment by teonbrooks** [comment]
looks like it was a regression from removing the login logic: https://github.com/iodide-project/iodide/commit/0533862d91cef9971d80adb3ad229862c2c2229d

**Comment by hamilton** [comment]
@teonbrooks yes, just filed #1496 to fix this
