### ISSUE TITLE
Randomly generate default notebook names?

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1541]
We're seeing a lot of "Untitled Notebook" notebooks appear on extremely-alpha.iodide.io, now that people are slowly starting to discover the site. We probably should add a "published" field to the notebook so we can not index these kinds of test notebooks, but I wonder if it might also be useful/fun to randomly generate a name for a new notebook? Going with the iodide/scientific theme, I thought it might be fun to generate some random names based on molecules. Here's a simple notebook demonstrating the idea:

https://extremely-alpha.iodide.io/notebooks/302/

Sample output:

```
0: "dihydrogen triphosphide"
1: "trioxygen triargide"
2: "pentargon dihydride"
3: "pentargon tetrahydride"
4: "tetraoxygen pentargide"
5: "dihydrogen pentaphosphide"
6: "dioxygen dioxide"
7: "pentargon hexahydride"
8: "trioxygen tetraphosphide"
9: "hexaoxygen pentargide"
```

Thoughts?

**Comment by mdboom** [comment]
I like this a lot.  People complain about this problem in Jupyter notebooks on Twitter all the time...

e.g.: https://twitter.com/jakevdp/status/762755807389683712

**Comment by hamilton** [comment]
Love this idea a ton. One thing to think about here (mentioned on gitter): might be worth figuring out how to make sure we have a lot of rhythmic / tonal diversity in the generated titles so they're easier to read down a list of untitled notebooks. We could have a generator for astronomy, machine learning / stats, neuroscience, etc.

**Comment by bcolloran** [comment]
Also love it! Let's go for it! :-)

**Comment by robhudson** [comment]
ATMO has a similar thing for naming the servers...
https://github.com/mozilla/telemetry-analysis-service/blob/master/atmo/names.py
