### ISSUE TITLE
the iodide API docs are out of date

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1558]
We should remove whatever is stale about https://iodide-project.github.io/docs/api/

**Comment by bcolloran** [comment]
i just removed the stuff about the environment, which i think we'll remove in favor of a proper upload API.

eval queue is also deprecated now, right?

**Comment by hamilton** [comment]
Yep, we can remove that too

**Comment by bcolloran** [comment]
@hamilton i think this is now up to date. can you review https://github.com/iodide-project/iodide/blob/master/docs/api.md and close this issue if it looks ok to you? thanks!
