### ISSUE TITLE
no link to docs anywhere on the server

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1563]
We should probably have something somewhere

**Comment by wlach** [comment]
A link to the docs is actually in the user menu :)

![image](https://user-images.githubusercontent.com/20569/53613283-a37b8500-3ba3-11e9-83e9-040f993e544b.png)

I have no objections to adding them to the footer as well tho

**Comment by hamilton** [comment]
Indeed :) totally didn't even think about that, but yeah as a new user on a technical project page I like to ctrl+f for 'docs' so I put out a pr with one extra link. can't hurt
