### ISSUE TITLE
Notebooks owned by other users don't tell you who the user is

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1580]
@DevinBayly noticed this with his brain notebook, which was recreated by @hamilton a few months ago:

https://extremely-alpha.iodide.io/notebooks/194/?

If you open it as a user who is not hamilton, you see this banner:

![image](https://user-images.githubusercontent.com/20569/53761006-6e687e80-3e92-11e9-8494-46209a099ce6.png)

Or as an anonymous user:

![image](https://user-images.githubusercontent.com/20569/53760996-67da0700-3e92-11e9-8e6e-7c367606ab38.png)

I think we should show the name of the user who created it in the banner. This should be available in the `notebookInfo` script blob.

**Comment by wlach** [comment]
@hamilton @bcolloran -- what do you think about the above? After thinking about it a bit, I feel like we should probably do something more fundamental medium-term (e.g. putting the notebook owner right in the header bar somewhere) but I feel like just updating the infobar would be a good short-term win here.

**Comment by bcolloran** [comment]
ya, adding the username and linking back to that userrs page sounds great to me will! thanks!
