### ISSUE TITLE
disable the "ctrl-d" multiple cursors shortcut within codemirror code editors

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#159]
ctrl-d for declared variables pane conflicts with codemirror sublime multiple cursors shortcut

**Comment by bcolloran** [comment]
also, ctrl-d appears to delete a line in the editor. yuck. we should just disable ctrl-d in the editor probably? will anyone miss multiple cursors?

**Comment by hamilton** [comment]
I personally don't think so. I'd be in favor of removing it.

**Comment by bcolloran** [comment]
great, i'll update the issue name

**Comment by fkohlgrueber** [comment]
I'd like to work on this issue
