### ISSUE TITLE
If I am viewing a revision, autosave should be off by default

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1593]
We are quickly getting to the point where we need a real strategy around how revisions operate (which is exciting!), but if I am viewing a revision, I believe we should probably have all autosave off by default until we have a better idea. The point of viewing a revision in a notebook (for now) should be primarily to investigate how something works. With #1565, however, viewing a revision will quickly begin adding another revision to the stack, which is most assuredly an unintended side-effect.

So we will need _some_ strategy / reasoning around how to adequately view revisions. The revision viewer is really not enough, since the point of viewing a revision is so I can run it and check the code logic and report, not just looking at the source.

**Comment by bcolloran** [comment]
added some thoughts on the strategy at #1592

**Comment by wlach** [comment]
I mentioned some of my thoughts on this there:
https://github.com/iodide-project/iodide/issues/1592#issuecomment-471062649

The pertinent suggestion is:

> Maybe if the user is looking at an older revision of a notebook, we could just turn _off_ autosave, but give the user an option to:
> 
>     1. Save the revision to a _new notebook_
> 
>     2. Overwrite the existing notebook

I would suggest communicating this state (and the possible actions) via the header bar.
