### ISSUE TITLE
move info about cursor position to redux store, and generally decouple the app from codemirror

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1594]
we should move the current cursor position into the redux store and fire an action to update it whenever the cursor moves, instead of just checking the cursor position inside of the evaluateText action. this will more cleanly decouple the actions from the internals of the editor, which will (1) push this into our state tree, where we have more kinds of sanity checking and thus bugs like this are easier to to catch in advance, and (2) make it easier to migrate to Monaco down the line. (I don't know why i didn't do this to begin with -- this was my bad during the jsmd migration)

**Comment by hamilton** [comment]
@bcolloran can we close this issue or repurpose it?

**Comment by bcolloran** [comment]
ah yes, this is done via #1597, thanks for catching that hamilton!
