### ISSUE TITLE
Reference links to dom elements broken

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#1601]
using MASTER

### What I Did
I'm trying to make a reference link to a dom element but it doesn't resolve to the location.
https://definitely-staging.iodide.io/notebooks/19/

@wlach suggested a solution to this bug using [this](https://stackoverflow.com/a/19378662).

**Comment by teonbrooks** [comment]
I think it has something to do with how markdown-it parser renders anchor tags and that its html reference is not pointing to the base but to the `.app` source. i will be in sf tomorrow and i will follow up to see if someone can work with me on this bug

**Comment by teonbrooks** [comment]
a few things @hamilton and i just discussed.
- the links are opening to a new page (`target=_blank`). this will prevent the referencing within a page
- the anchor needs to reference the iframe, which has the panels, and scroll to those location. the top-level link would need to be able to point to an iframe anchor

open questions: 
- does using the base tag in an href allow the link to point to the correct location in the iframe?
- would we need to intercept the anchor links to point to the correct location?

**Comment by teonbrooks** [comment]
a few things @hamilton and i just discussed.
- the links are opening to a new page (`target=_blank`). this will prevent the referencing within a page
- the anchor needs to reference the iframe, which has the panels, and scroll to those location. the top-level link would need to be able to point to an iframe anchor

open questions: 
- does using the base tag in an href allow the link to point to the correct location in the iframe?
- would we need to intercept the anchor links to point to the correct location?

**Comment by wlach** [comment]
Sorry I meant to comment after reopening but got distracted:

#1698 fixed an aspect of this, but I would also like to be able to persist links/state across reloads of the report view. e.g. something like this should work for our athena query dashboard:

https://data-iodide.stage.mozaws.net/notebooks/22/?viewMode=report#wlachance@mozilla.com

This would require some things which are rather involved (i.e. sharing the bookmark state between the editor and the iframe) but the use case is compelling IMO. We can open a new issue for this if it's easier.

**Comment by teonbrooks** [comment]
ah, gotcha, that makes sense, yeah @hamilton and I chatted about that as well. and i agree, that would be super useful and very compelling

**Comment by wlach** [comment]
I keep on wanting this for various things (most recently for a redash diff tool I was working on: https://iodide.telemetry.mozilla.org/notebooks/405/), I might look into implementing this soon.
