### ISSUE TITLE
as a user, I would like a way of forking any notebook (including my own) from the notebook menu

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1621]
I have bumped up to this use-case a number of times. While I know the workaround - copy and paste the old editor content into a new blank NB - it might be nice to provide a menu item that does this for me.

**Comment by teonbrooks** [comment]
just bumping this issue up. I would like to be able to establish a template for reports that I am working on and be able to fork them from a "template" notebook

**Comment by wlach** [comment]
Looking into this one.
