### ISSUE TITLE
file not found error for a local file

### ISSUE THREAD

**Issue by six42** [iodide-project/iodide#1645]
Hi iodide team,
first thanks for this nice tool. I just started to explore it.

I tried to fetch files stored in my notebook but get a file not found error.

### What I Did
I forked https://alpha.iodide.io/notebooks/154 (Saving an image to iodide, loading it into a notebook)
my version is: https://alpha.iodide.io/notebooks/800
I then saved the video localy and uploaded again in my workbook
https://alpha.iodide.io/notebooks/800/files/gritty.mp4

### What I Expected
My notebook (800) should no work identical to the original(154)

### What Happened 

while the original is working my copy is not but falling with the following error in the console window:
```
blob: gritty = files/gritty.mp4

ERROR: files/gritty.mp4
	Error: 404 Not Found (files/gritty.mp4)

```
### (if applicable) notebook that reproduces bug 

https://alpha.iodide.io/notebooks/800

Thanks for your help

**Comment by hamilton** [comment]
Thanks for the issue @six42. I'm having trouble reproducing this error - it seems like the upload is available, and when I hit "run all" (or just hit the "run" button multiple times on [your notebook](https://alpha.iodide.io/notebooks/800)) I see the short video pop up as expected.

Can someone else verify what I'm seeing?

**Comment by bcolloran** [comment]
Working for me also.

Other notes: 
- that gritty video is hilarious
- iodide works much better than expected on mobile

**Comment by six42** [comment]
Thanks @hamilton and @bcolloran for taking the time to check.
It works now for me as well.
Reproduced my steps but still working.
Maybe a problem with a first login only.
