### ISSUE TITLE
fuzzy text menu search a la figma

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#165]
see #150. We will be adding more menu options in the coming months, and it will be nice to have something similar to what figma has:

![figma](https://media.giphy.com/media/xT9IgHl36aTKrbtVrG/giphy.gif)

**Comment by bcolloran** [comment]
i'm going to close this for now -- we bth know that this option exists if we ever actually need it, but for now (and for the last year+) we really haven't. so wontfix until the need exists
