### ISSUE TITLE
You have a gorgeous logo

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/iodide#1653]
But it is only available as a PNG file.  Any chance of getting an SVG version?

Thanks 
Chris

**Comment by bcolloran** [comment]
Thanks @PythonLinks. funny, we've been talking about the need for a "real" logo for more than a year (#267) :-)

in any case, svg is here: https://github.com/iodide-project/iodide-graphics/blob/master/iodide-sticker-2-paths.svg

**Comment by bcolloran** [comment]
(oh also, just out of curiousity: why do you want an svg version in particular? :-) )

**Comment by PythonLinks** [comment]
Thank you for asking.  
I built a content management system.  
http://distributed-wiki.com

It is a tree of wiki pages. 

I am about to add in an Iodide content type.   (If I can figure out how to install Iodide on my linux server.)

So I need an icon for the the management view.   The management view lets you see all of the objects in one node of the tree, and rename, cut, copy, delete and paste them. 

Maybe I will have two content types.  One for Iodide, and one for Pyodide.  But with the svg, I can easily change the I to a Py, and shrink it down.  Maybe I will change the color of the icon for Pyodide objects. 

Thanks
Chris
