### ISSUE TITLE
the notebook revisions list on the server needs time stamps

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1658]
HH:MM:SS

**Comment by hamilton** [comment]
for reference, this is an example of what i mean. 

https://alpha.iodide.io/notebooks/341/revisions/

It's impossible to do any real forensics on my revisions if I can't identify whjen i actually worked on these.

**Comment by wlach** [comment]
Longer term we should probably try to unify the revisions list view on the server with the one inside the client, but this seems like a logical improvement.

The code to change is here:

https://github.com/iodide-project/iodide/blob/4ef000d1c936bd3fedc9316822ee0dc07aebc435/src/server/pages/revisions-page.jsx#L207

The local revision formatter uses this code to format the date in the format @hamilton is suggesting:

https://github.com/iodide-project/iodide/blob/4ef000d1c936bd3fedc9316822ee0dc07aebc435/src/components/modals/revision-list.jsx#L63

**Comment by SJasoria** [comment]
Hi!
I'll take up this bug if no one else is hacking on it

**Comment by hamilton** [comment]
@SJasoria feel free to take this one
