### ISSUE TITLE
come up with app error reporting mechanism

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#166]
We report cell execution errors in the output of the cell, which is the right spot. But we do not have a way to report any other app errors. JSON parse errors when importing notebooks, for instance. There will likely be other ones as well.

There are a few options. I'm in favor of using the [Material UI Snackbar](http://www.material-ui.com/#/components/snackbar) component, which pops up a small, unobtrusive component that clicks away.

**Comment by hereisnaman** [comment]
@hamilton @bcolloran I was working on solving saving unnamed notebook issue https://github.com/iodide-project/iodide/issues/208. As @bcolloran said there in the thread, it would be good to show a snackbar in case of explicit saves. I can build a general use component for it, which will integrate with both jsmd execution errors and other app errors. 

I need to know that how will we show and scroll to the relevant output in the history window when clicked on trigger(click on snackbar or auto), inpage link ? Please suggest.

**Comment by bcolloran** [comment]
we have this now!!
