### ISSUE TITLE
Iodide Installation Documentation

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/iodide#1660]
Short summary of the bug. 
bin/install_pyodide does not work. 

Please include the IODIDE version number where you found the bug
MASTER

### What I Did
$git clone https://github.com/iodide-project/iodide
$cd iodide
$bin/install_pyodide

### What I Expected
For it to download and install Pyodide.

### What Happened 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     17      0 --:--:-- --:--:-- --:--:--    17
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
(wiki) lozinski@pythonlinks:~/code/cromlech/wi

Part of the problem is that I do not know what the directory is supposed to be called.  If I did, I could just go ahead and execute a command to create and populate it.

**Comment by PythonLinks** [comment]
The reason I titled this issue  Installation Documentation is because I was just writing the installation documentation, when I got stuck on this item.  Here is the current version. 

#Software Installation

The first thing you have to do is to install Node.   You can read more here:
     https://nodejs.org/en/download/package-manager/

Then git clone the iodide repository.
    $git clone https://github.com/iodide-project/iodide

Change to the iodide directory
    $cd iodide

Make the software
    $ make

If you want to also use Pyodide
    $bin/install_pyodide

The Pyodide repository has instructions for how to make it.
   https://github.com/iodide-project/pyodide

I found the docker approach very clean.   There is a docker container for iodide, but not yet documented.

Then you want to compress the files in the build directory, so that they serve faster.
see: https://devcenter.heroku.com/articles/buildpack-api#caching
     $bin/post_compile

Then there are some things to be done before deploying.
   $bin/pre_deploy

And finally you can run the server.
   $bin/run

**Comment by PythonLinks** [comment]
Also if I do 
git clone ...
cd iodide
make
bin/post_compile

I get the error message
bin/post_compile: line 12: CACHE_DIR: unbound variable

I suspect that there is some order in which I should be executing commadns, but I do not know what it is.

**Comment by wlach** [comment]
That script isn't meant to be run standalone,  it's meant to be run by webpack:

https://github.com/iodide-project/iodide/blob/master/webpack.config.js#L178

I'd recommend reading through the instructions on getting a local development environment going:

https://iodide-project.github.io/docs/local-dev/
