### ISSUE TITLE
run ./manage.py migrate from make shell

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1661]
per conversation with @wlach on gitter, we should run ./manage.py migrate from make shell automatically

**Comment by wlach** [comment]
I actually meant run it from `make up`, but it appears it already does this:

https://github.com/iodide-project/iodide/blob/master/bin/run#L31

So in fact you didn't need to run the make shell thing I suggested -- just shutting down the server and running make up should have done the job. There's probably something we could do to make it more obvious you need to restart the server / run the migrations, though I'm not sure if it's worth the effort: I think this might be one of the things that we expect people working on / using the server to just know (or learn through experiences like this one).

**Comment by bcolloran** [comment]
(hmm fwiw, i did kill my server and re-run `make up`. i've never had a problem with that before, so hopefully this was a one-off)
