### ISSUE TITLE
branding, colors, type, etc. for the MVP

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#167]
maybe we should add a splash of color!

maybe something from the FF palette to pay homage to our mozillian roots? -- https://www.mozilla.org/en-US/styleguide/identity/firefox/color/ 
or something else entirely if we're not feeling that.

(i am not attached to this in general, nor to any particular color; we can stick with black if we want.)

**Comment by hamilton** [comment]
closed with #1390.
