### ISSUE TITLE
Http2 Trouble + compliments.

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/iodide#1693]
So first of all my compliments on this newest release. 
I love that you organized the src directory into 
(editor  eval-frame  server  shared).  Just 4 items. 
Now it all makes sense to me.   The previous version, I never knew where to look for stuff.  This is much much better.

Next compliment, I was having a huge problem with it secretly loading some file or other.  After searching for a day, I went to upgrade and file a bug report, but the new version no longer secretly loads a file.  Thank you.  Most appreciated. 

But of course not all is well.  My new problem is with http2. I thought that was between the browser, and nginx.  I have literally no idea why  I am having this problem. 

Short summary of the bug. 
MASTER, 3 days old version. 

When starting up an example I get the following message on the right hand side. 

"Firefox doesn’t know how to open this address, because one of the following protocols (http2) isn’t associated with any program or is not allowed in this context."

### What I Did
Installed the newest version.  
went to my version of the software, and got the error message. 
Upgraded NGINX.  Used two different sites to test and confirm that http2 is working on my url. 

### What I Expected
well I did not expect the upgrade to work on the first try, but l I certainly did not expect an http2 problem. 

I will leave my dev server up from 7 pm  until midnight east coast time for the next few days, so that you can take a look at it, if you want. 
https://dev.pythonlinks.info/iodide-notebooks/a-tour-of-iodide/

And thanks again for making the software directory structure much more understandable.

**Comment by PythonLinks** [comment]
Okay, that was my mistake. 
On a clean install I had to change the url. 
I managed to change it to http2, instead of https.
Since i have never had to deal with http2, I was quite confused, and looking in all the wrong places. 

My apologies.  In any case the compliments still stand. 
Chris

**Comment by bcolloran** [comment]
glad you figured it out, and thanks for the compliments :-)

sounds like we can close this issue
