### ISSUE TITLE
the server needs to fill out appropriate metadata in head in the notebook template

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#1696]
You'll notice this if you post a notebook link on Twitter, slack, etc. - there is no preview to be had. We can easily provide additional metadata in the header template, making it easier to index Iodide.

Once we have other forms of notebook metadata (description, tags, representative image, etc.) those can also be added.

**Comment by wlach** [comment]
@rafrombrc @robhudson this would be another interesting one to look at, if you're looking for a diversion.

**Comment by wlach** [comment]
Ok, this is really low effort and would provide a large benefit, so let's just get this done. I'm gonna give some clearer instructions in the hope that someone feels motivated to create a PR, if they don't I'm just gonna do it myself. :)

This article describes in detail what slack needs: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

So very explicitly, I think we want the following tags:

```html
<meta property="og:url" content="{{ url }}"/>
<meta property="og:title" content="{{ title }}"/>
<meta property="og:site_name" content="Iodide"/>
<meta property=”og:image" content="{{ iodide_icon }}"/>
```

The place to put this data would be inside this template:

https://github.com/iodide-project/iodide/blob/master/server/templates/base.html

I think most of this should be very straightforward to copy from what's already there, the exception being the url, which I will leave as an exercise for the reader.

**Comment by bcolloran** [comment]
@wlach @teonbrooks did you guys fix this recently?

**Comment by teonbrooks** [comment]
yup, #2344 closed this
