### ISSUE TITLE
Should only show notebooks on the front page that have been changed in some interesting way

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1710]
Right now the "firehose of notebooks" on alpha.iodide.io is dominated by notebooks which are forks of existing ones, with no changes:

![image](https://user-images.githubusercontent.com/20569/55648590-bc80e280-57ae-11e9-84f9-8377eacf9429.png)

I would propose a simple changes to make it much more likely that the information will be useful/interesting:

1. Add a boolean `user_titled` field to the notebook model. Defaults to `False`: https://github.com/iodide-project/iodide/blob/b45ecdc126a2db79cba30f3cd9eb5ceba2e1b6c4/server/notebooks/models.py#L18
2. When the notebook title changes, this field changes to True (if it wasn't already)
3. Forked notebooks do *not* inherit the setting.
4. The main page should filter by this attribute (being True of course) in order for a notebook to appear in the firehose: https://github.com/iodide-project/iodide/blob/b45ecdc126a2db79cba30f3cd9eb5ceba2e1b6c4/server/views.py#L21

Comments/feedback on this approach welcomed. Might be an interesting issue for @robhudson @rafrombrc. I think this can entirely be done inside `server/`. Be sure to add some tests if you do tackle this!

**Comment by bcolloran** [comment]
Would it be possible to check how many revisions a notebook has, and only show notebooks with some number of revisions? In that case, we could set a higher threshold -- e.g., 10 revisions would indicate that someone was in the notebook for at least a five minutes and made several changes (even if they didn't get around to changing the title).

if we do this, we could just use the existing data without needing to update the notebook model (we could handle it in the query logic), or if there is reason to have concern  that the query would be slow using the existing tables, how about adding a `number_of_revisions` int to the notebook model?

**Comment by wlach** [comment]
> Would it be possible to check how many revisions a notebook has, and only show notebooks with some number of revisions? In that case, we could set a higher threshold -- e.g., 10 revisions would indicate that someone was in the notebook for at least a five minutes and made several changes (even if they didn't get around to changing the title).

That could work, it would be an aggregation query and wouldn't be too terribly slow. However I think there are a few reasons why it would be useful to do it this way:

1. We could key certain user interface behaviour off of whether the title has ever been changed or not (e.g. we could default to blanking out the title altogether when the user clicks on it if they never explicitly set a title and the notebook wasn't forked)
2. Changing the title I see as a strong signal that the user considers the notebook ready for publication, rather than just a one-off experiment.

> if we do this, we could just use the existing data without needing to update the notebook model (we could handle it in the query logic), or if there is reason to have concern that the query would be slow using the existing tables, how about adding a `number_of_revisions` int to the notebook model?

If we're going to do that, I would start with an aggregation (see above) and go from there. My first step to optimizing the query itself would probably be to store the results in memcache/redis, since it's currently the same for all users.

**Comment by rafrombrc** [comment]
I've started on this... unless someone feels strongly otherwise, I'm gonna just do the "only show queries that have >=10 revisions" as a starting point, since that addresses the original pain point, doesn't require a data model change, and is the least amount of work.

@wlach would you be able to add me as a contributor so I can claim this issue, or at least assign it to me so toes don't get stepped on?

**Comment by wlach** [comment]
Sure, that sounds like a reasonable place to start. @rafrombrc -- I added you as a collaborator on this repo.
