### ISSUE TITLE
notebook ownership information in redux store is not updated appropriately when notebook is forked

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#1746]
### What I Did

- Opened https://definitely-staging.iodide.io/notebooks/26/
- Click "copy to your account"
- Run the first cell:
```
%% js

iodide.file.save('here is a test file', 'test.txt', {overwrite: true})
```
- Got error `"only the owner of this notebook can save files"`

### What I Expected

I could save files to the forked copy of the notebook.

**Comment by mdboom** [comment]
Note and/or clue: Reloading the new fork seems to resolve the issue.

**Comment by hamilton** [comment]
Got it. It sounds like `state.notebookInfo` & family is not updating when the notebook is forked, which would cause that error to be thrown.

**Comment by hamilton** [comment]
Seems like there's more at play here. I have a branch that fixes this as I expected, but loading within that same page does not work (I get a 404). Will have to dig a bit deeper to see why.
