### ISSUE TITLE
A value renderer encountered an error.

### ISSUE THREAD

**Issue by renedlog** [iodide-project/iodide#1748]
### What I Did
code sample:  https://alpha.iodide.io/notebooks/300/

Steps:
Run Full Notebook -> Workspace -> Expand pyodide object -> "A value renderer encountered an error."

### What I Expected

Do not allow expansion or do render an info why it cannot expand (catch error).

### What Happened 

Error msg

### (if applicable) notebook that reproduces bug 
https://alpha.iodide.io/notebooks/300/

**Comment by bcolloran** [comment]
superseded by #2254
