### ISSUE TITLE
Add Screen Reader Support to the Editor

### ISSUE THREAD

**Issue by frastlin** [iodide-project/iodide#1749]
I ran the [Example application](https://alpha.iodide.io/tryit/) in Firefox using [NVDA 2019.1.1](https://www.nvaccess.org/download/)
and when I enter edit mode (or focus mode) in the editor, NVDA just reads "blank" when arrowing up and down the content. NVDA reads the content in brows mode, but it is not possible to edit text in brows mode.

Editors such as MCE, Google Docs, and Monaco work perfectly well with a screen reader and allow for massive amounts of text in the document.

There is also an example of how to do a text editor from [AccDC.](http://whatsock.com/tsg/Coding%20Arena/Web%20Chat%20and%20Dynamic%20Message%20Announcement/Web%20Chat%20(Static)/demo.htm)

### What I Did

Opened the [sample notebook](https://alpha.iodide.io/tryit/)
went to the second edit field, hit enter, and used the up and down arrow keys to move through the text.

### What I Expected

I expected NVDA to read the first lines of text:

> %% md
> # Welcome to Iodide!
> Type `shift+enter` to evaluate a chunk and move to the next, or Press 

### What Happened 

NVDA just said "blank".

### (if applicable) notebook that reproduces bug 

https://alpha.iodide.io/tryit/

**Comment by hamilton** [comment]
Thanks for the issue @frastlin! Moving to Monaco is on our immediate roadmap, which will solve this issue. We are tracking this issue in #1629, and will take your issue as yet another sign that we need to get this right ASAP so users with screen readers can work in the editor. I'm going to close this issue in favor of the earlier one.
