### ISSUE TITLE
dependency error on master

### ISSUE THREAD

**Issue by ctmattice** [iodide-project/iodide#1778]
Short summary of the bug. Please include the IODIDE version number where you found the bug - if you are just running locally (building for dev or prod) you can put MASTER

### What I Did
ran -> git pull origin master 
for my local copy.

code sample or exact steps that causes the bug
make build

### What I Expected
completion without errors as other builds

explanation, imgs, etc.

### What Happened 

build reports:
Downloading https://files.pythonhosted.org/packages/fd/2a/b51377ab9826f0551da19951257d2434f46329cd6cfdf9592ea9ca5f6034/whitenoise-4.1.2-py2.py3-none-any.whl
requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.

explanation, imgs. etc.

### (if applicable) notebook that reproduces bug 

link to the notebook that reproduces the bug. the smaller the better. you may wish to use https://definitely-staging.iodide.io/ (our staging environment, deploys from master) for creating/sharing the notebook.

**Comment by wlach** [comment]
@ctmattice I'm pretty confused, are you running the instructions here:

https://iodide-project.github.io/docs/local-dev/

The python parts of iodide are meant to be run using docker-compose locally. Other configurations (e.g. trying to use the local python environment) explicitly are not supported. Going to close this for now, reopen if I'm missing something.
