### ISSUE TITLE
proposal: package versions and git revisions

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/iodide#1801]
It would be useful to know the git revision for packages used to build iodide, e.g. iodide's git revision and pyodide git revision (to know when to test some fixes at https://definitely-staging.iodide.io ). Maybe a "Help" ui page, or some variable available from JavaScript.

e.g. in NumPy it's implemented in `numpy.__config__.show()`

**Comment by bcolloran** [comment]
hmm, i think we should be able to read the iodide version at least during build and inject it as a global in webpack. is there a way to do that for pyodide at build time too? @mdboom any ideas?

**Comment by vadimkantorov** [comment]
PyTorch also includes git revision in build - like that one can construct this (iodide / pyodide).__version__ that could list all the versions and git revisions - this is useful for reporting bugs and testing bug fixes

**Comment by bcolloran** [comment]
oh, @wlach and @hamilton i recall that we do have `iodide.VERSION` available in the JS environment, but we're not setting it to anything useful... nor are we updating the package.json, which we should probably add to the version release doc,

**Comment by mdboom** [comment]
For pyodide, we already have:

From Python:  `import pyodide; pyodide.__version__`
From JS: `pyodide.version`

but obviously that's not the git hash, which should probably be added.

**Comment by vadimkantorov** [comment]
For an example, PyTorch just appends the git hash into `__version__` like `1.1.0+dfd787a`

**Comment by bcolloran** [comment]
fixed via https://github.com/iodide-project/iodide/issues/2007

**Comment by vadimkantorov** [comment]
Do I understand correctly that the git revision is now available in the footer? But not in the programmatic way, right?

**Comment by Algentile** [comment]
Hey @vadimkantorov,

As of right now the commit hash for the last git revision is rendered in the footer of the iodide documentation modal. Currently we are using the [Webpack Git Revision Plugin](https://github.com/pirelenito/git-revision-webpack-plugin) to grab the commit hash on build and expose the process environment variables.

**Comment by bcolloran** [comment]
That's right @vadimkantorov it's available in the footer of the main site, and in the "Getting started" tab of the help modal. I thought that satisfied your original request for the info in the help page, do you need it programmatically as well? if so, i'll update the issue name.

**Comment by vadimkantorov** [comment]
You are gith, it satisfies my original request. However, we can easily imagine someone using pyodide as a javascript library. Then being able to request the actual git revision is useful as well.

**Comment by bcolloran** [comment]
sorry, i think i'm not understanding -- you mean you want the *pyodide* git hash in addition to what @mdboom mentioned above?-- https://github.com/iodide-project/iodide/issues/1801#issuecomment-489912036 ... if this is what you need, would you mind filing a new issue in the pyodide repo?

in case you need do you need the *iodide* git hash to be available programmatically via the iodide API, that should be fixed via #2258, available `iodide.COMMIT_HASH` (a one liner thanks to @Algentile's previous work!)
