### ISSUE TITLE
[feature request] Execution indicator spinner in Report Mode

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/iodide#1824]
There is an execution spinner in Explore Mode, but none in Report Mode. When a user opens Report Mode directly, currently there is no indication of whether exeuction has completed or how many cells have completed execution.

**Comment by bcolloran** [comment]
thanks for filing this @vadimkantorov -- we were talking about it just the other day, and i thought we already had an issue to track this, but i can't find one. oops!

related to #1087

**Comment by vadimkantorov** [comment]
this is even more important given that it’s not easy to offload python computations to a background thread and then ping-back updates on the main thread. Currently the python computation in html elements events (e.g. select’s onchanged) happens on the main thread, hangs the browser and there isn’t even a spinner

**Comment by bcolloran** [comment]
oh i found it -- this is a duplicate of #1149
