### ISSUE TITLE
fetch cell error handling bug

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1853]
```
%% fetch
js: js: https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js
```
should fail with a syntax error.

the current error message is not very detailed:
```
ERROR: js
	(load) file "" does not exist
```

https://alpha.iodide.io/notebooks/2026/

this is probably not too difficult to fix. might be a good first issue.

**Comment by imranariffin** [comment]
@wlach I think I can pick up this one.

**Comment by imranariffin** [comment]
> > @wlach I think I can pick up this one.
> 
> Excellent! I've assigned it to you.

Thanks!
