### ISSUE TITLE
notebook reducer still impure

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1857]
we didn't actually quite fix this completely a few weeks back (see #995 and #1783 ), because this reducer case is impure:

```
    case "NOTEBOOK_SAVED": {
      return Object.assign({}, state, {
        lastSaved: new Date().toISOString(),
        notebookInfo: Object.assign({}, state.notebookInfo, {
          user_can_save: true,
          revision_id: action.newRevisionId,
          revision_is_latest: true
        })
      });
    }
```

the `new Date().toISOString()` should be handled in an action creator (which we don't actually have for "NOTEBOOK_SAVED")

**Comment by bcolloran** [comment]
but also note fwiw: the string "lastSaved" only shows up in this reducer case and in the state schema, so we can actually just delete it altogether -- it's never actually _used_ anywhere (but plz double check me when you go to fix this)

**Comment by wlach** [comment]
We took this code out in #1812! Woohoo
