### ISSUE TITLE
Iodide vs jupyter

### ISSUE THREAD

**Issue by j209** [iodide-project/iodide#1864]
Hi
what is different between iodide and [Jupyter Notebook](https://github.com/jupyter/notebook)?

**Comment by bcolloran** [comment]
Take a look at https://hacks.mozilla.org/2019/03/iodide-an-experimental-tool-for-scientific-communicatiodide-for-scientific-communication-exploration-on-the-web/ ,
as well as our readme. I will leave learning about Jupyter to you. A google search will turn up a lot of information to help you get started.
