### ISSUE TITLE
Proposal: Custom Cell Parameters for Language Plugins

### ISSUE THREAD

**Issue by mehmetoguzderin** [iodide-project/iodide#1867]
# iodide-project/iodide
# Custom Cell Parameters for Language Plugins
## Objective
This document defines custom cell parameters that Iodide system can pipe to language plugins for evaluation. The initial version of this document does not define the API of custom cell parameters nor provides proper references to the points made in various sections.
## Motivation
Iodide makes it possible for computational notebooks to reach a wider user base by providing offline execution, easy language addition with language plugins and capability to run in web browsers. This feature tries to eliminate the possible redundancy that can occur in rich utilization of Iodide system. This redundancy could be creating multiple notebooks to provide alternative views of the same content, and it could be creating multiple language plugins of the same language to provide support for full utilization of language. This resolution can make it easier to use Iodide as an exploratory computational environment and as a means of writing proper text content for a wide range of readers.
## User Benefit
The main benefit of this feature is that it brings feature parity with other execution environments while staying within Iodide philosophy, usage is human-readable and would work with versioning systems like git. It is possible to break how this feature brings feature parity to two parts, the first one is existing language hyperparameters, and the second one is new cell hyperparameters. Many languages widely use existing language hyperparameters like compiler version, output formatting, and feature sets and those are adopted by their users, thus having it would make it easier to adopt Iodide for the existing community of these languages and would make it more feasible to use in teaching environments by having one less trade-off. New cell hyperparameters would help mostly with languages that have limited options regarding the control of displayed outputs. Internationalization, grading, and output control are some of the features that would be desired by users before adoption.
## Examples
- Compiler options
    - Compiler version
    - Feature set control
- Output modifiers
    - Directing output of a set of functions from console to notebook display
- Grading systems
    - Specifying remote endpoint for grading
- Internationalization
    - Disable execution of cell depending on the user's language choice, making it possible to have multilingual language literals in languages that do not support it
### Flag Parameters
- Flag parameters are on if they are found on the cell and off otherwise.
- They already exist in the system, but language plugins can not process them.
- They can not contain `=` reserved for valued parameters.
#### Usage
`%language flag0 flag1 ...`
##### Example
`%md nohtml`
- When implemented in the Markdown language plugin, this would disable HTML in the cell from getting displayed.
### Valued Parameters
- Valued parameters can take any string as value.
- They do not exist in the system but also could benefit the system.
#### Usage
`%language parameter0=value0 parameter1=value1 ...`
##### Example 
`%md language=locale localDateFormat=false`
- When implemented in the Markdown language plugin, this would display the cell only if the language is the user's preferred language but ignores local date formatting.
## Questions and Discussion Topics
- Should cell parameters be evaluated first by system or language plugins?
- Should language plugins be able to disable system parameters of cells?
- Should language plugins be able to add system parameters to cells?
- Should all valued parameters accept an empty string as default parameter unless overridden?
- Should valued parameters without value be processed as flag parameters?
- Should collection inputs to valued parameters be standardized to be processed when recognized or should Iodide system supply language plugins with utility functions?
## References

**Comment by wlach** [comment]
@mehmetoguzderin this looks interesting, were there any concrete scenarios or use cases which motivated this proposal? I think that would help with evaluation / understanding.

**Comment by bcolloran** [comment]
good thinking @mehmetoguzderin -- in fact, we were thinking of this also just a couple weeks ago, so we're on the same wavelength :-) 

Please take a look at https://github.com/iodide-project/iodide/issues/1840 

i think this issue is close enough to that one that i'm going to close this and mark it as a duplicate so that we can keep the discussion in a single thread, but you have a number of new ideas here, so I encourage you to read through that other issue and migrate over any ideas that you think are missing from that conversation.

thank you @mehmetoguzderin !
