### ISSUE TITLE
add a cell type label to each cell

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#187]
We have no labels for the kind of cell we're dealing with, given that all cells use the same general editor. Perhaps we can put a small bit of text under the editor (or above it) to declare what we're working with.

**Comment by hereisnaman** [comment]
@hamilton can we make the cell type label a dropdown on click, from where we can change the type? I am interested on work on this.

**Comment by bcolloran** [comment]
closing in favor of #245
