### ISSUE TITLE
we should probably be using `process.env` in webpack rather than globals

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#1899]
we can really be using env variables directly rather than processing them `webpack.DefinePlugin` and then treating them as global, b/c IIUC `process` is already available globally  via webpack. This would just simplify our webpack setup somewhat -- cut down some mental overhead and bring us in line with the common practice.

this should be a very simple issue to fix -- just a tasky thing where someone has to go in and change all the files that use one of those globals. easy first issue.

see https://webpack.js.org/plugins/environment-plugin/

**Comment by Algentile** [comment]
Hello bcolloran,

I will pick up this issue.

**Comment by bcolloran** [comment]
this is mostly fixed in #1948, but there are a couple more things to be done that @wlach wants to wait to wrap up while addressing #1943

**Comment by bcolloran** [comment]
fixed at some point after #1943
