### ISSUE TITLE
Where should the computation layer live?

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#190]
At the moment, we run all the code in javascript cells directly in the main thread. This has a number of great advantages:

- it's easy to implement.
- we don't have to do any fancy maneuvers for DOM manipulation. All the code execution is very native.
- it's done and it mostly works in a way that lets us do the work right now 

It also has some drawbacks:

- heavy computations, simulations, etc. will lock the entire app.
- we have no way of resetting the scientific computing namespace back to normal, or re-starting the kernel like you can in jupyter.

This discussion thread will be the grounds for any advocacy for changing this piece of the app.

**Comment by bcolloran** [comment]
iframe-2 has a solution for now, and we have additional ideas that seem workable. closing
