### ISSUE TITLE
Revision browser, file downloads broken when read-access is restricted

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1965]
With @jezdez's PR #1926 landed and various fixes, read access to some previously open endpoints is now locked down on Mozilla's internal instance -- in particular file fetches (for resources uploaded to the iodide server) and the revision browser no longer work.

One of those "obvious in retrospect" things. I have a PR to fix the revision browser pending, but how to handle files (which may be referenced via a fetch cell) requires some more thought.

/cc @robotblake @hamilton

**Comment by wlach** [comment]
Revision browser is being worked on in #1966. 

@jezdez, if you wanted to try working on the file endpoints that would be cool. It might be a little tricky: we normally download files via a fetch cell (example: https://alpha.iodide.io/notebooks/759/), so we'd need to find a way to automatically add the iodide credentials for resources fetched on the current domain. We may also need to update the iodide file api (https://iodide-project.github.io/docs/api/), though hopefully that will be a little easier.

**Comment by wlach** [comment]
So it turns out we were already passing file requests (relative ones at least) through to the main editor cell, with authentication credentials:

https://github.com/iodide-project/iodide/blob/c08375515cfe7d48259498c66f53bcaf63a0c9b4/src/eval-frame/actions/fetch-cell-eval-actions.js#L75

Verified that this (along with iodide.file.load) works fine on the internal server here:

https://stage.iodide.nonprod.dataops.mozgcp.net/notebooks/74/

I think we can close this out as done.

**Comment by jezdez** [comment]
Yay @wlach!
