### ISSUE TITLE
Allow iodide server to download files on user's behalf

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#1976]
as a user, I would like to be able to store my secret keys for use in some web api calls. currently, the api key is exposed in the Iodide notebook. this would be useful internally for accessing Bugzilla to retrieve private bugs. Something similar to how Glitch stores private keys would be nice.

**Comment by teonbrooks** [comment]
cc: @wlach

**Comment by wlach** [comment]
@hamilton and I just did a brainstorm on this. We think the right solution is to allow the server to access urls and download files on the user's behalf. This involves a few things:

1. Add a model called "File Source" which specifies a source url for the file, along with an update frequency (once a day, once week, never, ...).
2. A celery component to schedule/execute tasks to update files based on the schedule/urls defined in "File Source". For book-keeping purposes, we would want to keep a model called "file operation" which tracks whether a query is "pending", "in progress", or "completed".

With this infrastructure in place along with some API endpoints, we should be able to define a nice client side interface. @hamilton will define that.

This model (with a few extensions) is probably extendable to the idea of creating/executing queries via redash. /cc @rafrombrc

**Comment by hamilton** [comment]
The terminology is still a bit loose, but here is the rough frontend spec as we see it. This will live as a separate tab under the "manage files" modal (for now). The idea is to give users an interface to create new file sources by (1) putting in the url that they want to query from (eg a "secret url" with an api key, etc.), (2) giving the resulting file name, (3) picking the update frequency (4) provide a "run now" button, an (5) give a "remove this operation" option as well. The point of this feature is to download and cache a file, so the result of a new file source will (when the file operation is run) be a new file.

The data for these operations will live in the Redux store similar to file – an array of objects with the requisite information in the current `notebook_info` section. The actions for these will be somewhat similar to the file API (for the most part), but will focus only on (1) creating new file sources, (2) deleting file sources, and (3) manually kick-starting a new file operation.

This modal view will be hidden if the viewer does not own the notebook. We will enforce this on the django side (don't ship the file source info, period) as well as in the component.

![IMG_6265](https://user-images.githubusercontent.com/95735/60298693-e34b4280-98df-11e9-83b0-3a931554c976.JPG)

**Comment by hamilton** [comment]
@wlach for reference, here is the data model we sketched out:

![IMG_6266](https://user-images.githubusercontent.com/95735/60299452-9a948900-98e1-11e9-8f35-abbf609006ef.JPG)

**Comment by teonbrooks** [comment]
cool, I like this idea

**Comment by bcolloran** [comment]
+1 this is great!

**Comment by bcolloran** [comment]
@teonbrooks @wlach @hamilton -- with "file sources" landed, i'm going to close this one. congrats guys! :confetti_ball: 

opened https://github.com/iodide-project/iodide/issues/2276 to track the api key request in particular
