### ISSUE TITLE
Add some unit tests to verify dockerflow endpoints

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#1988]
If the [dockerflow middleware](https://github.com/mozilla-services/python-dockerflow) is enabled, we currently have three endpoints:

/__version__/ (provides some basic version information generated by circleci)
/__heartbeat__/ (provides some health checks)
/__lbheartbeat__/ ( load balancer checks)

We should add some unit tests that verify that these endpoints basically work (i.e. respond with HTTP 200 and have the expected content) when the `DOCKERFLOW_ENABLED` setting is [enabled](https://github.com/iodide-project/iodide/blob/5c3c855668a71ef5e7c8a1c6d055b521f6657602/server/settings.py#L47) (by default it is not).

We currently only use dockerflow for our internal server but we may start using it in heroku as well (__version__, in particular, might be useful)

Instructions on writing unit tests are here:

https://iodide-project.github.io/docs/local-dev/

An example unit test which changes a setting is here:

https://github.com/iodide-project/iodide/blob/5c3c855668a71ef5e7c8a1c6d055b521f6657602/server/tests/test_server_pages.py#L129

You should be able to model the API checks after existing unit tests, like this:

https://github.com/iodide-project/iodide/blob/master/server/tests/test_notebook_api.py

Name the new file `test_dockerflow.py`

**Comment by Samrose-Ahmed** [comment]
I'd like to take this.
