### ISSUE TITLE
Include git revision (or tag if available?) in footer

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2007]
Forked from iodide-project/iodide#1801

I think we should include some version information in the footer on the main iodide pages to make it more clear what version is being used. Something like this:

![image](https://user-images.githubusercontent.com/20569/60990269-06311a00-a316-11e9-8350-750df7d6dc4a.png)

Where the "revision f54e434c02" link would be to something like: https://github.com/iodide-project/iodide/tree/f54e434c02cb42dfb61ab0e020be940e639fefda

This would help people understand what version of the iodide server they're looking at / reporting bugs against. The exact formatting / display is obviously up for debate / discussion.

@Algentile would you be interested in this? It's in the same vein as the issue you previously fixed. This plugin might be useful: https://www.npmjs.com/package/git-revision-webpack-plugin

**Comment by Algentile** [comment]
Hey @wlach,

I can take this on. Would you just want the hash of the last commit or also display a link to the last issue that was merged?

**Comment by wlach** [comment]
@Algentile a shortened version of the hash, as shown above, should be enough. People can always look through the commit log if they want more detail.
