### ISSUE TITLE
[META] tutorial notebooks vol. 1

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#201]
We need a set of decent tutorial notebooks before this repository turns public. One thing that many closed-source computing platforms get right is the documentation, tutorials, and examples are almost always enough to jump in and hit the ground running. Max/MSP, in particular, does a great job of of keeping almost all the documentation in the form of patches, which is the main Max/MSP paradigm.

Her are a list of useful tutorials (add more as we talk about it):

- how to perform basic DOM manipulations. This should drive home that we are ON the DOM. Should start with a bit of motivation, and then end in a small d3 example, and / or a webgl example. (#200)

**Comment by bcolloran** [comment]
Issue moved to [iodide-project/iodide-examples #2](https://github.com/iodide-project/iodide-examples/issues/2) via [**ZenHub**](https://www.zenhub.com/)
