### ISSUE TITLE
build tune-ups (webpack not shaking tree correctly / not reading NODE_ENV options correctly)

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#2023]
we should set our "build" mode to be a "production" mode (which will have minification and tree shaking and will prevent some debug messages from being surfaced in the devtools console), and deprecate the "build-prduction" mode, which we don't seem to be using anywhere.

thanks @dmose for noticing this.

cc @wlach

**Comment by bcolloran** [comment]
also, this may need to include removing ".dev" from a bunch of our filenames

**Comment by wlach** [comment]
💯 

I'd prefer to wait on this until #1943 is fixed, but would be a good issue for a contributor to pick up when that's done

**Comment by bcolloran** [comment]
now that #1943 is fixed, this is ready for work. as will says, this could be a good first issue for a contributor.

**Comment by wlach** [comment]
I'm going to take this one
