### ISSUE TITLE
Revision browser should allow reverting notebook to previous state

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2047]
Currently the revision browser lets you view a summary of what changed, but doesn't let you actually revert the notebook content to that of a previous revision.

![image](https://user-images.githubusercontent.com/20569/61397697-76044f00-a898-11e9-9ffc-bfe51dd716e1.png)

We should, at minimum, add a button to do exactly like this. Before actually replacing the content, it should pop up a warning dialog confirming the user wants to do this. Google docs provides a good UI example on how this is done:

![image](https://user-images.githubusercontent.com/20569/61397808-b1068280-a898-11e9-80c5-02ee4ca0fdff.png)

Depending on where we go with iodide, we probably want to enable other things in the future  (e.g. forking a "branch" from a previous revision) but for now this will move the ball forward a bit.

**Comment by ZiyaoWei** [comment]
Interested in contributing to Iodide - is this issue a good first issue to pickup? If not, I'll browse around and try to find something else (open to suggestions!).

**Comment by wlach** [comment]
> Interested in contributing to Iodide - is this issue a good first issue to pickup? If not, I'll browse around and try to find something else (open to suggestions!).

I think @mehmetoguzderin wanted to pick this one up, #2114 which you filed would be a good first issue to try. I can probably suggest other things on gitter when I get back in on Tuesday.

**Comment by bcolloran** [comment]
this functionality was added somewhere along the way...
