### ISSUE TITLE
saving unnamed notebooks, saving blank notebooks

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#208]
I have years of PTSD from having various things open and then a program crashes and I didn't save it and now I don't have it. Generally speaking, things have gotten better on this front for most programs. But this means, for folks like me, I habitually try to cmd+s without thinking about it.

We should have some way of dealing with trying to:
- saving unnamed notebooks. Should we have a way of encouraging naming the thing, like in other programs?
- saving blank, unnamed notebooks. Perhaps the former case is all we need. If that is not acceptable, we should have a way of dealing with this, even if the way to deal with it is "don't save a blank & unnamed notebook".

**Comment by hereisnaman** [comment]
@hamilton I would like to work on this issue. We can show a prompt for saving a blank unnamed notebook and give a name las @bcolloran said.

**Comment by hamilton** [comment]
Given the direction we are going, this is `wontfix` for `localStorage` until we have server / github gist integration.
