### ISSUE TITLE
move examples to an overlay

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#209]
Removing from the menu and using an overlay for notebook maintenance will reduce the menu size. It will also give us room to expand our current default docs and tutorials.

**Comment by djbarnwal** [comment]
Hey @hamilton  I would like to work on this issue. To be clear the end result should be to remove the dropdown menu and replace it with an off canvas overlay menu, right? That would look cleaner I guess.

**Comment by hamilton** [comment]
I think this will likely require more discussion, so I would hold off for
now since it is not a priority

**Comment by hamilton** [comment]
We are going to probably just send users to a web page w/ a directory of example notebooks.
