### ISSUE TITLE
console should update active language when going through scrollback to match language of evaled code

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#2104]
related to #2103 -- it seems like when you scroll back through the console with up/down, that the active language in the console should update to match the language/chunk type that was used in the original eval.

**Comment by bcolloran** [comment]
i'm not sure, but i think this should not be too difficult. it would be good to try https://github.com/iodide-project/iodide/issues/2103 first, which is in the same part of the code, but probably a bit easier

**Comment by Hrtkk** [comment]
Hii, @bcolloran I have sent the pull request. please review it.

**Comment by bcolloran** [comment]
fixed via #2508
