### ISSUE TITLE
Exploring the "big data" question in our context - plugins?

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#211]
The obvious question we get during presentations is "well, what about big data?"

We are emphatically not trying to provide a solution to the kind of big data needs of industry and academia. It's simply out of scope. There are, however, some possible lightweight extensions that our notebook could provide that would empower others to write connectors to the kinds of services others are used to. This is a concept that @wlach brought up in Austin, and was later reiterated by other data platform engineers at Mozilla.

Let's use this issue to discuss further.

**Comment by bcolloran** [comment]
obselete-- this will be replaced with more specific issues in the near future (in collab with the data teams)
