### ISSUE TITLE
tabular dataset viewer breaks badly if you feed it a column with raw objects

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#213]
ex:
[{a:1, b:{}, c:"foo"},
{a:2, b:{}, c:"fee"},
{a:3, b:{}, c:"bar"}]
makes the viewer sad.

stop gap solution could involve stringifying things for display, real solution might be replacing the table display component we're using.

**Comment by bcolloran** [comment]
i think stringified objects seem fine for now?
dates should def be date strings.
this feels like a goof first issue, yes?

**Comment by hamilton** [comment]
Would like to escalate this, since I am having trouble dogfooding the notebook w/o this solved.
