### ISSUE TITLE
Changelog URL in PR template not pointing to the right place

### ISSUE THREAD

**Issue by ZiyaoWei** [iodide-project/iodide#2131]
The tiniest nitpick - the `changelog` link in the PR template actually points to https://github.com/iodide-project/iodide/CHANGELOG.md after PRs are submitted, e.g., https://github.com/iodide-project/iodide/pull/2130.

### What I Did

N/A

### What I Expected

The link should point at https://github.com/iodide-project/iodide/blob/master/CHANGELOG.md

### What Happened 

https://github.com/iodide-project/iodide/CHANGELOG.md which 404s

**Comment by wlach** [comment]
Thanks! For future reference, it is possible to submit PRs against these sorts of templates (see commit) -- feel free to do so in the future, no issue required. :)
