### ISSUE TITLE
Our docker images should be built using a multi-stage builds

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2156]
@armenzg just taught me about [multistage docker builds](https://docs.docker.com/develop/develop-images/multistage-build/), I think we use these for generating the iodide docker images. Advantages:

* Much smaller images we can use deployment (should speed up deploys internally, and on Heroku whenever we start using docker images there)
* Can much more easily create a "production" image without dev and test dependencies (should probably do that as part of this work)

The version of docker used to generate the images must be relatively recent (17.05 or higher), but I believe the resulting images can be used just about anywhere.

Here's an example file, much of what's in here would apply to iodide as well: https://github.com/mozilla/bedrock/blob/master/Dockerfile

This isn't a "good first bug" in the sense that some of the exact details of the work required are undefined but should be relatively approachable to someone newish to iodide. I would recommend reading the section on https://iodide-project.github.io/docs/local-dev/ before diving in.

**Comment by Algentile** [comment]
Hey @wlach, 

I was looking into this earlier last week, I can start working on this.

**Comment by wlach** [comment]
@Algentile fantastic! I will assign to you
