### ISSUE TITLE
Embed report in Google Site?

### ISSUE THREAD

**Issue by Jsalaz1989** [iodide-project/iodide#2174]
Not really a bug, more of a feature request I suppose, sorry if this is not the place for it. I'm hoping to embed an interactive report, with the Pyodide scripts already evaluated, into a google site. I think the Iodide version is 94f4a59ccf of the alpha release. 

### What I Did

In the new Google Sites, I tried embedding a link to the report but I get 'Can’t embed due to provider site permissions. URL will display as a text link.' 

I then was able to insert it into an 

`<iframe width="100%" height="100%" src="https://alpha.iodide.io/notebooks/2945/?viewMode=report" frameborder="0" allowfullscreen is="x-frame-bypass"></iframe>`

but I needed the `is="x-frame-bypass"` to work around the error 

`Refused to display 'https://alpha.iodide.io/notebooks/2945/?viewMode=report' in a frame because it set 'X-Frame-Options' to 'sameorigin'`.
 
The x-frame web component is from [here](https://github.com/niutech/x-frame-bypass). 

However, it does not embed the report view, but rather the regular, exploratory view. It also logs errors of the types:

`Access to fetch at 'https://cors.io/?https://alpha.iodide.io/notebooks/2945/?viewMode=report' from origin 'https://1999851158-atari-embeds.googleusercontent.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`x-frame-bypass.js:72 GET https://cors.io/?https://alpha.iodide.io/notebooks/2945/?viewMode=report net::ERR_FAILED
fetchProxy @ x-frame-bypass.js:72
load @ x-frame-bypass.js:42
connectedCallback @ x-frame-bypass.js:6
(anonymous) @ x-frame-bypass.js:1`

`x-frame-bypass.js:72 GET https://jsonp.afeld.me/?url=https://alpha.iodide.io/notebooks/2945/?viewMode=report 525`

But I imagine those are issues related to the x-frame component and not Iodide. In any case, I can at least get the notebook to show up in its exploratory view. However, it doesn't let me run any cells and will, for example, remain stuck at 'Loading Python language plugin'.

### What I Expected

An interactive, fully evaluated report embedded in a Google Site. I understand that opening with `viewMode=report` typically provides this.
 
### (if applicable) notebook that reproduces bug 

https://alpha.iodide.io/notebooks/2945/

**Comment by wlach** [comment]
Hmm, I believe we set the x frame options parameter to prevent clickjacking attacks:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

We used to have an option to export a notebook as a report you could put anywhere -- I think that would cover your use case.

**Comment by Jsalaz1989** [comment]
>We used to have an option to export a notebook as a report you could put anywhere

Right, that's what I originally thought would be the case but I wasn't able to find a way to export the full, evaluated notebook. Am I not seeing that feature some where or has it been taken out?

**Comment by wlach** [comment]
> > We used to have an option to export a notebook as a report you could put anywhere
> 
> Right, that's what I originally thought would be the case, and that it would be fairly straight forward, but I wasn't able to find a way to export the full, evaluated notebook. Am I not seeing that feature somewhere or has it been taken out?

It has been taken out but I just filed an issue to resurrect the feature: #2178

**Comment by wlach** [comment]
I'm going to close this bug because I don't think we'll ever allow this for security reasons. The above issue should hopefully satisfy the use case when implemented.
