### ISSUE TITLE
No evaluator available for chunks of type

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#2215]
Hi, this demo doesn't work anymore https://alpha.iodide.io/notebooks/1627/

```
%% plugin

{
  "languageId": "ml",
  "displayName": "OCaml",
  "codeMirrorMode": "mllike",
  "url": "https://louisabraham.github.io/domical/eval.js",
  "module": "evaluator",
  "evaluator": "execute",
  "pluginType": "language"
}

%% ml
open Printf
let my_data = [ "a"; "beautiful"; "day" ]
let () = List.iter (fun s -> printf "%s\n" s) my_data
```

The output is the following:

![image](https://user-images.githubusercontent.com/13174805/64258062-d160ce00-cf26-11e9-85f8-875934fd17fa.png)

**Comment by wlach** [comment]
Weirdly, after taking out the `codeMirrorMode` key out from the language plugin directive, everything seems to work:

https://alpha.iodide.io/notebooks/3183/

We no longer use codemirror in iodide so it's no longer necessary, but I don't see why it should be causing the language plugin not to work.

**Comment by bcolloran** [comment]
oh i bet it's probably failing at state schema validation. it's probably an easy fix to have it not fail if there are extra keys (and/or to give better feedback in case the plugin info is not valid for some reason).

(note that adding Monaco syntax highlighting for additional languages is not working at present)

**Comment by mdboom** [comment]
Yeah -- this seems like a good place to *not* be strict about extra keys.
