### ISSUE TITLE
List of pathlib.Path objects fails to render into JavaScript

### ISSUE THREAD

**Issue by agilevic** [iodide-project/iodide#2237]
Encountered online at alpha.iodide.io

### What I Did

This works works as expected.
```
%%py
from pathlib import Path
p = Path('/')
l = [str(pe) for pe in p.glob('*')]
l
```
So does this
```
%%py
Path('/')
```

But the following fails. The Pyodide console reports an array of 5 elements but when expanded, returns this error: 

A value renderer encountered an error.
TypeError: Cannot read property 'childItems' of null

```
%%py
from pathlib import Path
p = Path('/')
l = list(p.glob('*'))
l
```
### What I Expected

List of PosixPath objects (their __repr__() specifically).

### What Happened 

explanation, imgs. etc.

### (if applicable) notebook that reproduces bug 

link to the notebook that reproduces the bug. the smaller the better. you may wish to use https://definitely-staging.iodide.io/ (our staging environment, deploys from master) for creating/sharing the notebook.

**Comment by bcolloran** [comment]
this is probably the same underlying issue as https://github.com/iodide-project/iodide/issues/2254

**Comment by bcolloran** [comment]
superseded by #2254
