### ISSUE TITLE
migrate diff viewer to use monaco's diff viewer

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#2275]
monaco editor comes with the diff viewer used by vscode. this is obviously very actively maintained and quite polished, and migrating would also remove a dependency which is always nice. we should migrate to it when we can.

**Comment by bcolloran** [comment]
little more on this: i'm not sure how involved this will be; it might be trick or it might be pretty easy. we'd need to create a custom component to instantiate the monaco diff viewer, along the lines of the [editor component](https://github.com/iodide-project/iodide/blob/master/src/editor/components/iomd-editor/iomd-editor.jsx) but i think waaaay simpler since the state updating would not need to be so sophisticated -- i think we could write it as it's own component that could just take the same props as `ReactDiffViewer` and have it be a drop-in replacement, but i'm not 100% sure.

**Comment by wlach** [comment]
FWIW, our usage of react-diff-viewer is very very simple (as is the component):

https://github.com/iodide-project/iodide/blob/dbfa9999eb48f989288830d3e399520cc743983b/src/editor/components/modals/revision-diff.jsx#L67
