### ISSUE TITLE
Uploaded files show as having "failed to upload" even though the operation was succesful

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2287]
### What I Did

On https://definitely-staging.iodide.io do the following:
* login
* create a notebook
* open up manage files
* upload a random local file

### What I Expected

File uploads, shows up in file dialog

### What Happened 

It says "file failed to upload". Refreshing the notebook and looking at file sources shows that the upload did succeed. This is a regression from the last release: this functionality works fine on alpha.iodide.io. 

Most likely this broke when we added file sources /cc @hamilton

**Comment by wlach** [comment]
Taking this

**Comment by bcolloran** [comment]
thanks @wlach! :+1:
