### ISSUE TITLE
`ReadTimeoutError` with Local Development using WSL 2

### ISSUE THREAD

**Issue by mehmetoguzderin** [iodide-project/iodide#2297]
# Environment
Operating System
Edition: Windows 10 Pro
Version: 1903
OS Build: 18990.1
Insider: Fast Cycle
Windows Subsystem for Linux 2
OS: Ubuntu
Version: 1804.2019.521.0
# Problem
When `make build` is run in the given environment, build keeps producing `ReadTimeoutError` error.
Sometimes it succeeds.
# Error (example, can happen on any module)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/bf/5a/44c04abc182990d716eb7703502aa851433ea66569bd72765ef1abdaea9c/Faker-2.0.2-py2.py3-none-any.whl

**Comment by wlach** [comment]
@mehmetoguzderin can you attach a larger log of what's going on, perhaps as a gist?

**Comment by mehmetoguzderin** [comment]
Turns out to be a router issue
