### ISSUE TITLE
Approach of importing circleci vars into docker compose container is ugly

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2333]
To fix #2330 I imported the circle environment into the docker compose environment in #2332. This is pretty ugly, and there's probably a better approach here. Maybe we can just copy the codecov report out of docker compose and upload it from the circle environment? @jezdez wdyt?

**Comment by Algentile** [comment]
It appears that there is now a codecov orb that seems to be easily integrated with circle ci [https://circleci.com/blog/get-started-with-google-binary-authorization/](https://circleci.com/blog/get-started-with-google-binary-authorization/). Although it appears to use orbs we would need to migrate to circle CI 2.1 if we wanted to use this option.

**Comment by wlach** [comment]
Interesting! I would be open to using that if it solves our problems, I haven't yet had a chance to look into CircleCI orbs.

**Comment by jezdez** [comment]
@wlach Yeah, I like just copying the coverage.xml to the CI machine, much saner than the weird environment passing. I'll send a PR.

**Comment by wlach** [comment]
This is resolved with #2374
