### ISSUE TITLE
what kind of app-level usage data should we collect, if any?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#235]
at some point we need to think about what kind of app usage data we'll need, and how to collect it (google analytics, etc)

**Comment by hamilton** [comment]
I would argue that this is a `wontfix` for the foreseeable future, pending a real, public conversation. I don't want anyone to get the impression that we are tracking what they're doing in the notebook environment until we are very publicly explicit about what we're doing.

**Comment by bcolloran** [comment]
Yea, 💯 -- I'm in full agreement, I don't think we need or even want to know about the details of what people are doing in the notebook, and in particular, what code people are running or anything like that. what we will probably need is very basic metrics on app usage for things like grant applications to support this work.

We're obviously a long way out from needing this, since no one actually uses the notebook :-) , but I think it's best to have it on record in our issues that we're considering this. I think it's clear that we'll never serve ads for example, and for now this project is supported by Mozilla, but there may come a time when we need other funding streams, in which case the best option for a project like this may be grants. If that comes to pass, we'll need some small amount of data to show orgs the value of the project.
