### ISSUE TITLE
double check table styling (might have lost some styles from the bootstrap reset?)

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#240]
(minor nit; this is not a 0.3a blocker, we have higher priorities to worry about)

it looks like there is now a bit of spacing between table cells for the matrix-like outputs:

![image](https://user-images.githubusercontent.com/2380975/35647114-60bd53cc-0686-11e8-9c44-617a898aa819.png)

**Comment by djbarnwal** [comment]
Adding a property of `border-spacing: 0` to the `table` selector seems to solve the issue on my local system. Will send a PR.

**Comment by hamilton** [comment]
Believe the PR that addressed this was merged - closing now / thanks @djbarnwal!
