### ISSUE TITLE
When truncating numbers in scientific notation, don't truncate the exponent!

### ISSUE THREAD

**Issue by felixlawrence** [iodide-project/iodide#2439]
[Minimal example](https://definitely-staging.iodide.io/notebooks/220/)

The exponent was truncated from 8.3e-308, so that the number read as 8.3. I had to expand the result view to see that the number was closer to 0 than 8.

### What I Did

```
%% py

[
    8.321007997501958e-308,
    0.6852718992213929
]
```

### What I Expected

```Array(2)[8.3210079975e-308, 0.6852718992213929]```

### What Happened 

```Array(2)[8.3210079975, 0.6852718992213929]```

(i.e. it looks like the first number is closer to 8 than 0)

### (if applicable) notebook that reproduces bug 

https://iodide.telemetry.mozilla.org/notebooks/339/

**Comment by wlach** [comment]
@nikijiandani is interested in taking this on

**Comment by nikijiandani** [comment]
Working on this right now.
