### ISSUE TITLE
Get an error when completely erasing default notebook content

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2445]
How to reproduce:

1. Create a new notebook
2. Erase all content
3. Switch tabs or wait a while

Result:

Get this error:

![image](https://user-images.githubusercontent.com/20569/69070902-0396ad80-09f7-11ea-8159-5b75805f84a9.png)

It appears that the `/api/notebooks/<notebook>/revisions/` endpoint does not accept an empty string, but it really should. Code which should be changed probably around here: https://github.com/iodide-project/iodide/blob/master/server/notebooks/api_views.py

**Comment by imranariffin** [comment]
Thanks for creating the issue @wlach, I'd like to work on this.

Can you assign this issue to me?

**Comment by wlach** [comment]
> Thanks for creating the issue @wlach, I'd like to work on this.
> 
> Can you assign this issue to me?

Sorry for the delay, done now

**Comment by imranariffin** [comment]
> > Thanks for creating the issue @wlach, I'd like to work on this.
> > Can you assign this issue to me?
> 
> Sorry for the delay, done now

No worries, thank you!
