### ISSUE TITLE
Cell type not immediately obvious in UI

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#245]
In my first "real" attempt at using an Iodide notebook, I was a bit thrown off by the fact that the cell type parameter is completely hidden in the user interface and that you have to dig through a menu to set a cell type. I think it would be nice to label each cell with its type, perhaps in small text with a dropdown to easily change its type inline. Maybe something like this (gratuitously cribbed most of the style from github):

![image](https://user-images.githubusercontent.com/20569/35707134-977dab32-0776-11e8-8842-32e8f01b1485.png)

**Comment by djbarnwal** [comment]
@wlach I would like to work on this feature. Is this issue up for others to try or the discussions regarding this is still going on?

**Comment by wlach** [comment]
@djbarnwal I don't think we know exactly how we want it to look, but i see no reason not to try building a first draft of the feature that looks like my mock up and then iterating from there.

**Comment by bcolloran** [comment]
@djbarnwal -- might actually be best to wait for a bit more discussion on this one; we've been thinking about the need for per-cell menus to handle a few issues that are coming up, and we've been thinking about how the need to visually indicate the cell type might fit in with that.

**Comment by bcolloran** [comment]
teon hit this issue -- our UI is much too confusing here. We need an MVF of this, even if it's not pretty (ugly will be an improvement over nothing)

(note: the MVF could be as simple as a string in the top left corner of cell-container )

**Comment by bcolloran** [comment]
fixed with #530
