### ISSUE TITLE
reconfigure neutrino dev server to return 404s for pages / urls that do not exist that are local

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#247]
I discovered this through trying to figure out why the `ExternalDependencyCell` seemed to let pass sources that were just random characters when they used to fail.

Turns out `http://localhost:5000/sdoifnsdofidnfosdifnd` returns the notebook, which mostly makes sense, except it doesn't reflect the actual "production" environment of being able to load (or not load) resources in the appropriate directory.

As a quick fix to this, could we have anything that is `http://localhost:5000/*` return a 404?

**Comment by bcolloran** [comment]
closing for now since we're not using neutrino ATM
