### ISSUE TITLE
Revision coalescing sometimes results in two adjacent revisions with no changes

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2517]
#2461 added automatic revision coalescing of "draft" revisions, but there's one edge case where not taken into account:

Imagine a notebook with these three revisions:

```
A (non-draft) = aaa
B (draft) = aab
C (draft) = aaa
```

This code will delete B but keep C, which is no different than A. In this case we should just delete both B and C, since the notebook hasn't really changed.

**Comment by wlach** [comment]
Continuing discussion with @zzl0 from https://github.com/iodide-project/iodide/pull/2461#issuecomment-561930576:

> That's a nice finding (How did you find this issue?). 

It just happened when testing a notebook on stage. 😄 

> Yeah, I didn't think about this case. This is an interesting problem. I don't have a solution off the top of head.
> 
>     * I am not sure if we should delete both B and C, or just delete C and keep B.

I think the right solution is probably to delete both B and C, as I think the usual reason it happens is the user made an accidental change when opening a notebook.
 
>     * Seems we also need to get the newest non-draft revision in the auto prune task.

Yup, I think that's what needs to happen.

**Comment by zzl0** [comment]
I am working on this
