### ISSUE TITLE
Document title should match notebook title

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#253]
The title of the document is always "Iodide Notebook" no matter what the notebook name is. Instead, we should set the title to be whatever that of the notebook is.

I recommend the react helmet library for this task. You can see an example of adding it to a repository here:

taskcluster/taskcluster-tools#188

**Comment by djbarnwal** [comment]
Hey @wlach can I work on this issue and send a PR?

**Comment by pradeepgangwar** [comment]
@wlach I think we can close this as PR has been merged.

**Comment by bcolloran** [comment]
Perfect, thanks for noticing that @pradeepgangwar, and thanks for the PR @djbarnwal :-)
