### ISSUE TITLE
Should be able to browse a read-only copy of files + file sources even when you don't own a notebook

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2562]
Currently we hide the option to open the files dialog if the user does not own a notebook (or is not logged in). However, it would sometimes be useful to be able to browse the files + file sources (the latter minus their URLs) of a notebook even in this state.

![image](https://user-images.githubusercontent.com/20569/71005390-98053600-20b1-11ea-9b10-c1067c806dfb.png)

I'd propose that when a user does not own a notebook (or is not logged in), we continue to make the above accessible, hiding the "add files" / "delete" options and replacing with a message saying something like "You must be the owner of a notebook to add or remove files".

For the file sources dialog, we can do something similar -- remove all the options to add / manipulate stuff, and hide the metadata pertaining to the actual URL source (which only the owner of a notebook knows):

![image](https://user-images.githubusercontent.com/20569/71005597-e4e90c80-20b1-11ea-8cd4-63777343f6e1.png)

Finally, I would propose we change "Manage Files" to just "Files" in all places (I think the manage part is pretty much implied for owners of a notebook).

The source to the files modals are currently in `src/editor/components/modals`. The current logic to hide the modal is in `src/editor/components/menu/editor-toolbar-menu.jsx`

**Comment by ThobyV** [comment]
May I work on this please?

**Comment by wlach** [comment]
> May I work on this please?

You may, but please only commit to working on one issue at a time at first. :) We want to keep some issues open for other contributors.

**Comment by wlach** [comment]
I'm actually looking into this.
