### ISSUE TITLE
Add a simplified way of creating notebooks with no authentication credentials

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#2565]
We added the capability for services to create notebook on a user's behalf in #, but it's a little bit of a pain to set up: administrative effort is required to configure both the iodide server and the service creating the notebook to use a special key.

It would be nice if we could just do everything on the client, wouldn't it? I originally thought this was intractable, but have since come up with an approach that I think is secure:

1. Allow notebooks to be owned by *no user* initially and allow anonymous creation of notebooks of this kind
2. Allow notebooks to be addressed by a unique hash of their id (maybe using https://github.com/nshafer/django-hashid-field) in addition to (at first) their numeric id. Anonymous notebooks can only be viewed by using their hash (which is returned when they are created)
3. When an anonymous notebook is viewed by a logged in user, it will automatically be claimed. When it is viewed by an unauthenticated one (only applicable to public sites like alpha.iodide.io), it will show the usual message about needing to be logged in to save your changes.

So in this case, to add an "open in iodide button" to a web app (or a web extension), you would do something like:

1. POST a new notebook owned by no user. Get the content of the notebook back, including the hash id (which should be known only to the person creating the notebook)
2. Open a new tab at (e.g. iodide.telemetry.mozilla.org/notebooks/&lt;hash id&gt;/)

This should be resilient against the following types of attacks:

1. Users won't be able to claim/view notebooks they didn't create (since they won't have the hash)
2. On a server where we require authentication (e.g. iodide.telemetry.mozilla.org), we can allow anonymous creation of notebooks with low risk (creating a notebook doesn't grant access to any other resources)

With this in place, we should be able to easily add "explore this dataset in iodide" buttons to all our telemetry tools, including ones that use static frontends. No auth credential setup required.

/cc @jezdez @openjck @hamilton , I'm curious what you think of this idea. I may give it a shot in the next couple weeks if there aren't any glaring flaws with it.

**Comment by bcolloran** [comment]
do we need to also worry about DOS-type attacks?--

(3) a malicious/buggy actor sends a bunch of POSTs that create a bunch of NBs on an iodide server

-- or is this covered by the existing mechanisms?

in any case, i think this is a great idea, and this potential attack vector is not a showstopper -- i think DOS is low-risk for now, and there are a lot of plausible mitigations. mostly just wondering if our flow already addresses this.

**Comment by wlach** [comment]
> do we need to also worry about DOS-type attacks?--
> 
> (3) a malicious/buggy actor sends a bunch of POSTs that create a bunch of NBs on an iodide server
> 
> -- or is this covered by the existing mechanisms?
> 
> in any case, i think this is a great idea, and that you should go forward with it. this potential attack vector is not at all a showstopper -- i think DOS is low-risk for now, and there are a lot of plausible mitigations. mostly just wondering if our flow already addresses this.

Yeah I considered that. I'm not *too* worried about this, but there's a few things we could do if we want to be a bit cautious:

1. Automatically delete unclaimed new notebooks after some timeout
2. Limit new notebook creation to once every 5 seconds or so using something like django-ratelimit https://django-ratelimit.readthedocs.io/en/stable/rates.html

There's not much of a payoff for these kinds of attacks other than being annoying to us or whoever runs an iodide server.

**Comment by bcolloran** [comment]
yep agreed, not too worried about it.

and those mitigation strategies (which IMO would be optional for a first-pass at this) seem like they'd cover us far into the future

**Comment by wlach** [comment]
Was just using jsfiddle for something unrelated and they do something pretty ingenious. They allow creating a new just by posting a form directive. e.g. try opening one of these maps examples:

https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/map-latlng-literal

I didn't know this but you can just open forms in a new tab and it'll post the form data as the page loads:

https://stackoverflow.com/a/5709607/295132

So I think we can actually skip doing most of this in favor of a new endpoint which accepts the notebook + metadata as a form payload and does one of the following:

1. If logged in, create a new notebook with the payload
2. If *not* logged in, create a trial notebook with the payload

There might be some additional complexities around attaching files if that's something we want to support, but this should work for a first pass.

**Comment by wlach** [comment]
> Was just using jsfiddle for something unrelated and they do something pretty ingenious. They allow creating a new just by posting a form directive. e.g. try opening one of these maps examples:
> ...

Just tested and this doesn't seem to be a magical solution, since the posted form will not have any authentication credentials associated with it (probably a good thing from a security perspective, now that I think of it). Something like this might still be an interesting option from the point of view of letting people try iodide on the public site, but we should think through the user stories and implications carefully.

**Comment by hamilton** [comment]
This is a at a high-level a great idea @wlach. I'd like to explore the different user stories behind this idea and think about the consequence, since I don't have a good read on whether this is the right design to achieve other potential intents (and downsides). I'm a bit skeptical of the original idea of automatic notebook claiming as suggested in the original comment (can't tell if that's still on the table from this thread) without having spent time thinking about the experience. It seems like it'd potentially lead to some adverse issues, such as a not-logged-in user creating an anonymous notebook, sharing it with someone who is logged in, then that logged-in user automatically claiming it without intending to.
