### ISSUE TITLE
Help Icon in Header centering bug

### ISSUE THREAD

**Issue by Samrose-Ahmed** [iodide-project/iodide#2567]
The Help Icon in the header is not centered properly. Also affects play and fast forward icons.
Affects Chrome and Safari based on my testing but not Firefox for some reason.

### What I Did
https://alpha.iodide.io/tryit/

### What I Expected

Icons should be centered.

### What Happened 
![iconss](https://user-images.githubusercontent.com/9027301/71062168-b35a5a80-211e-11ea-8f26-f5dae3d960c8.png)

### (if applicable) notebook that reproduces bug 

https://alpha.iodide.io/tryit/

Seems to be caused by `padding: 12px` in `NotebookTaskButton`.

Adding `padding: "0px"` [here](https://github.com/iodide-project/iodide/blob/69409c8f70731ed83ee18da828e3cb66ca966982/src/editor/components/menu/notebook-task-button.jsx#L27) seems to fix it ![](https://user-images.githubusercontent.com/9027301/71062392-35e31a00-211f-11ea-8310-c394f408c751.png).

**Comment by wlach** [comment]
@Samrose-Ahmed good catch, I'd noticed this myself. Would you care to send a PR?
