### ISSUE TITLE
add docs about setting up an editor to work well with linting etc

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#264]
i have a config for sublime that seems to be working fine; @hamilton has one for VScode; and i believe @mdboom has one for emacs. Perhaps we can add docs to assist new devs with getting up and running quickly.

**Comment by hamilton** [comment]
Adding the VS Code rule here:

1. Install the ESLint extension from the extensions pane.

![screen shot 2018-02-09 at 3 28 32 pm](https://user-images.githubusercontent.com/95735/36054973-1cb46a06-0dae-11e8-877c-ea41f62ac2b3.png)

2. Under Preferences > Settings, add the following rules:
```
{
    "eslint.autoFixOnSave": true,
    "eslint.options": { "configFile": "./.eslintrc.js" }
}
```
3. Restart VSCode

**Comment by bcolloran** [comment]
(this is not really in scope)

**Comment by mdboom** [comment]
Yeah, I think just saying "we use eslint" is enough for people to get Googling for their own editor.
