### ISSUE TITLE
test suite style issues / questions regarding jsx

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#278]
The linter feels very angry at how our tests are written at the moment - we're importing `jsx` into files with only a `js` extension. Should we consider migrating all the tests to `jsx` for the sake of uniformity?

**Comment by bcolloran** [comment]
works for me. (or at least all the tests with jsx, i think not all of them have it)

i'm also open to just using .js exclusively and disabling that lint rule (i think i read that facebook prefers that style). keeping the distinction but just be adding cognitive overhead at this point. but i don't have strong feelings one way or the other
