### ISSUE TITLE
License should be a valid SPDX license expression warning.

### ISSUE THREAD

**Issue by horcrux2301** [iodide-project/iodide#279]
I ran `yarn run dev` and received the following error `License should be a valid SPDX license expression`. 

In `package.json` the license is `Mozilla Public License 2.0` whereas the correct one according to this [link](https://spdx.org/licenses/) should be `MPL-2.0`.

Should I open a PR and fix this?

**Comment by hamilton** [comment]
Yes, feel free

**Comment by hamilton** [comment]
This was closed by #279. Thanks for the PR.
