### ISSUE TITLE
How do I deply iodide server?

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/iodide#2812]
Hello. Sorry for the noob question, but the documentation is either thin or I'm missing something.
The docs say that:

> Iodide is currently designed to be deployable on Heroku out of the box, using Github as an authentication provider.

Okay, so I have heroku installed. How do I setup iodide? I have cloned the project from git, I was able to run make to build it (is this step even necessary?) and now when I execute
`heroku local web`
the server starts yet the webpage at 0.0.0.0:5000 returns Bad Request (400).
When I try to see the logs (via `heroku logs --tail`) the only output is:
`Error: Missing required flag:
-a, --app APP app to run command against
See more help with --help`

What am I doing wrong? How do I set up the iodide server step-by-step?

**Comment by wlach** [comment]
Hi, the local development workflow is to use docker: https://iodide-project.github.io/docs/local-dev/#runningbuilding

Feel free to reopen if something is still unclear.
