### ISSUE TITLE
Add offline working capabilities

### ISSUE THREAD

**Issue by hereisnaman** [iodide-project/iodide#287]
As the node book is public and loads data from the local storage, we can add offline working capabilities to the project so that it can work even when offline. For the upcoming features like export to gdrive, which needs network access, we can show a snackbar when offline.

**Comment by bcolloran** [comment]
hi hereisnaman, can you clarify what you mean? we have one potential plan in mind for a fully offline, fully portable export, but i'm curious if you had something else in mind.

the plan we've been considering would be to wiret the complete contents of the application CSS and javascript inline into the apps HTML within <link css> and <script> tags (tho we haven't experimented with this yet, and I don't know how it will work with fonts in particular). would something like tha satisfy your use case?

also, fwiw, it is possible to work fully offline if
(a) you build a local copy with `npm run start`, in which case the copy built in the `dev/` folder will run fully locally (pointing at local JS and CSS resources); or
(b) as a workaround, if you visit https://iodide-project.github.io/iodide/ and use your browsers "save as complete webpage" (not the notebook save functionality) you will download and save a copy of the HTML file with the JS and CSS uris set to point at the local resources you've downloaded.

and also also fwiw: the usage of localstorage is really intended more for emergency backup than as the primary workflow, but of course we're interested in hearing people's feedback as they use the notebook to do work, so we are open to changing how that is handled.

anyway, please do let us know if any of this covers the use case you have in mind, or if you are in need of something else.

Thank you!!

**Comment by hereisnaman** [comment]
What I am thinking is to use the service workers to make it work offline. So the service worker will use the cache storage api of the browser and will automatically store the network requests mainly the GET (which will include assets, and totally according to implementation and caching pattern) as key/value pair of request/response. 

So it is like, if we setup network first pattern, if online the service worker will fetch from the network, will respond and also save the response to the cache storage, when offline it will get the content from the cache storage and respond.

This will be like if someone has first visited the website, he can visit is offline too afterwards.

**Comment by bcolloran** [comment]
@hereisnaman -- i think i understand. Definitely a good idea to provide some kind of warning (snackbar or something) if people who are using the network features like that in #361 drop offline. Right now we're already using localStorage for offline work; see #351 for a discussion of some of the design constraints around that.

Do you have ideas about how your proposal would interact with the other workflows we're designing towards?
