### ISSUE TITLE
add correct React propTypes to two-row-cell.jsx

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#289]
cell-type-raw.jsx, cell-type-markdown.jsx, cell-type-javascript.jsx, call-type-css.jsx have propTypes and can be used as examples.

**Comment by pradeepgangwar** [comment]
@bcolloran I would like to work on this.

**Comment by bcolloran** [comment]
go for it! this and the others like it should be quick little PRs, no need to ask for any of them feel free to file PR. thanks! :-)

**Comment by bcolloran** [comment]
fixed by #308
