### ISSUE TITLE
add correct React propTypes to menu-component.jsx

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#297]
cell-type-raw.jsx, cell-type-markdown.jsx, cell-type-javascript.jsx, call-type-css.jsx have propTypes and can be used as examples.

**Comment by pbteja1998** [comment]
@bcolloran I want to take this issue, but I have one doubt though. There are already proptypes existing in `menu-component.jsx`, so what is this issue about?

**Comment by mdboom** [comment]
Once all of the PropTypes are done, we should consider turning on the eslint lints related to them.

**Comment by bcolloran** [comment]
@pbteja1998, yes i think this was fixed in a previous PR but the issue wasn't closed.
