### ISSUE TITLE
scrolling doesn't seem to work correctly on chrome?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#304]
### What I Did
- open dev/dev.iodide.html
- load the "what a js nb looks like" notebook
- `shift enter` through all cells to execute them in order

### What I Expected

only the "cells" area should be scrollable; only one scrollbar should appear on the right

### What Happened 

a second scrollbar appears, allowing the possibility of scrolling past the bottommost cell. also, the nav/menu bar scrolls off out the top of the viewport:

![image](https://user-images.githubusercontent.com/2380975/36080119-3f9d6e9e-0f40-11e8-8e8e-d104dd458a77.png)

this is probably some kind of css error-- something that works differently on Chrome and FF. So a valid fix will need to be tested on both.

**Comment by bcolloran** [comment]
Oh, i did a little more poking around, and here is a lead to follow: it looks like this might only occur in the case of rendering LaTeX in a Markdown cell. This theory is not fully tested and will need to be investigated further, but it's something to check out

**Comment by horcrux2301** [comment]
@bcolloran I will try to solve this.

**Comment by horcrux2301** [comment]
Is this UI fine?

Chrome View:- 
![up2](https://user-images.githubusercontent.com/25867561/36113560-3a6e9cc2-1053-11e8-916b-74e151869a77.gif)

Mozilla View:- 
![up3](https://user-images.githubusercontent.com/25867561/36113694-b14eec02-1053-11e8-8a57-03eb9a7065db.gif)

**Comment by bcolloran** [comment]
Hi @horcrux2301, thank you for looking in to this!

I notice that in both of those examples the menu bar scrolls off the top of the page. The desired behavior is that the menu bar always stays fixed at the top of the page, and that there should only ever be a single scroll bar on the side.

**Comment by horcrux2301** [comment]
I think this is the view that you are aiming for. However what should I do about the scroll bars along the individual cells?

![newup1](https://user-images.githubusercontent.com/25867561/36115633-a98f4588-1059-11e8-8546-fc45de596c98.gif)

**Comment by bcolloran** [comment]
Yep, that's what we want!

Scroll bars on individual cells are just fine :-) They are part of design parity with Jupyter.
