### ISSUE TITLE
deprecate DOM cell type and remove all traces of it from codebase

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#306]
We currently have a cell of type "DOM", which lets you create divs or some other element with an id. I'm personally not convinced that this is especially useful, since as far as I can tell you can get the same behavior by creating a markdown cell and creating some html inline:

```
<div id="mycoolelement">
</div>
```

Is there some motivation for these cells that I'm not aware of?

**Comment by bcolloran** [comment]
i'm not sure they are -- hamilton and I have been discussing whether or not they are idiomatic at this point. they were introduced right at the start before we had the "add markup directly within MD" workflow in mind, which i think both of us think is cleaner at this point. We're also discussing a replacement for the DOM cell workflow in #288.

I'm fine deprecating this cell type and removing that code if @hamilton approves. just want to make sure he doesn't have any other remaining use cases in mind.

**Comment by hamilton** [comment]
Yeah, it feels like it's not an idiomatic idea at this point and I'd be fine deprecating it. Originally the intent was to have a way to not clobber the DOM containers that, say, a canvas or svg-plotting JS cell was drawing to, simply by changing stuff in an MD cell that happened to have the container element. But honestly this feels kind of useless in practice, and I think between an MD cell and something like `NB.show` or `NB.print` from #288 we have everything we need.

**Comment by bcolloran** [comment]
ok, renaming the issue

**Comment by hamilton** [comment]
IMO this really only entails

1. removing the DOMCell from the code base, and 
2. updating the examples that use it (evictions notices and maybe the "what does a js notebook look like?" example?)

**Comment by bcolloran** [comment]
yep -- for completeness, remo

**Comment by pradeepgangwar** [comment]
@hamilton I am working on this.
