### ISSUE TITLE
<pre> formatting on code in MD cells no longer styled as expected

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#309]
### What I Did

write some code wrapped in back ticks in an MD cell, like:
```
`ctrl+enter`
```

### What I Expected

expected it to be styled like this: `ctrl-enter` --github style.

Or the style from Slack is maybe even nicer: 
![image](https://user-images.githubusercontent.com/2380975/36084478-8e48c85e-0f72-11e8-80f0-0ee14837c06c.png)

### What Happened 
It looks like this:
![image](https://user-images.githubusercontent.com/2380975/36084500-b7e87056-0f72-11e8-85fe-048e0d4385e5.png)

**Comment by hamilton** [comment]
this is probably another victim of the bootstrap removal, so we could find that style and re-apply it

**Comment by hereisnaman** [comment]
@bcolloran I have fixed it.
