### ISSUE TITLE
Add a button to dismiss the history and variable overlays

### ISSUE THREAD

**Issue by jaredkerim** [iodide-project/iodide#314]
Short summary of the bug. Please include the IODIDE version number where you found the bug

Version: How do i find the version?

### What I Did

Click the little arrow at the top right

### What I Expected

Some kind of overlay to show up

### What Happened 

A little overlay flew out, but didn't have any X or arrow to dismiss itself

You can click outside of it and it'll go away, but that's not obvious, it just looks like there's no way to dismiss it.

**Comment by hamilton** [comment]
Thanks for the issue!

**Comment by pradeepgangwar** [comment]
@hamilton I am working on this.

**Comment by hamilton** [comment]
@pradeepgangwar Great! I look forward to your PR.
