### ISSUE TITLE
Add some kind of introduction text or link

### ISSUE THREAD

**Issue by jaredkerim** [iodide-project/iodide#315]
Short summary of the bug. Please include the IODIDE version number where you found the bug

Iodide version: How do i find this

### What I Did

I opened iodide

### What I Expected

I expected some text or link to explain what to do next

### What Happened 

I got some buttons and an input dialog with no instructions

**Comment by jaredkerim** [comment]
And some dummy data with examples would be nice

**Comment by hamilton** [comment]
Thanks for the issue! We actually have all these things available but when you're dropped into a notebook there is no real indication of what to do next. We should figure out how to handle this.

lol "Iodide version: How do i find this" - @bcolloran this is a pretty important issue to add, if we're using this issue template.

**Comment by hamilton** [comment]
bcolloran has a great tutorial notebook that landed in a recent PR. We should also surface this tutorial in the docs so it is obvious how to get started.

**Comment by bcolloran** [comment]
i'll take on the task of making sure that the demo notebook is deployed as the landing page.

**Comment by mdboom** [comment]
Yeah, demo notebook as landing page is a good quick fix. It would be fun to use something like "[Bootstrap Tour](http://bootstraptour.com)" eventually to give users a quick walk through of the interface.

**Comment by bcolloran** [comment]
closed with #377
