### ISSUE TITLE
add current notebook version to the menu dropdown, or to footer

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#318]
Brought up by #315.

**Comment by pbteja1998** [comment]
@hamilton Is the `notebook version` the `version` present in `package.json` ?

**Comment by mdboom** [comment]
The version should be obtained from the git tag or hash (or some combination of that and the version in `package.json`).  If we use the version in `package.json`, it might appear to the user that they are running a released version when they aren't.

**Comment by bcolloran** [comment]
closing in favor of #318
