### ISSUE TITLE
menu-component.jsx and title.jsx now use setState to hold local state rather than getting state from store

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#319]
looks like a non-redux pattern got by some PR or another. @hamilton, you can maybe grab this as part of the big menu refactor in any case.

**Comment by hamilton** [comment]
Yep, this was added in a recent PR, but I do feel this is actually a correct use of component state, and is the only acceptable reason to use state within the redux paradigm. In this case, we need to use the state within the component to either show or not show the menu, which is not related to the store.

**Comment by hamilton** [comment]
I'm open to changing this of course! Just want to bring up that it doesn't seem like there's one clear answer, and perhaps it would be a good idea to come down one way or another.

**Comment by hamilton** [comment]
This will be addressed when we refactor towards modes & views. `setState` will only be used locally within a UI component when it makes sense. Moving to 0.5a.

**Comment by bcolloran** [comment]
@hamilton -- if you are good with this implementation, we can close this as wontfix. your call, you know these parts better than i do

**Comment by bcolloran** [comment]
closing wontfix
