### ISSUE TITLE
Evaluate only the selected code

### ISSUE THREAD

**Issue by pbteja1998** [iodide-project/iodide#328]
Right now, when i click anywhere in a cell and press `Shift+Enter`, the last line of that cell is being evaluated. I think it would be better if we can evaluate only some part of the cell by selecting the required part of a cell. If nothing is selected, then the behaviour would be normal(evaluating the last line).

I think this feature would be very useful as it is taking a lot of steps to press `ESC` and then `b` and then write code just so that in future that code can be evaluated too.

**Comment by hamilton** [comment]
To be clear, all of the cell is being evaluated, but only the last line will return something into the output at the moment. Implementing this behavior would break Jupyter parity.

**Comment by pbteja1998** [comment]
Is [this](https://github.com/jupyter-attic/jupyter-js-notebook/issues/87) what you are talking about? I am sorry I do not know about Jupyter Parity, what is it?

**Comment by pbteja1998** [comment]
By the way that is what I meant when I said last line is being evaluated, I meant that only the final output of a cell is being showed.

**Comment by hamilton** [comment]
Ah yes, "jupyter parity" is kind of an unclear term. I meant that as a starting point we are trying to reach feature parity with the Jupyter notebook to some extent, and what we have now is pretty fundamental to the current story.
