### ISSUE TITLE
need per-row UI to allow hiding/showing cell rows in presentation mode

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#329]
follows from #219

**Comment by bcolloran** [comment]
we need to discuss how we might want this to work.

**Comment by hamilton** [comment]
I have a pretty clear idea for this which also solves #312.

**Comment by hamilton** [comment]
@bcolloran is this relevant anymore, given the direction we're going?

**Comment by bcolloran** [comment]
nope!
