### ISSUE TITLE
auto-deploy master version of app for pages

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#334]
We found that it is kind of a shame that the notebook served in https://iodide-project.github.io/iodide/ must be explicitly updated whenever we want to give users the newest changes. Given we are moving very quickly, we will just serve master to `gh-pages`.

@mdboom is taking the lead on this, with any needed assistance from @wlach.

**Comment by pbteja1998** [comment]
https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

**Comment by pbteja1998** [comment]
[This](https://www.netlify.com/docs/continuous-deployment/)  works very well for auto deployment. It deploys everytime a push is made to the repo, it also gives the website preview for every pull request.
