### ISSUE TITLE
Eviction notices notebook seems to be busted

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#335]
### What I Did

Load iodide notebook for eviction notices, attempt to run

### What I Expected

Should load eviction notices

### What Happened 

Fails to load

There's two errors in the external dependency cell:

![image](https://user-images.githubusercontent.com/20569/36177360-58fee206-10e3-11e8-970c-882d1faedf37.png)

The metricsgraphics.css file is fine so I don't know why it can't load it. `src/nb-tools.js` seems to be legitimately gone though.

**Comment by hamilton** [comment]
Yes, I noticed this as well. I don't know how exactly to reference local files in this new paradigm so that will be broken right out the gate, and the paths for metrics graphics needs to just be updated to the cdn since I made this way before I fully knew how we were going to handle dependencies.

**Comment by hamilton** [comment]
@bcolloran do you have any pro tips for dealing with nb-tools in this paradigm, or should I load the one function for it in the notebook for now until we have `stdlib`?

**Comment by wlach** [comment]
@hamilton here's what I'm using for metricsgraphics in my own notebook:

```
https://unpkg.com/metrics-graphics@2.13.0/dist/metricsgraphics.js
https://unpkg.com/metrics-graphics@2.13.0/dist/metricsgraphics.css
```

I'm getting the same weird error for the CSS file for those locations though.

**Comment by hamilton** [comment]
Have you pulled recently? those errors shouldn't exist anymore I think

**Comment by hamilton** [comment]
Nevermind - something bad is happening. Definitely a regression from my PR madness.

**Comment by wlach** [comment]
I was using the latest version, but it seems like something got stuck in the cache. Running `git clean -f -x -d` and then `npm install` seems to have cleared things up. Sorry for the noise!
