### ISSUE TITLE
How should the tabular data output represent `null` and `undefined`

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#341]
in JS, it is not true that `null===undefined`, so we want to make sure they are not depicted the same way; however, just using the strings can be confusing in case people are actually using the strings "null" and "undefined", which is not unheard of in data sets. So should we depict `null` and `undefined` with a different font color than strings, or on a little pill, or etc?

**Comment by hamilton** [comment]
We can render the contents with typical syntax highlighting, and have `null` and `undefined` be block-label styled to differentiate themsselves from a string that says "null", for instance.

**Comment by hamilton** [comment]
It will take about 5min to assign a color to the outputted DOM elements associated with these types.

**Comment by hamilton** [comment]
I'm marking this is fixed. We have explicitly different fonts for `null` and `undefined`.
