### ISSUE TITLE
Bookmark loaded notebook

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#345]
Currently, when you reload the page, a blank notebook is loaded.

If we stored the bookmark name in the fragment (after `#`) part of the URL, we could restore directly to the same notebook when the page is reloaded.

**Comment by bcolloran** [comment]
enormous volume of thought coming, but I wanted to mention the workflow that solves this problem currently:

(1) begin work on a notebook by opening "dev/iodide.dev.html" in your browser
(2) when you have something you want to load again, `ctrl-e` export it to "dev/your-new-notebook.html"
(3) open that in your browser for testing, and it's just a browser refresh away when you update the notebook code

**Comment by hamilton** [comment]
Yes - I love this idea.

Would also be fun to experiment adding a query pair for `nb=` where we can put the contents of `data:text/json;charset=utf-8,${encodeURIComponent(exportJsmdBundle(nextState))}` there. Let's just see how big the url is to start. I know it probably is very long, but who knows - this would actually be an easy way to send someone a notebook from iodide.github.io/master or the like.

**Comment by mdboom** [comment]
Cool, and thanks for the tip, @bcolloran!
