### ISSUE TITLE
Warn when exporting from a non-release notebook

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#348]
As currently set up, exporting from a non-release notebook and reloading it at a later date may fail since the underlying resources in the iodide-project/master repo will be updated with each commit to master.  In the general case, it's still useful enough, and the utility of having a constantly updated live notebook is worth it, but do we want to warn the user about this on exporting somehow?  Alternatively, we could export a (much larger) version with all of the Javascript and CSS inlined...

**Comment by bcolloran** [comment]
obsolete pending our rethink of how exporting arhives shold work (in fact, this problem is part of what's driving that rethink).
