### ISSUE TITLE
Autosave tune ups and deprecating localstorage for regular saving

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#351]
responding to #345 and #327. --

We put in the ability to save to localStorage very early on because it was easy to dump the notebook state to a JSON string in local storage, and it let us move fast in early prototyping. Ultimately, I think that loading notebooks from localStorage is not really the paradigm we want to support, because it kind of muddies our story around portability, and it has some big drawbacks.

The drawback of localStorage are:
(1) if you change the directory in which a notebook html bundle is stored, or if you start working online and export to a local bundle, any work you have saved in local storage will mysteriously vanish (e.g., if you start working at `https://iodide.io`, save notebooks A B and C to localStorage, then export C to your local machine at `/home/user/notebook_C.html`, when you open that file containing notebook C, notebooks A and B can't be loaded from localStorage because you're not opening the file from the same domain/origin.
(1.1) If you are working with the notebook C starting by opening the file `/home/user/notebook_C.html` in your browser, you save D and E to localStorage, if you subsequently move `/home/user/notebook_C.html` to another folder, say `/home/user/iodide_notetbooks/notebook_C.html`, D and E can't be loaded from localStorage because the browser does not recognize files loaded from different directories on disk as having the same origin.
(2) we've already had to build a "delete notebook" function; if we continue with the metaphor that the app hosts "files" and that the correct way of accessing other notebooks is from _within the app_, if we hope for people to do real work using this tool one day, we'll need to build an _entire suite_ of notebook management tools -- basically a file explorer for managing localStorage within the app. Ick. We should make sure the preferred workflow revolves around files, so that normal file management tools are the only way of managing a collection of notebooks.
(3) in addition to not working with normal file managers, localStorage doesn't work with any of the skillions of other tools that can handle text files -- text diff tools, version control, etc. There is a lot of value in being compatible with these texty tools, which is why we've invested in JSMD
(4) the amount of data that can be saved in localStorage is pretty limited. Again, if we want people to do real work (that is: lots of notebooks), and if we want to support bundling data within a notebook, this will be a problem.

There is at least a couple drawbacks to using export:
(A) export actually functions as a download, so it will default to someone's downloads folder, or whatever folder they last downloaded to or something like that. This will be confusing for some users.
(B) since it's a download, it won't be as seamless as pressing "ctrl-s" and updating the file on disk. depending on your browser settings, it might be that:
    - if your browser automatically puts files in "downloads", if you export a few times you'll end up with e.g. "notebook.html", "notebook (1).html", "notebook (2).html", "notebook (3).html", ... or something like that 
    - if your browser always asks you where to put files, you have to navigate to where you want the file kept, and potentially rename it to overwrite the last "notebook.html". This is several clicks an some keystrokes.

Using exports will be a somewhat more annoying workflow in the short term (but it's not _too_ too bad, i've been using it...), but I think building more functionality around localStorage is a red herring and some of the issues will be almost show-stoppers in the longer term. So I think that we should move in the other direction -- tear off the band-aid, deprecate localStorage for saving notebooks, and look for other ways to improve the workflow (some thoughts on that below)

Here's my proposal (which we'd break into a bunch of issues)
* localstorage is used only for saves/autosaves between exports; saved entries in localStorage are not keyed by notebook title, but rather by a random notebook id that is created along with a new notebook and saved in the "meta" section of the JSMD.
    * local storage only saves JSMD to conserve bits (also, keeping all of the state has hidden a few bugs)
* we replace the "saved notebooks" menu with a "previous versions" menu -- a notebook can _only_ load other versions the same notebook; the most recent autosave, and maybe a few user initiated "checkpoints" (the `ctrl-s` action).
    * on loading a notebook, we can check localStorage for saved versions of the same notebook; if newer versions are found, we can popup an offer to load the latest (or to select a revision?).
    * to partially address what i think is the workflow needed in #345, we could have something like "notebook.html#autorestore" that loads the most recently autosave or `ctrl-s` checkpoint (we could even have different flags here for autosaves and manual checkpoints if that kind of granularity is needed, but i don't think it would be)
* we get rid of the concept of "saving as" by changing the notebook name and pressing `ctrl-s`; to branch a notebook way, an explicit export is required. [question: does every export spawn a new notebook id? or is an "export as" type action required?]
* we move "examples" out from under "saved notebooks" (ha it just occurred to me that this is not very discoverable, maybe contributes to poor experience in #315). Instead, add a top-level "examples" menu item that is populated with links to notebooks deployed online (or opens a popup with links).

wrt mitigating some of the wrinkles with exporting to the filesystem, at least two eventual options occur to me:
(1) a light weight webextension could make saving pretty seamless -- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download .
(2) a server-side something for saving notebooks somewhere if you're signed in to something (either a service we provide one day, or like github or some other remote file saving service that has an easy to use API?)
Making the fully standalone and portable use case work as effectively as possible is the top priority, but suggesting a light webextension or a service for people that are using Iodide for real work and want a few workarounds for browser limitations would be acceptable.

**Comment by bcolloran** [comment]
Hamilton and i have a plan for this, the first part of which is to encourage people to start adopting the export workflow rather than the localStorage saving workflow. The gist workflow #361 will also be nice, but not a blocker to this. In any case, this is not top priority ATM, and will wait until 0.5a probably

**Comment by hereisnaman** [comment]
Understanding the drawbacks of both localstorage and exports, I feel that using gists as the main storage will be the best idea, we can still have exports and localstorage. 

There is a netlify CMS for gatsby which works as a admin panel for your gatsby project hosted on github. It gets itself access to your repo and proxy commit the changes you do from the GUI admin panel. We can have that kind of functionality. 

# Benefits of using Gists
- Integration with GitHub, Bitbucket, GitLab....
- Increased shareability
- Automatic version control
- Public and private notebooks (or with access to specific people)
- Fork feature (depends on platform)
- Easy exports
- community and engagement
- team collaboration

## Exports
**Owner:** export to local file system the same way it is doing now. We can also share the url to local git clone.
**Others:** export to local file system the same way, or clone/fork to a gist platform using the api. we can also share the url to local git clone.

## Shareability
URL structure can be: `iodide.com/<platform initials>/<platform username>/<gist id>`
**Example:** 
- GitHub: `iodide.com/gh/hereisnaman/c6704e49bbb86375accd999c0616c446`
- GitLab:  `iodide.com/gl/hereisnaman/1699973`
- BitBucket: `iodide.com/bb/hereisnaman/be9RBj`

## Save
If integrated with some gist, can be pushed directly using the api on explicit save. Auto save can still be using local storage and all the features of auto save can be implemented as discussed above.

**Comment by hereisnaman** [comment]
@bcolloran what you think ?

**Comment by bcolloran** [comment]
Getting gist integration working will be a huge help @hereisnaman! :-)

Let's see if we can limit the scope a bit so that we can break it into chunks that will fit into a few smaller PRs.

I'll reference you in #361, where we're talking about how we want that functionality to work.

**Comment by bcolloran** [comment]
this is part of the iframe-2 milestone 0.6b.

**Comment by bcolloran** [comment]
@wlach, as part of work around getting the server side saving story in place, i'm also going to revisit this issue. client-side saving of notebooks in localstorage is buggy, so i'm going to move in the direction of just using local storage for autosaves, as described here, and we'll use the landing page that you and @djbarnwal have been working on for managing a users collection of notebooks (rather than the dropdown menu, which is broken anyway on iframe-2)

**Comment by bcolloran** [comment]
task are:
- make sure autosave is working on iframe-2
- remove option to "save" to localStorage
- generally robustify handling of localstorage, and make sure there is only one entry/exit point probably through `actions.js`
- use the id strategy described above
