### ISSUE TITLE
"report/explore" vs "view/edit" or "presentation/editor"

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#352]
"presentation mode" has always felt like a bit of a mouth full, and we have a number of things in the code that are modal and thus show up as `whateverMode`; this is a small thing, but i like the words "explore" and "inquire" and then "report"; terser than "presentation", but nicer sounding than "view". it's like you are exploring an idea or data set or whatever, then reporting on your findings.

This would also allow us to more cleanly relabel some of the modal concepts: `reportView` and `exploreView`; and within explore view, there is `commandMode` and `editMode`. Or rather: instead of having two things we call "mode", we can call on thing "view" and the other "mode".

so for example, we could simplify code from this:
```
export function mapStateToProps(state, ownProps) {
  const cell = getCellById(state.cells, ownProps.cellId)
  return {
    cellSelected: cell.selected,
    pageMode: state.mode,
    viewMode: state.viewMode,
  }
}
```
to this
```
export function mapStateToProps(state, ownProps) {
  const cell = getCellById(state.cells, ownProps.cellId)
  return {
    cellSelected: cell.selected,
    mode: state.mode, // "edit", "command", "title", etc
    view: state.view, // "explore", "report"
  }
}
```

**Comment by hamilton** [comment]
I've been thinking about this on and off over the last week, and think it's the right idea, and would be happy to begin pursuing this. As for `mode`, I think there are only three: `edit`, `command`, and `menu` modes. `menu` mode is our way of turning off keybindings (like #284) for menu work, such as changing the title, working through an export dialog, etc.

**Comment by bcolloran** [comment]
+1. I should also mention that we should probably move these options into enums as a matter of hygiene, a la #97.

If you're on board with this, i can write it up in more detail and mark it as "help needed".

**Comment by bcolloran** [comment]
done in iframe-2
