### ISSUE TITLE
Use output handlers in declared variable pane

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#358]
currently, the declared variables pane renders all of the declared variables within a `JSONtree`. It would be a nice improvement of the utility of the declared variable pane to display the value of each declared variable using the `CellOutput` component.

**Comment by pradeepgangwar** [comment]
@bcolloran Can i try it?

**Comment by bcolloran** [comment]
yeah go for it Pradeep :-) if you have any questions, please ask me or @hamilton or @mdboom

**Comment by mdboom** [comment]
@pradeepgangwar: I agree, go for it.  You may want to wait until #344 is done (hopefully today), since it will make it easier to call output handlers recursively.

**Comment by pradeepgangwar** [comment]
Since #344 is done, i am working on this.

**Comment by bcolloran** [comment]
To add some more detail to the requirements of this issue:

the declared variable panel should iterate over each item in its `props.variables`, and display each individual value in it's own <CellOutput> element. It should also display the variable name, so, schematically, it should look like

```
Object.keys(this.props.variables).map( (key,i) => {
  <div key={i}>
     {key}: <CellOutput valueToRender={this.props.variables[key]}  />
  </div>
}
```

_this is not the correct implementation_, but it will be something like that
