### ISSUE TITLE
make sure "CellOutput" component if generic enough to be used in multiple places

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#359]
@hamilton @mdboom -- i think this might be as simple as changing the name from "CellOutput" to e.g. "ValueRenderer" or something, but we should double check that it will work without any problems if we use it in other places, e.g. #358

Is this a good first issue?

**Comment by hamilton** [comment]
I encountered this warning when running @mdboom's output handler example via `https://iodide-project.github.io/master/?url=https://raw.githubusercontent.com/iodide-project/iodide-examples/master/output-handling.html`
```
warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `CellOutput`. See https://fb.me/react-warning-keys for more information.
    in span (created by CellOutput)
    in CellOutput (created by JsCellUnconnected)
    in div (created by CellRow)
    in div (created by CellRow)
    in CellRow (created by Connect(CellRow))
    in Connect(CellRow) (created by JsCellUnconnected)
    in div (created by CellContainer)
    in CellContainer (created by Connect(CellContainer))
    in Connect(CellContainer) (created by JsCellUnconnected)
    in JsCellUnconnected (created by Connect(JsCellUnconnected))
    in Connect(JsCellUnconnected) (created by Page)
    in div (created by Page)
    in div (created by Page)
    in Page (created by Connect(Page))
    in Connect(Page)
    in Provider
```

**Comment by mdboom** [comment]
I found the source of @hamilton 's comment above, but I'm not sure I understand the larger issue.  Is it just that `CellOutput` is a name clash with something else?

**Comment by bcolloran** [comment]
Oh the larger issue is just about (a) the naming convention, since we want to be able to use this variable formatter in other places (like the declared variables pane) and (b) tweaking it a bit so that there's a version that doesn't require any props passed in from the "cell" context (which i think is just `props.render`).

Maybe the way to do it would be something like: turn the `renderValue` into a component that can used in any context, and have the `CellOutput` component use that new component when `props.render===true`? Then we can use that new `ValueRenderer` (or representer or if we want to follow devtools) component in e.g. the variables pane as well.

Or we could just always pass `props.render=true` i guess.

in any case: the issue is mostly just a reminder to take a look at it when organizing things into files for #276 -- it's not really an "issue" per se
