### ISSUE TITLE
Output handlers for all built-in data types

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#360]
@mdboom @hamilton 
following from #341 and #344 -- we could make sure that all basic data types have output handlers that render them in a way that makes it a bit clearer what the of the variables are (like syntax highlighting in the editors). For example:

- Strings might render as blue `<pre>` tags
- numbers in green
- functions as `function fncNam(...){...}` , where hovering or clicking shows detail about the arg and internals,

and so on.

If we can spec out what we want, these could be nice little atomic "first issues"

**Comment by mdboom** [comment]
That's cool.  I wonder if there's any way to leverage/borrow the code for this from Firefox Dev Tools?

**Comment by mdboom** [comment]
To answer my own question: Looks pretty easy to use DevTools rendering:

https://github.com/devtools-html/devtools-core/tree/master/packages/devtools-reps

I suspect this will form a basis, but not 100%, of what we want since data scientists needs will be different from regular-old-JS-developers, but it probably helps us not reinvent the wheel for the basic stuff.

**Comment by mdboom** [comment]
I clearly reinvented a wheel.  At a high-level it's basically the same thing (it even contemplates extensions in a comment).

https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-reps/src/reps/rep.js

There might be a lot of benefit to rejiggering what we have to use this and then building the data-science-specific parts on top.

**Comment by bcolloran** [comment]
Oh borrowing from devtools is a great idea! I haven't studied the code in depth, but if you think it looks like a good foundation to build from, let's try it out!

i don't know whether this is actually helpful or we'd want to just borrow chunks of the source more directly, but:
https://www.npmjs.com/package/devtools-reps
:-)

**Comment by bcolloran** [comment]
oh, they even have a "tiny/short/long" concept, which maybe they've found is a good way to handle the stuff we were discussing around recursive rendering in #344. Nice find Mike :-)

**Comment by hamilton** [comment]
This is awesome @mdboom! The tiny/short/long abstraction is perfect.

**Comment by hamilton** [comment]
Hey @bcolloran / @mdboom - I'm revisiting [devtools-reps](https://github.com/devtools-html/devtools-core/tree/master/packages/devtools-reps) library and thinking of integrating some of these soon. Thoughts?

**Comment by mdboom** [comment]
I still think it's a good idea.  The most recent information I have is that the design of devtools-reps is pretty heavily around remote objects (the developer tools always exist in a separate worker from the code being debugged for obvious reasons), and it would take some work (not sure how much) to adapt it for local objects.  But it would be great to not reinvent this wheel...

**Comment by hamilton** [comment]
Ah yes. I missed the other issue saying this.

**Comment by bcolloran** [comment]
yea as we discussed yesterday -- if you think you can get this in without too much trouble, i think you should go for it; if it starts to feel like more overhead to fit it into our universe (and to make our existing/future reps conform to those patterns) than to reinvent this particular wheel, welp than that is what it is and we'll roll our own. i haven't looked at it at all and you guys have, so whatever you think is best is ok with me.

**Comment by hamilton** [comment]
@bcolloran is this something we ought to close?

**Comment by bcolloran** [comment]
yeah i suppose so. thanks @hamilton :+1:
