### ISSUE TITLE
add current app version to iodide namespace

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#362]
We want to make sure that `IODIDE_VERSION` provided by webpack makes it over to `api.js`, so the user has a cell-based way of asking which version of the app they are on.

**Comment by mdboom** [comment]
It would be useful to add a git hash to this version string if it's not a tagged release, too.

**Comment by bcolloran** [comment]
iframe-2 branch will have `iodide.VERSION`

i'm not sure how to do the git hash

**Comment by bcolloran** [comment]
closing, see #494
