### ISSUE TITLE
Let and const variable declaration does not work

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#365]
I am working on the latest version of MASTER branch. I was trying to use ES6 syntax in the notebook.

### What I Did

I entered `let a = 5` and `const c = 6`

### What I Expected

On next cell entering `a` should give 5 and `b` should give 6

### What Happened 

![11792c8b-f6c7-491d-8a40-9a66c0b5214b](https://user-images.githubusercontent.com/4402679/36340537-37025e4c-1405-11e8-8b43-014e5a4a15d5.png)

I tried adding other ES6 syntax like template string and Sets and they were working just fine.

**Comment by hamilton** [comment]
`let` and `const` are locally scoped within `eval` (which is what we are using at the moment to evaluate cells), so this is (unfortunately) expected behavior.
