### ISSUE TITLE
How to do "integration" tests of React components connected to the Redux store?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#375]
I think we have a good strategy for testing _unconnected_ react components, as described in these two articles:
https://hackernoon.com/unit-testing-redux-connected-components-692fa3c4441c
https://medium.com/wehkamp-techblog/unit-testing-your-react-application-with-jest-and-enzyme-81c5545cee45

But we don't have a good strategy/pattern for testing actions fired by components connected to the redux store. I've played around some with enzyme `mount` rather than `shallow`, but i wasn't able to get it to work.

If anyone has experience with this or wants to try to figure it out, that would be a big help. I think the easiest place to start would be with the markdown cell (cell-type-markdown.test.js), because that component only responds to onClick and onDoubleClick events, and both of those events only fire the same method, `enterEditMode`, which in turn fires one or two Redux actions, so the change to the final state will be very limited.

Working PRs for this would be very very useful.

@pradeepgangwar @djbarnwal -- it sounded like you two might be interested in trying this out?

**Comment by imshubhamsingh** [comment]
@bcolloran I think I could help for this one, just wanted to know what do you mean by 
> testing actions fired by components connected to the redux store
Is it whether on double click, testing is needed for checking action changeMode and markCellNotRendered has been fired or is it  testing for change in state due to these actions?

**Comment by hamilton** [comment]
We more or less have a story around this for now.
