### ISSUE TITLE
Break up notebook header in separate components

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#376]
right now, notebook-header.jsx contains I think about four top-level react components; it should really be split up so that each top-level component is in its own file.

Initially, a PR that just splits these up will be accepted, but it would be possible to go above and beyond by:
* making sure that each new component only has access to the minimal amount of the state it needs (by removing unneeded variable in each components `mapStateToProps` function). This is basically issue #176
* adding unit tests for each new component. For now, just testing the unconnected component would be a great step (since we still haven't figured out our strategy for testing connected component actions, see #375 ).

**Comment by pradeepgangwar** [comment]
I am working on thia
