### ISSUE TITLE
"new notebook" action should open a blank notebook in a new tab

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#381]
we think this will be clearer and more consistent with the mental model we want to move towards in #351 

There are couple design issues we want to work out--
1. should the new blank notebook load from a web url? if so, presumably from `master` for the time being?
2. or should it attempt to determine if you're working from a local file and attempt to be clever about checking whether e.g. `iodide.dev.html` is available in the same folder, and if it is, load that file in a new tab?

Or maybe it should attempt (2) and fallback to (1)? i guess that seems best.

@wlach @hamilton @mdboom  any other wrinkles around this?

**Comment by hamilton** [comment]
This was impleneted somewhere.
