### ISSUE TITLE
find (and replace) is weird with codemirror

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#396]
It would be great to have a find (and replace) solution that works.

Ctrl-F in the browser currently returns nonsensical results -- this is basically a bug.

for Real Work, though, we'll also need a reasonable ability to do find+replace; this part would be a new feature enhancement

**Comment by hamilton** [comment]
@bcolloran I'm finding that at least the "find" part of this equation works pretty nicely now w/ the jsmd editor (results seem coherent). Should this be closed or updated?

**Comment by bcolloran** [comment]
yea i think this is superseded by #579 . thanks!
