### ISSUE TITLE
data frame viewer causing terrible app performance?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#403]
### What I Did

loaded a couple data sets (5550 rows x 44 cols; 70k x 6)

returned values of these tables and a mutated dataset

app slowed way way way down; editing etc was basically unusable.

reran these cell, but returned a string in each, and app performance came right back.

this needs to be tested/verified, but initially it looks like something in the data table viewer is killing perf.

**Comment by mdboom** [comment]
I wonder if this is related (at least in part) to some of the discussion in #420.  It seems the output handlers are getting called multiple times which probably thrashes the gc even more than it has to.

It's possible ReactTable isn't the most performant option.  Google tells me there's [lots of options](https://jspreadsheets.com/)

**Comment by bcolloran** [comment]
Ya I think you're absolutely right Mike.

**Comment by bcolloran** [comment]
Confirmed. The datagrid component itself seems to be ok even with several of them present, we've just been doing not very good updates (passing too much state to some components), which has caused cascades of updates to tons of components
