### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#404]
[React 16](https://auth0.com/blog/whats-new-in-react16/) has a number of big updates, particularly Fiber, which could have big (positive) performance implications. It also has support for fragments, which would be immediately useful for a PR I am working on now, and would be generally useful for the future. The API changes seem fairly minimal and I don't believe would break our app.

Not pressing, but worth bringing up.

**Comment by bcolloran** [comment]
This would actually fit within our code cleanup push for 0.4a, and if you need it anyway for what you're working on, I think it would be reasonable to see if you can get it working in a quick PR in another branch, then you can merge that branch into your other project branch and keep going. If we merge the final PRs in order, it should be fine i think, right?
