### ISSUE TITLE
Importing .ipynb notebooks on Iodide

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#409]
A big part of the scientific community today works on Interactive Python notebooks. It would be great if we could support .ipynb notebooks on Iodide. These notebooks are JSONs and contain `cells` array which can be mapped to Iodide's `cells`. I am not sure how feasible this can be but I am assuming we need to find a way for easy interaction and exchange between Jupyter and Iodide Notebooks as the project grows. It is not a necessity now but could be of great help in the long future.

**Comment by bcolloran** [comment]
It's a great idea Dhiraj! It would be really cool to enable this as our ability to handle python matures, definitely something we should explore as that progresses!

**Comment by mdboom** [comment]
I agree, this is a cool idea.  The hard bit is making the code itself work (i.e. our Javascript environment is significantly different from Jupyter with the Node.js kernel, and our Python environment is also different from Jupyter with the IPython kernel).  So I don't think the goal of "load and run" is necessarily feasible.  However, it would still be very useful to load a Jupyter notebook as a starting point and then edit it into shape to run in Iodide.

The Jupyter notebook format is pretty well documented and reasonably stable: http://nbformat.readthedocs.io/en/latest/  I'd suggest just starting with the latest version of the notebook format and not bothering to support anything earlier -- `nbconvert` is already able to migrate from older versions to newer ones.

**Comment by hamilton** [comment]
fwiw, @mdboom has implemented this in #631

**Comment by mdboom** [comment]
Oops... forgot we already had this.  Hope we didn't duplicate effort, @djbarnwal

**Comment by djbarnwal** [comment]
No, we didn't. Was planning to work on it sometime later. Thank you @mdboom for implementing this.
