### ISSUE TITLE
Migrating to a studio view

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#410]
while working on #408, it became apparent that we could pretty easily refactor the side panes to be optionally-persistent, and the pane could easily move over the main cell content instead of overlapping it. This would be the quickest way to get us to something similar to RStudio while maintaining the cell pane as-is, and would open up the possibility of other types of modules (plots, perhaps a way to search cdnjs.org to get other libs quickly, etc.)

**Comment by mdboom** [comment]
FWIW JupyterLab developed a Javascript library specifically for this kind of stuff: http://phosphorjs.github.io/  It's for building the sort of "paned" user interfaces that you see in Visual Studio, Eclipse etc.

**Comment by bcolloran** [comment]
fwiw: a proper studio view would require a few other things, most important of which would be to have a single editor with pure JSMD and that would allow execution of code per JSMD block and execution of selected code (a la MATLAB's editor adn Rstudio). persistent panes will be very useful, but would just be a part of that.

**Comment by bcolloran** [comment]
deprecated while we consider #593
