### ISSUE TITLE
scrolling in report (presentation) view broken

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#416]
Steps:
- open https://iodide-project.github.io/iodide-examples/what-a-web-notebook-looks-like.html
- press "view" button
- scroll to bottom

results:
- scroll bar goes out the bottom of the viewport
- content is inaccessible off the bottom of the page

same in FF and Chrome; same whether running all or not.

Looked fine in edit view... i guess we forgot to check report view in our QA cycle, @hamilton, oops :-)

@hamilton  i think this basically on your agenda anyway, re the stuff around CSS fixes (esp for report view) and re scrolling issues, and re putting things into panes. Just wanted to flag this as something to double check when you're working through those other bits.

see also #304 for a similar scrolling problem

**Comment by hamilton** [comment]
Yeah, that's wild, and a pretty serious problem!

**Comment by hamilton** [comment]
Closed via #449
