### ISSUE TITLE
outputs retroactively handled by output handlers

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#420]
steps:
- load https://iodide-project.github.io/iodide-examples/output-handling.html
- run all
- 3rd cell with `let obj = {'lat': 42, 'lon': 49}` shows tree viewer
- switch to report view ("view" button)
- switch back to explore view ("edit" button)
- 3rd cell with `let obj = {'lat': 42, 'lon': 49}` now shows image

this is probably one of those weird react quirks where triggering an component re-render also rerenders all children, which in this case will use the most recently registered output handlers.

**Comment by mdboom** [comment]
Interesting.  Probably related to this, I've noticed that output handlers get called a bunch of times every time a cell is evaluated.

I feel like what we really want is to "freeze" the HTML of the output immediately, and basically skip over all the React magic (for cell output only).
