### ISSUE TITLE
Output renderers might need a "post mounting" callback

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#425]
Given that Google Maps no longer works without a key, I was exploring using Leaflet with some free map tile providers to replace our mapping example.

However, leaflet expects to work like this:

1) Have a DOM element in hand
2) Call a Javascript function on it to set up the map rendering in it

This is hard to do given our current output handler design which takes a DOM Element, converts it to HTML, converts that to a React component, which eventually converts it back to a DOM Element.

We could provide another hook so that the user could call Javascript after the final DOM Element is created (this is the `componentDidMount` callback in React, as far as I can tell).

Alternatively, and given #420, maybe the better thing to do is to take React components out of output handling altogether.

**Comment by bcolloran** [comment]
Hmmm, i think that the output renders could justifiably be limited in scope to rendering a "final" value -- so if that final value is an HTML string, a dome node, or some other final value that can just be _rendered_, we provide facilities to allow smart rendering, but anything more complicated (requiring side effects, state, mutation) is up to the user to handle. So REST-type calls that work in this was might not qualify.

Or, to put it another way: we might be able to limit the scope of our built in output handler API without losing too much if we restrict output handlers to being pure sychronous functions of their input value.

I'm not sure, what do folks think?

**Comment by mdboom** [comment]
I think it's probably fine to restrict output handlers to being pure sychronous functions of their input value.  If we just took what was returned (a DOM Element) and added it directly to the output <div>, then libraries like Leaflet that need to hook into a DOM node should be happy.  Right now, by going to React and back for no real "Reactive" benefit, we lose that.

All that said, I don't know if doing that would break things like `ReactTable` etc. that we use to display data frames.

**Comment by bcolloran** [comment]
closing this as our custom rep store has moved on substantially in the last year :-)
