### ISSUE TITLE
migrate away from "title-edit" mode to "menu"

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#427]
We need a way to turn off all command mode keybindings while using menus. This is a problem for drawers, menus, and changing the title, which at the moment `console.warn`s when editing the title that the `title-edit` is not an admissible state in the cells.

This seems like it'd be worth doing sooner rather than later.

**Comment by bcolloran** [comment]
@hamilton is this issue still active? i have a vague inkling that you fixed it already?
