### ISSUE TITLE
New demo Iodide Notebook

### ISSUE THREAD

**Issue by imshubhamsingh** [iodide-project/iodide#428]
Working on a new demo iodide notebook which is an attempt to visualize and help to understand how some of the most famous sorting algorithms work. So far I've implemented only selection sort, I'll add more sorting algo to it.

![ezgif-5-8822698393](https://user-images.githubusercontent.com/17807743/36932985-a3132632-1ef7-11e8-8ce2-0ec8c6a9be9b.gif)

@bcolloran and @hamilton what you guys think about this demo book.

**Comment by imshubhamsingh** [comment]
I've add two more algo to the list. 
![ezgif-5-8822698393](https://user-images.githubusercontent.com/17807743/36936020-85e53a86-1f25-11e8-9f1b-5e82e044ce8a.gif)

**Comment by hamilton** [comment]
@imshubhamsingh this sounds great! Please file a PR over at https://github.com/iodide-project/iodide-examples and we can take a look and see it as it develops.

**Comment by imshubhamsingh** [comment]
@hamilton and @bcolloran I fileed a PR over [ https://github.com/iodide-project/iodide-examples]( https://github.com/iodide-project/iodide-examples), could you guys please check

**Comment by hamilton** [comment]
Thanks for the PR over in `iodide-examples` - going to close this issue.
