### ISSUE TITLE
css cellType not mapped while saving

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#429]
### What I Did

Created a notebook, saved it, opened it again. Ran all the cells together

### What I Expected

Everything to work as it is

### What Happened 

Cell type of CSS cells are changed to JS and hence compilation fails.

Seeing the JSMD stored on local storage, I was able to find out that CSS cells are not being recognized. I will send a PR to fix this.

**Comment by hamilton** [comment]
Closed by #430
