### ISSUE TITLE
Option for clearing output/execution

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#431]
There should be an option to clear the output and execution of the notebook. 

Recently, I have been playing a lot with the notebook. While working I often make small tweaks to one or two cell but in order to see its change, it is preferred that the previous execution and output along with the declared variables are cleared. A typical example is when something like `element.innerHTML += string ` is part of the code. Running the cells again without clearing the previous execution gives out unwanted results. 

For now, I have to resort to saving the notebook, reloading the page and again importing the notebook which is altogether too cumbersome.

**Comment by bcolloran** [comment]
+1, good idea @djbarnwal, would you like to implement this?

right now, there is a function `clearUserDefinedVars` in the file `notebook-reducer.js` that we call when a notebook i created, loaded, or imported, but we could have a separate UI task and redux action just for clearing user defined variables.

@hamilton, what do you think? @djbarnwal, if you're up for this one, hamilton can give you tips on creating UI tasks within his new and improved framework if you need help, but his framework might be clear enough that you can jump right in if you want. `task-definitions.js` is probably the right place to start looking at how that pattern works.

**Comment by djbarnwal** [comment]
@bcolloran Sure, I'll work on this. I will read the entry points and go through the complete loop of one or two executions. That would help a lot in understanding the codebase. Moreover, since the project is modular and made from indepenedent and loosely coupled components, it wouldn't be very difficult to catch up. Nevertheless, I'll make sure to contact you guys if I get stuck somewhere :-)

**Comment by hamilton** [comment]
This worked out well :) fixed in #434.
