### ISSUE TITLE
Option to select some cells and run them

### ISSUE THREAD

**Issue by pradeepgangwar** [iodide-project/iodide#432]
I am not sure how much useful it would be but if we can have an option to select some cells and execute them it would be really cool.

Please share your views on this.

**Comment by bcolloran** [comment]
Oh yes, it's a very good idea. Somewhat related to the cell cut and paste #65 in that it would require the ability to select or "highlight" multiple cells. I'll add an issue for that

**Comment by bcolloran** [comment]
blocked by #433

**Comment by hamilton** [comment]
This seems like it'll be obsolete once we move to JSMD editing.
