### ISSUE TITLE
add ability to "highlight" multiple cells (for "run selected", cell cut and paste)

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#433]
in order to facilitate "cell cut and paste" #65  and "run selected" #432 , we'd need to add the ability to have multiple cells selected to the state schema

**Comment by pradeepgangwar** [comment]
@bcolloran I would like to give it a try.

**Comment by bcolloran** [comment]
Cool, thanks Pradeep. :-) You might want to off on this one for a couple days, i have some changes coming around how state is managed and validated. Maybe we can check in around Wednesday? Thanks!
