### ISSUE TITLE
Visualization Algorithm notebook not working

### ISSUE THREAD

**Issue by imshubhamsingh** [iodide-project/iodide#440]
I was trying to add new features to the notebook, it was working just an hour ago. Now Its broken. 

### What I Did
Just ran the notebook

### What Happened 

![image](https://user-images.githubusercontent.com/17807743/37011143-ca4f5698-2114-11e8-91d6-264d7a95fdaf.png)

### (OPTIONAL) notebook that reproduces bug 

I think this was caused due to addition of ajv in #437

**Comment by hamilton** [comment]
Ah, yes. This would have caused it. We're still in a pretty early stage of this project, so we are hoping to get done as quickly as possible these major changes that break some things. Apologies.

@bcolloran do you have a suggested way to move forward on this? I'm sure it wouldn't be hard to suggest an easy fix to get @imshubhamsingh moving again.

**Comment by imshubhamsingh** [comment]
@hamilton  and @bcolloran, Found the cause of the error, fixed it and filled a PR. The notebook is working now
