### ISSUE TITLE
Use firefox devtools-reps to display values

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#446]
Firefox devtools-reps comes very close to what we need to display objects.  Unfortunately, most of the sophisticated stuff assumes that you have a remote object (since Devtools runs in a separate process from the Javascript it is debugging).

There is an open issue here https://github.com/devtools-html/devtools-core/issues/524 to track this.  If I understand correctly, the main work involved would be a wrapper to have local objects behave like remote objects.  Clearly there's support and buy-in for this change from devtools-reps, but we may need to provide some cycles in order to get this done.

**Comment by bcolloran** [comment]
we've decide to go another way on this one, closing
