### ISSUE TITLE
should we move console.warn out of the jsmd tools?

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#448]
original point: I assumed the parse warnings were being triggered by an outdated jsmd blob used in testing, but that's actually the right idea - we want to induce the parse warnings.

**Comment by bcolloran** [comment]
we can get rid of those warnings once we have an app error UI. in the meantime, i'm not sure what to do about this. i think those `console.warn`s are useful warnings to have in the browser console, but the test intentionally trigger those errors to make sure they are caught/handled/warned correctly.

oh, note also that the warnings are in the jsmd parser code, not the test itself.

maybe there is a way to suppress console output within specific test cases or something like that?

**Comment by hamilton** [comment]
Got it. I understand the warnings are in the parser itself. Just wondering if perhaps we ought to be keeping the actual `console.warn` of the parse warnings in the history / state itself, and not rely on this otherwise pure function to report the parse warnings.

**Comment by bcolloran** [comment]
oh interesting. yes i quite like that idea - we can find some way to migrate the warnings thing to actions+reducers even before we have a UI built, and can just fire the `console.warn` for now until we can use the app error mechanism. much more elegant solution, nice.
