### ISSUE TITLE
tooltips missing since header refresh

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#454]
@hamilton -- looks like the tooltips that used to exist for the header buttons are no longer there. I looks like we just need to wire the "title" properties of the usertask definitions to the button components. Will that make a good first issue, or do you prefer to handle it yourself?

**Comment by hamilton** [comment]
I'm happy to handle it! The API changed enough that I had totally neglected
going through the docs and seeing how they were re-implemented.
