### ISSUE TITLE
tooltip text is a bit small

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#458]
on my screen it looks like its only 7-8 px, very small. should be standard 11-12ish probably.

**Comment by hamilton** [comment]
For anyone who takes this, take a look at the [Tooltip docs](https://material-ui-next.com/api/tooltip/).

**Comment by pradeepgangwar** [comment]
@bcolloran @hamilton tooltips are completely missing in Firefox :sweat_smile:

**Comment by djbarnwal** [comment]
@pradeepgangwar I am on Firefox and tooltips are visible to me. Try fetching the latest version of master. Maybe that would resolve the issue.

**Comment by pradeepgangwar** [comment]
@djbarnwal It is visible now, I think i missed refreshing after i did npm start.

**Comment by bcolloran** [comment]
Reopening this issue, as i've noticed that not all tooltips are fixed. Notice in particular that the tooltip for the hamburger menu and the "view" button are still smaller than the others.

![peek 2018-03-13 22-51](https://user-images.githubusercontent.com/2380975/37385521-65f112ec-2711-11e8-89ed-291bb0c1a01c.gif)

Looks like all tooltips and the corresponding code should be double checked, there must be some pattern we missed in #466
