### ISSUE TITLE
possibly unneeded peek at state? (maybe need small refactor of `saveNotebook`)

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#461]
just noticed this in the code here:

https://github.com/iodide-project/iodide/blob/e1520924cdb9326aa01ed8c9f1957f0d6eafb3cf/src/task-definitions.js#L259

```
  253  
  254: tasks.saveNotebook = new UserTask({
  255    title: 'Save Notebook',
  256    keybindings: ['ctrl+s', 'meta+s'],
  257    displayKeybinding: commandKey('S'),
  258    preventDefaultKeybinding: true,
  259:   callback() { dispatcher.saveNotebook(store.getState().title) },
  260  })
  261  
```
I think we should not need that `store.getState().title` for any reason -- the reducer will have access to the store as it's processing the `saveNootbook` action.

@hamilton, do you recall any reason why this was needed? Even if it is currently needed, a small refactor of `saveNotebook` should be able to polish it out (I can take that on if it's needed)

**Comment by hamilton** [comment]
I cannot recall, but if I remember correctly this was taken from the keybindings. I perhaps added it without thinking, or it was in that file to begin with. Either way, would be very happy to remove this peak into the store!

**Comment by bcolloran** [comment]
great, i'll take care of it
