### ISSUE TITLE
Deploy step seems to be failing

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#471]
Recent builds on travis seem to be failing the deploy step. For example: https://travis-ci.org/iodide-project/iodide/jobs/351750127

```
Initialized empty Git repository in /tmp/d20180310-4648-18cdh85/work/.git/
Switched to a new branch 'master'
cd -
cd /tmp/d20180310-4648-18cdh85/work
commit 731d2388631c445d28322abd6de682c40c73c588
Author: Deployment Bot (from Travis CI) <deploy@travis-ci.org>
Date:   Sat Mar 10 17:37:39 2018 +0000
    Deploy iodide-project/master to github.com/iodide-project/master.git:master
 index.html                                      |   15 +
 iodide.master.css                               | 3638 +++++++++++++++++++++++
 iodide.master.css.map                           |    1 +
 iodide.master.fonts/KaTeX_AMS-Regular.eot       |  Bin 0 -> 71656 bytes
 iodide.master.fonts/KaTeX_AMS-Regular.ttf       |  Bin 0 -> 71428 bytes
 iodide.master.fonts/KaTeX_AMS-Regular.woff      |  Bin 0 -> 40200 bytes
 iodide.master.fonts/KaTeX_AMS-Regular.woff2     |  Bin 0 -> 33188 bytes
 iodide.master.fonts/KaTeX_Caligraphic-Bold.eot  |  Bin 0 -> 19836 bytes
 iodide.master.fonts/KaTeX_Caligraphic-Bold.ttf  |  Bin 0 -> 19588 bytes
 iodide.master.fonts/KaTeX_Caligraphic-Bold.woff |  Bin 0 -> 12136 bytes
 ...
 105 files changed, 128941 insertions(+)
Couldn't push the build to github.com/iodide-project/master.git:master
failed to deploy
```

Nothing notable seems to have changed in the repository since this started happening: https://github.com/iodide-project/iodide/commits/master

Re-running the build reliably reproduces the error though, so it's not just an intermittent.

Suspected causes:
* @mdboom needs to refresh his credentials
* Some issue with travis deploy (but there's nothing on the status page about it: https://www.traviscistatus.com/)

@mdboom -- can you take a look next week? (I don't think this is urgent)

**Comment by hamilton** [comment]
It appears that the deploy step is passing now. Not sure if @mdboom did anything or if it was something relating to Travis CI just working all of a sudden for no clear reason.

**Comment by mdboom** [comment]
Great!  I did nothing, as I didn't have a chance to look at this yet.  :)
