### ISSUE TITLE
"run all in presentation mode" not working for url=

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#482]
Steps to reproduce:

1. open a notebook made via dev
2. try adding `?url=?url=https://gist.githubusercontent.com/hamilton/5b0c4dd281b8a11c24272fd99fb0971a/raw/f95227cb44bbaded9b4bddebc65276deb53b19ca/default-presentation.html` to the end
3. see that it does indeed open in presentation mode, but it does not run all the cells.

**Comment by hamilton** [comment]
This is actually a cleaner representation of the problem: https://iodide-project.github.io/master/?url=https://gist.githubusercontent.com/hamilton/5b0c4dd281b8a11c24272fd99fb0971a/raw/f95227cb44bbaded9b4bddebc65276deb53b19ca/default-presentation.html

**Comment by imshubhamsingh** [comment]
@hamilton I've looked into the issue and from what I see that the `evaluateAllCells` is never run after the import of notebook. I've a way to solve this issue.

**Comment by hamilton** [comment]
Thanks for the PR @imshubhamsingh - going to close this.
