### ISSUE TITLE
Add support for dynamically loading CodeMirror syntax highlighters

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#495]
When a new language is loaded via the `addLanguage` API (as being developed in #489), we'll need to dynamically load the syntax highlighting definition for that language over the network.  There is a [codemirror addon](https://codemirror.net/demo/loadmode.html) for this that hopefully will do the trick.

**Comment by bcolloran** [comment]
Oh, this is very cool. It doesn't seem like it would be too difficult to implement. Nice find!
