### ISSUE TITLE
implement proper "prod" builds

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#499]
I haven't looked into this in detail yet, but it seems like we're at the poing where our env=prod build environment would benefit from all the standard JS build best practices-- minification, uglification, tree-shaking...

@wlach @hamilton do you have any thoughts on this? I've never really don't it before. I have the sense that this might be a good first project for someone that know JS build stuff well, but i'm not really sure how complex it is in general, so i don't really know

**Comment by hamilton** [comment]
Couldn't agree more - let's put it on the agenda for the internal meeting this week. I don't think this is very hard to put together with webpack, but there may be some small quirks we'll have to figure out.

**Comment by hamilton** [comment]
We've done a lot of this already, I think - using uglify has cut our prod bundle size down, and there is more savings to be had that we should pursue for both this and the server bundle.

**Comment by bcolloran** [comment]
yup. we also need to set `NODE_ENV=production` for our prod builds to clear some kind of redux warning

**Comment by bcolloran** [comment]
i think our current set up satisfies this in many way, and this is very stale. can file more specific issues if needed.
