### ISSUE TITLE
[meta] app message next steps

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#502]
after #501 -- App messages need some work. There is an MVF action in place, but:
- rather than passing an html string, maybe app messages should be objects with type props that specify how they will render?
    - in this case, app messages should probably not `dangerouslySetInnerHTML`
- app messages should pop a snackbar in the top left corner with a "more" link that opens the app message pane
- create a snackbar component to capture app messages. For the snackbar, app message objects should probably have both "short message" and "details" properties or something like that, the short message being used in the snack bar and as the title in the app message pane, and the details being show only in the app message pane.
- the styling is adequate for now but basic. if someone has a vision for how this should look once we figure out the rest of the functionality, they should have at it.

**Comment by hamilton** [comment]
@bcolloran I believe we've covered the last 3 points here for now, yeah? I'd be in favor of closing this and created a fresh thread on app messages given #617 just landed.

**Comment by bcolloran** [comment]
wfm, migrated the last remaining bit to #643
