### ISSUE TITLE
side panes should push over the cells instead of overlaying

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#520]
The UI should be a bit closer to Slack's side panes.

**Comment by djbarnwal** [comment]
@hamilton Side panes are of fixed size (575px) as of now. Do you think it would be a good feature addition to make their width dynamic by adding a draggable cursor on left side of the pane?

**Comment by bcolloran** [comment]
Draggable would be great @djbarnwal.

The other thing we've discussed or setting the side pane to be a bottom pane depending on overall window width. Maybe a media query or some js that does a vertical split of the window is less than 1200 or 1000 px wide (not sure about the exact threshold). You could look into that too if you wish.

**Comment by hamilton** [comment]
Ah, missed this before commenting on your PR. Yes, if you think making the width somewhat dynamic would be great. I think we should avoid allowing users the full width since from experience someone may accidentally drag their pane too far one way and wonder where their content went. Maybe we can give users something like 50% of the screen real estate - 20% or so, or replace those percentages with values that feel right.
