### ISSUE TITLE
change the state prototypes for cells to include a "pinned" key-value pair

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#525]
Part of #521. Maybe this is a pin id so we can preserve the pin order - @bcolloran we can either do this or just a boolean, any thoughts here? If we don't preserve pin order, we can preserve actual cell order.

**Comment by bcolloran** [comment]
i think the way to do this is to have a `pinnedCellId`, and to render a full second copy of the cell in the side/top pane. I don't think cell order should be affected, can you explain more about what you're thinking?

**Comment by hamilton** [comment]
I mean preserving the cell order in the side pane itself, not in the `cells` part of the store. A pinned cell wouldn't have anything necessarily change in the main cell view (perhaps a little icon that shows it is pinned or something). I think there's a question of what users would expect the cell pinning order to be in the UI - the order in which it was pinned, or the order in which it appears in the notebook? The latter is nice because it still ties the pinned cells to some sense of vertical coherence of the notebook, but the former might also make sense from an ergonomic point of view (I expect the pins to be in the order in which I pinned them).

I don't have a strong preference one way or another, but I do think it would be sensible to select for the more verbose one, state-wise (that is, going with the one that would allow us to preserve the pin order even if we end up not going that route) in case we want to make this flexible for users down the line.

**Comment by bcolloran** [comment]
i'm still not sure what you mean, i think we're understanding this feature differently? I was thinking that you can only ever pin a single cell (and for that matter, maybe only the editor of that cell), in which case pinning order is not even a thing.

**Comment by hamilton** [comment]
Yep, sounds like we are not on the same page about this and we should
probably discuss further before anyone jumps in. I’d argue that one pinned
cell is not enough to do real work (it certainly would not have been with
my recent work using iodide), and I’m not sure why we should limit users to
one. I agree that we should only have the editor though.

**Comment by bcolloran** [comment]
didn't you manage to get that recent real work done with 0 pinned tabs? ;-) we can figure it out tuesday :-)

**Comment by hamilton** [comment]
Tbh I deserve a medal for finishing that. If only you knew how much
expletive-filled scrolling I endured :)

**Comment by bcolloran** [comment]
deprecated while we consider #593
