### ISSUE TITLE
Code plugin cell not working

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#534]
The code plugin cell in #519 and the current contents of that branch (`code-plugin-cell`) work perfectly, though once merged into master, it seems to be broken.  Some conflict with some feature that was merged in the meantime, I guess...?  @bcolloran: I'm filing this because maybe the solution will be immediately obvious to you, otherwise I'm happy to continue digging tomorrow.

### What I Did

Press 'L' to create plugin cell.  Insert:

```
{
  "languageId": "py",
  "displayName": "python",
  "codeMirrorMode": "python",
  "keybinding": "p",
  "url": "https://raw.githubusercontent.com/iodide-project/pyodide-demo/master/pyodide.js", 
  "module": "pyodide", 
  "evaluator": "runPython"
}
```
Shift+Enter to evaluate the cell.

### What I Expected

"Python plugin ready", and then the ability to create and run Python cells.

### What Happened 

Seemingly nothing -- nothing interesting in the console.

**Comment by bcolloran** [comment]
huh. ya confirmed, i'll take a look right now.

**Comment by bcolloran** [comment]
(from gitter, in case you miss it there)
"""@mdboom , can you try adding the line "pluginType": "language", to your plugin definition?
i think that might be the problem
(tho an error should be popped in the case of a missing plugin type)"""

apologies, the plugin cell UI is really bad... it should probably be a bunch of inputs that you have to fill in based on the plugin type

**Comment by mdboom** [comment]
Aha, that did it.  Closing this, because it isn't really "broken".  Of course there's lots of UI things we can do given infinite time :)
