### ISSUE TITLE
Next cell type is 'js' if a 'py' cell throws an exception

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#539]
The expected behavior is that when you run a Python cell, the next cell that gets created should also be a Python cell.  However, if that Python cell throws an exception, the next cell is a Js cell.

(More generally, there's probably more thinking to do about how to decide what kind of cell to create next -- do we instead want some sort of UI element to select the "default new cell type".  Not sure...  But maybe there's more than one way to tackle this bug.)

**Comment by bcolloran** [comment]
huh, strange that it changes type on error.

maybe a nice behavior would be to use the type of whatever cell is above the cell being created, to kind of capture the case that if you're inserting a cell in the midst of other cells, you are likely to want a cell of the type in that part of the notebook.

in any case, it should surely not switch cell types just b/c an exception is thrown

**Comment by mdboom** [comment]
Yeah -- I actually haven't deeply thought through the design tradeoffs of different options.  We should just have something that's non-surprising.
