### ISSUE TITLE
plugin helper scripts should return a promise, plugin cell should update based on promise

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#546]
@mdboom  @hamilton 
any more thoughts on details of how this should work?

**Comment by hamilton** [comment]
I will have a PR in the next day or so demonstrating how we might handle making the cell execution w/ plugin cells feel synchronous. This will require some tradeoffs I'll bring up in the PR.

**Comment by hamilton** [comment]
Closing this due to the merging of #554
