### ISSUE TITLE
Declared variables pane doesn't play well with pyodide atm

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#552]
Pyodide fills the global namespace with thousands of things.  This, understandably, slows down the declared variables pane.  I think getting pyodide to not pollute the global namespace so much might involve a major refactoring of emscripten, unfortunately.

In the meantime, there are some things that might help -- this is an issue to brainstorm and get feedback from @bcolloran and others.

Most of the objects start with an underscore.  I think if the declared variables pane ignored everything that started with an underscore, we'd get 90% of the way there.  Might be surprising, of course.  It's a convention for private in Python, but I don't know if that's also true in Javascript land.  Maybe a user configuration?

**Comment by hamilton** [comment]
Underscores are _kind of_ a convention with JS, and the private story is just a lot [more complicated than in Python overall](http://2ality.com/2016/01/private-data-classes.html). I would be in favor of assuming that any programmer following the underscore convention should have those vars hidden in the declared variables.

**Comment by mdboom** [comment]
With https://github.com/iodide-project/pyodide/pull/25, pyodide no longer dumps 1000's of things in the global namespace.  It only sets one thing: `pyodide`, from which you can get to everything else.  I think with that this can probably be closed.  It doesn't have to be the case that iodide scales to 1000's of unorganized things at the top-level ;)

**Comment by hamilton** [comment]
Cool, will close. I suspect this will be a problem with other languages as well down the line.
