### ISSUE TITLE
prevent running cells while another cell (that we control) is running

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#562]
re #554 -- we now have a good solution for preventing async cells from racing during run all, next step is to prevent races when manually `ctrl+enter`-ing through an NB.

@hamilton can we `.then` functions onto a global promise object or something (like what you do with the local promise obj within `evaluateAllCells`), or do we need a global lock somewhere, or etc?

**Comment by hamilton** [comment]
@bcolloran I might suggest to tackle `iodide.expectResolution` / `iodide.resolve` first, so that this particular issue is a bit easier to work through on a low-surface-area example (and not the full pyodide example, which has been a bit difficult)
