### ISSUE TITLE
plugin cells should update all editors when codemirror mode loader finishes

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#563]
currently:
- when you open a notebook with python cells, at initial open the py cells don't have syntax highlighting
- when you run the py plugin cell, syntax highlight does not take effect immediately
- you have to change the cell mode to something other than py then back to py to get the highlighting.

obvi the highlighting should show up immediately, so the editors require some kind of refresh.

**Comment by mdboom** [comment]
Good find.  I was only testing on "fresh" notebooks, so never saw this.
