### ISSUE TITLE
make sure language plugin cells surface any errors from any of the steps

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#564]
If the Promise rejects, we need to make sure there is worthwhile, debuggable text of some sort that bubbles up into the right output handler.

**Comment by bcolloran** [comment]
@hamilton @mdboom did you guys sollve this one or is ther more to do here?

**Comment by mdboom** [comment]
I think this is solved.  For Pyodide, it converts the Python exception to a Javascript exception and throws that.  So as far as Iodide is concerned it's all "pure Javascript" and it works.
