### ISSUE TITLE
If a promise errors, it isn't possible to correct and re-run the cell

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#576]
### What I Did

Create a promise-returning cell with a typo:

```
fetch('iodide.dev.css').then(response => response.txt())
```

Running the cell resolves the promise and displays the exception / traceback.

However, when I corrected the typo (`txt` -> `text`) and reran the cell, the same exception was displayed again.

**Comment by hamilton** [comment]
Yes, this is indeed a bug! Thanks for filing.
