### ISSUE TITLE
need better find/replace functionality

### ISSUE THREAD

**Issue by jtg567** [iodide-project/iodide#579]
I'm on a Windows machine.

### What I Did

highlighted a variable name in edit mode and hit CTRL+F

### What I Expected

the find/text search bar would come up with the variable name pre-populating the textbox

### What Happened 

the find/text search bar came up with the text that was there previously, if any

**Comment by hamilton** [comment]
Thanks for the issue @jtg567!

@bcolloran seems like we should take a look at what options CodeMirror has for this kind of stuff. We're also running up against this for find-and-replace, I think.

**Comment by bcolloran** [comment]
the "official" f/r functionality in codemirror is pretty primitive:
http://codemirror.net/demo/search.html
https://codemirror.net/2/demo/search.html

maybe we could build off the f/r functionality here. it seems a little better:
https://discuss.codemirror.net/t/enhanced-search-and-replace/943
http://plnkr.co/edit/LEEZf2Vt9U6PASRGpsrt?p=info

none of this addresses f/r across multiple cells tho (yet _another_ inducement to move back in the direction of a single editor... )

**Comment by bcolloran** [comment]
@hamilton  now that we have a single editor on the JSMD branch, this issue is waaaay easier to tackle

**Comment by bcolloran** [comment]
finally fixed via #2117!
