### ISSUE TITLE
md headers need more spacing above them

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#581]
This is applicable to the h2-6 headers, primarily. A bit more space above them would make section parsing much easier on the eyes.

<img width="920" alt="screen shot 2018-04-26 at 3 20 46 pm" src="https://user-images.githubusercontent.com/95735/39334870-6d870ca2-4965-11e8-913b-5510d36614e1.png">

**Comment by bcolloran** [comment]
fixed in iframe-2
