### ISSUE TITLE
history problems for NBs that start in report view

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#588]
two sub-issues:
- [ ] for NBs that open in report view (and thus automatically run all), history items are not initially filled with the evaled text
- [ ] when you click on the history item, the evaled text appears, but the line numbers are broken (hard to see, but they overlap with the code

![peek 2018-05-03 16-19](https://user-images.githubusercontent.com/2380975/39607077-c5d5a5b6-4eed-11e8-8add-a75f171446ee.gif)

line numbers (light grey) on top of code:
![image](https://user-images.githubusercontent.com/2380975/39607169-56bfe172-4eee-11e8-836f-36fa53e53027.png)

**Comment by hamilton** [comment]
Ah, I had actually noticed this before that recent PR. Happy to take this
on.

**Comment by bcolloran** [comment]
no longer relevant on iframe-2
