### ISSUE TITLE
[META] moving computation to an iframe, and UI changes

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#593]
i've discussed the idea of moving user code evaluation out of the main window JS scope and into an iframe with a few folks, this issue is for discussing that idea and coming up with a plan for implementing it.

The idea is to split the app into two components:
1) the "editor" component, which will have the editor and the rest of the Iodide app functionality (saving/exporting/handling gists, etc), and which will pass messages containing code to be evaled to:
2) the "report/evaluator" component, which will receive messages from the editor, and which will be an iframe in which the code is actually evaluated.

We'd also change the UI from having the code input and outputs inline to side-by-side in independently scrollable panes (but which could have linked scrolling by default). The UI i'd like to aim for would be like google docs comments, where the output from each cell / chunk of code would appear in kind of a "comment bubble" that would point back to cell that generated it, and that running a cell/chunk would scroll the corresponding output bubble into view (but without making your editor jump around, as is the case in Jupyter and Iodide currently)

Here are a few of the problems that we'd be trying to address with this change:

- scrolling all the time -- as we've learned, the workflow in Iodide has turned out to be a bit different than that in Jupyter, where outputs are always returned from cells, and it makes sense to have e.g. images apper below the cell that created them. Because we are trying to make DOM-based workflows accessible, and because these workflows often involve *manipulating* existing dom elts which may have been created as the output of another cell (whether a code cell or an MD cell), we want to allow editing and execution of a cell while looking at the output of another cell. Side-by-side view will allow independent scrolling of the Report and Editor panes, enabling this workflow

- security? -- I'm not an expert in browser security, but i think we get some security advantages from having the code evaluation confined to an iframe. IIUC, this would mean that evaling malicious notebook code could in the would only be able to pass messages back to the editor iframe, but wouldn't directly be able to use the Editor components methods to e.g. talk to a server on localhost or on the web to write to your github account or filesystem. So as we begin to think about talking to systems outside the browser, this should buy us an extra layer of protection

- js scope hygiene --  we'd have a smaller amount of helper code in the report/evaluator app, and the editor (which would own the JSMD, saving/restoring, etc) couldn't get blown up by user code, and if a user blows up their Report component, the editor componemt might be able to refresh it

- css hygiene -- right now, styling the report view sucks, b/c the report view css is necessarily mingled with the css for the whole app (since everything having to do with cells appears in-line). having a separate css universe for the Report component would allow us to simplify and streamline our CSS a lot

- potential path towards not blocking the editor -- beyond having the Report component live in an iframe, we could experiment with popping it out in another window, which would allow the editor and the evaluator to run in separate threads (this is what the Carbide notebook did). Figuring out message passing to an iframe evaluator would be a step towards this.

**Comment by hamilton** [comment]
We talked over the last week w/ all the core contributors about this, and everyone appears to be in agreement that from a UX perspective, getting away from the current cell-based paradigm feels like a step in the right direction.

This is an enormous amount of work, however, which will be managed in an upcoming branch. Thus all PRs touching other parts of the app will have to target that branch and not `master` (excepting bug fixes), as will all of our upcoming PRs working toward this vision.

**Comment by bcolloran** [comment]
closing this issue in favor of a host of more specific issues
