### ISSUE TITLE
Firefox bookmark hotkey not functional on iodide page

### ISSUE THREAD

**Issue by jtg567** [iodide-project/iodide#605]
MASTER

### What I Did

tried to bookmark the page by pressing CTRL+D in Firefox

### What I Expected

the bookmark dialog to come up and the star in the awesome bar to fill in

### What Happened 

nothing

### (OPTIONAL) notebook that reproduces bug 

https://strategy-and-insights.mozilla.com/shield-studies/index.html

**Comment by hamilton** [comment]
You are the king of shortcuts my friend! We have taken `ctrl+d` at the moment for opening the "declared variables" pane, though clearly this is colliding in a way that isn't attractive. We are using Mousetrap to do this, but clearly we need to rethink how we're using the keybindings.

Were you in editor mode when you used `ctrl+d`, or just the top-level presentation view?

**Comment by hamilton** [comment]
@bcolloran we could approach this in two ways:

- let's just get rid of the declared variables / history pane keybinding
- let's disable ALL iodide keybindings in presentation mode

Thoughts?

**Comment by jtg567** [comment]
@hamilton I was in presentation mode

**Comment by hamilton** [comment]
Great - easy fix. Thanks for the issue!

**Comment by bcolloran** [comment]
thanks @jtg567 for the issue, thanks @hamilton for the fix!
