### ISSUE TITLE
Easy way to load local notebooks

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#613]
The current flow to load locally stored notebooks is very tedious. You have to open the root URL, toggle the menu, open Notebooks submenu and then select your notebook.

I am thinking something along the lines of `rooturl.com/?local=<notebook-title-hyphenated>` Opening a URL with `?local=example-notebook` should open the notebook from localStorage with the title Example notebook. Once opened, the URL will be saved in the browser's history for easy loading.

An alternative could be to show saved notebooks on Iodide Landing Page (similar to Top Sites on Firefox New Tab)

**Comment by bcolloran** [comment]
hmm i'm torn on this. i think it would be ok as a short term workaround, but we want to move away from localStorage in general, see #351, which of course is why we're working on getting the server-side saving to work. 

i guess we could add it in the short term with the understanding that we'll be wanting to pull it back out quite soon. but the other alternative is to try moving to a file-based workflow when working with local files.

ultimately, localstorage is a dead end, so we don't want to put too much energy into supporting it.

@hamilton  any thoughts on this?
