### ISSUE TITLE
We need stable file names not tied to notebook titles

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#616]
This is a real usability pain right now. It's nice to be able to title one's notebook, which updates the tab title in your browser, and also can provide some useful text for someone opening your notebook to verify the thing is what it says it is. But we're tying the filename to the title bar, and I think this a real pain. For one thing, if I change the title, I change the file name. These are semantically separate in pretty much all systems out there (google docs, jupyter, you name it), and we should be doing the same.

**Comment by bcolloran** [comment]
obsolete given the server and the coming rethink of archive export
