### ISSUE TITLE
Including images in notebook for export

### ISSUE THREAD

**Issue by DevinBayly** [iodide-project/iodide#621]
It would be very helpful if there were a mechanism for including images used in markdown cells with the rest of the notebook at time of export. 
 
### Suggested approaches

@bcolloran  suggests placing the images online and supplying a src link, but @hamilton has suggested that we try to save them in the environment variable. I understand that there's a way that we can encode images as base 64, and then create an Image with its constructor (method detailed here https://stackoverflow.com/questions/2395765/store-images-in-javascript-object) perhaps this is related to the environment freezing method? 

@bcolloran also mentioned that perhaps the 'file cell type' may play a role in making this feature a reality.

**Comment by bcolloran** [comment]
to clarify: putting the images online and linking to them is a workaround that can be used for now. we definitely want to support embedding images directly into jsmd as base 64 strings, an.d we want this to be as simple as drag-n-drop or copy/paste

**Comment by hamilton** [comment]
This will get resolved once we have file upload & project exporting implemented, so the unit of export is a directory w/ notebook(s) & uploaded files (including images).

**Comment by bcolloran** [comment]
obsolete
