### ISSUE TITLE
backups/autosaves need to not save frozen environment vars, or localStorage cries out

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#625]
```
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached
notebook-reducer.js:121:6
notebookReducer
notebook-reducer.js:121:6
reduceReducers/</<
reducer.js:16:16
reduce self-hosted:358:27 reduceReducers/<
reducer.js:15:4
validatedReducer
create-validated-reducer.js:20:26
dispatch
createStore.js:165
S/</</<
redux-logger.js:1:7804
createThunkMiddleware/</</<
index.js:14
bindActionCreator/<
bindActionCreators.js:3
Page/<
page.jsx:47:6
```

**Comment by hamilton** [comment]
yikes, of course it does!

**Comment by bcolloran** [comment]
:-)

yes, poor FF localStorage called out in pain as i worked on some demo notebooks; luckily i was able to sooth it by increasing the quota. But Chrome localStorage doesn't allow that, so it isn't even willing to talk to me at this point.

**Comment by hamilton** [comment]
I think this exposes something of a weakness of using any system that limits file size. Some class of user is going to encounter this with Github Gists as well - isn't the cap there 25mb?

And re: repositories, Github will send an angry email to you if your repo is > 1gb, and especially if we're saving copies of notebooks in the future, I can see someone maxing that out in an hour session with, say, a 25mb frozen state notebook. 

For all the faults of having a local filesystem connector, it's the single most flexible form for users wanting to experiment and try out big things, so I hope we don't discount putting together a connector for that soon.

And of course, we could just limit the size of the frozen state, but we're still going to brush against these constraints if we build more around anyone else's system.

**Comment by bcolloran** [comment]
@hamilton yea this is a really important point, and one of the leading reasons that we'd want to build our own server infrastructure. in general, bundling data and workflows around data are things we'll need to think more about. eg, bundling data directly within JSMD is only one of the workflows we need to consider -- we'll also want better APIs/workflows for saving data outside of JSMD (as demonstrated by devin's headaches with his brain data). maybe that "git for data" project at mozilla (the name of which i am blanking on) would be helpful for that.

regarding the filesystem connector: increasingly, i think the path forward here is an electron app. IIUC, once we have the two pane iframe/message passing stuff set up, i think it should be possible to host editor and report frames in webviews that run in separate processes (addressing one of our other big architectural question marks), and from an electron app you'll be able to save jsmd to the file system as you wish, unlocking arbitrary filseystem workflows. And this workflow will be overall less frictiony i think (simpler to install an electron app than some kind of npm thing, don't have to fiddle with localhost, etc).
