### ISSUE TITLE
idea: something to identify variables used in a cell

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#628]
[this is just an idea i want to capture, and is low priority]

on about a zillion occasions, i've written code in jupyter where i'm rapidly prototyping things in the global namespace, but after a while of copying cells and tweaking them, i go back and take the code within a cell and wrap it in a function so that i can parameterize it.

in jupyter, and also in iodide, it would be neat to have a little macro thing that takes a cell  AST analysis to determine what variables the cell uses -- i've found that figuring out what a cell uses by inspection is quite error prone. this would be useful for two things 
(1) taking the code from the cell and wrapping it in function (so that eg it can be used as a callback at the end of a promise chain)
(2) figuring out what variables a cell needs so that they can be frozen into the environment, and the cells above can be skipped (for loading in report view)

we could make little "macros" around these ideas -- generating new code cells with the function-wrapped version of a cell, or generating a code cell to freeze/load the identified variables

**Comment by hamilton** [comment]
We don't have cells anymore, so this is less of an issue now.
