### ISSUE TITLE
perhaps for now we should have it be iodide-project.github.io/alpha/

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#630]
Thinking about ways to make this clear that we're in early stage. We can keep `master`, but could we easily also add `alpha` for some cases?

Are there problems with this bit of branding?

**Comment by bcolloran** [comment]
fine with me, but it might not matter if we're going to switch everything to iodide.io anyways (to solve the pyodide ublock issue), right? b/c in that case, no one will see the references to iodide-project.github.io? or am i misunderstanding how that will work?

cc @mdboom

**Comment by hamilton** [comment]
I think it's a matter of semantics. Do we want `iodide.io/alpha` to put people into the notebook, while we reservre `iodide.io` for some splash page of some kind, or a way to get people into the funnel? Perhaps `iodide.io` redirects to `iodide.io/alpha` as a starting point.

**Comment by bcolloran** [comment]
i don't have strong feeling at all on this. if you have a vision for what you think this flow should be and you want to put together that splash page, i'm surely happy to let you take point on that

**Comment by hamilton** [comment]
This issue is stale at the moment. Going to close it and we can revisit later once we've thought a bit more about builds, etc.
