### ISSUE TITLE
option to change "edit" to "view source"

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#632]
Some notebook-consumers are pretty terrified to see a notebook in presentation mode w/ an "edit" button. They think they're saving something back to a server when they click on it and change something. Perhaps it would be smart that if a notebook is in some environment (server where user doesn't have access to notebook, single-page version, etc.) where they cannot really save edits easily, we don't use the word "edit"

Seems small, but I think this rough edge is pretty important.

**Comment by bcolloran** [comment]
i'm down with "view source", but per #352 i also like "report"/"explore".

anyone else have thoughts?

**Comment by bcolloran** [comment]
fixed in iframe-2
