### ISSUE TITLE
[meta] iodide.io redirect

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#639]
@mdboom @hamilton @wlach -- i saw there was some discussion on gitter about the iodide.io redirect. let's capture all the stuff we'll need to do here and i'll get the ball rolling

1) now that netlify is in play, what should iodide.io point to?
2) do we want to do any subdomain redirects -- e.g., would it be convenient for pyodide.iodide.io point somewhere that would make it easier to serve the pyodide files?
3) which iodide files will need to point at different locations? i think for iodide, maybe just the webpack config has the URL info. are there other other files, particularly for pyodide?

anything else we need to think about to make this transition?

**Comment by wlach** [comment]
For (1), we should point iodide.io to netlify's dns servers (which netlify can give you when you set up a custom domain). Not sure about the rest, that sounds like @mdboom's area of expertise.

It looks like the slightly longer term game is probably to deploy via heroku instead of netlify or other static hosting solutions, so preferably we wouldn't sink too much time into solutions specific to them.

**Comment by bcolloran** [comment]
>  (which netlify can give you when you set up a custom domain)

i had thought someone did this already?

**Comment by mdboom** [comment]
I set up a `pyodide.netlify.com` domain just to play with it, but I don't think that's ever going to be something public.

I think the iodide URL is in the webpack config, so would just need to be updated in one place.  Pyodide likewise has it all in one place.

I can't figure out how to make netlify serve different repos at different paths, only at different subdomains, so what we do now with github pages with `/master`, `/dist` and `/pyodide` will have to change to use subdomains -- unless I'm missing something.  That's less ideal, but we can probably work with it.

**Comment by mdboom** [comment]
No, I don't think so.  That should do it.  Let me know when you've made the changes and I can check from this end.

**Comment by bcolloran** [comment]
updates:
so i forgot that at this point we're building our master branch (iodide-project/master), pyodide (iodide-project/pyodide), docs (iodide-project/docs), and examples (iodide-project/iodide-examples) to separate repos.

there's an easy way to get _forwarding_ to work such that `iodide.io/X` _forwards_ you on to `iodide-project/X`, but it doesn't transparently use `iodide.io`

it looks like we might be able to get what we want by putting CNAME files in our repos, a la:
- http://www.curtismlarson.com/blog/2015/04/12/github-pages-google-domains/
- https://medium.com/@connorleech/launch-a-website-with-a-custom-url-using-github-pages-and-google-domains-3dd8d90cc33b
- https://medium.com/@Tnylnc/tnylnc-how-to-set-up-github-pages-with-google-domains-83bd5a4fbc5c

i think (tho i am not 100% sure) that this would have a couple consequences
- i think we'd need to use subdomains for the CNAME thingy rather than paths
- i think we would lose the ability to serve pages from `iodide-project.github.io/{whatever}` in parallel with `{whatever}.iodide.io`, so we'd need to change all of the links in existing notebooks all at once

i might be doing this just completely wrong. @mdboom @hamilton @wlach any thoughts?

**Comment by mdboom** [comment]
Does it work if you make a project called iodide.github.io, enable GitHub
pages on it, and putting the CNAME file there?  I think that's how
matplotlib.org works.

**Comment by bcolloran** [comment]
mmm yep, np i can do that. iiuc -- in that case, would we need to change our build system / procedures to have everything we want to serve (master, pyodide, docs, examples) mirrored to directories inside of the `iodide-project/iodide.github.io` repo going forward? but then the legacy urls pointing at iodide-`project.github.io/{whatever}` won't break? is that the idea?

if this is right, i'm happy to set up `iodide-project/iodide.github.io` with sub dirs
- `/master`
- `/pyodide`
- `/docs`
- `/examples`

but i'll surely need some help with the travis CI build system stuff (read: i'll need someone else to jump in and handle that, b/c i haven't figured out how it works)

@mdboom does this sound like the plan you have in mind? again: out of my depth, happy to adjust! :-) thanks!

**Comment by bcolloran** [comment]
oh and i guess we'll need 
- `/dist`
also

anything else i'm missing?

**Comment by mdboom** [comment]
I'm pretty sure if you set up the `iodide.github.io` project with just the CNAME (and any other top-level content we want to build later), then the existing `/master`, `/dist` and `/pyodide` repos will automatically show up at `http://iodide.io/master` etc.  No need to add those to the `iodide.github.io` repo.  This is what I set up for matplotlib.org, and it works quite well: there's a `matplotlib.github.com` repo that serves the main content, and it has the CNAME file and the main domain points to it, but there's a separate repo at `matplotlib/devdocs` that shows up automatically at `http://matplotlib.org/devdocs`.

The beauty of this approach is that we can (and should) update any existing URLs from `iodide-project.github.io` to `iodide.io`, but if we forget to update any of them, or people have old notebooks floating around, they will continue to work.  (This is why I think the move to netlify is riskier -- it would require non-backward-compatible changes to the repo contents...)

**Comment by bcolloran** [comment]
oh rad. sounds good, surely a cheap experiment to perform in either case -- i'll do that shortly. thanks @mdboom !

**Comment by bcolloran** [comment]
hey! this seems fixed! plz file additional issues if needed
