### ISSUE TITLE
point any final resources from iodide-project.github.io to iodide.io

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#644]
The content currently being served from iodide.io is pointing to iodide-project.github.io, but we're actually getting errors from all those resources right now. 

Changing those resources to point to the iodide.io equivalent fixes the issue. I've updated all the demo notebooks, for instance, and they work fine.

The webpack build is broken, however - https://iodide.io/master/ doesn't work right now. BUT (non https) iodide.io/master DOES work. The error appears to be that the js / css source uris are not allowed, and I'm guess its because the domain differs and https isn't thrilled.

I believe we will have to change the configuration in `webpack.config.js`, but I am not sure if there's something on the travis end that'd also get messed up if I changed it.

Is this the right way of thinking about this?

**Comment by mdboom** [comment]
I think this is resolved now.  Let me know if not, @hamilton.  We could (but probably shouldn't) update our tagged releases to the new URL.  I think it's best if those are left on the old URL (which, of course, is still public and still available).

**Comment by hamilton** [comment]
Yep, this seems to work now - thanks for reviewing my PR / merging!
