### ISSUE TITLE
[META] direct users to iodide.io for saving etc when viewing exported notebooks hosted at a 3rd party location

### ISSUE THREAD

**Issue by djbarnwal** [iodide-project/iodide#648]
This is a follow up of Issue #633. Before we have the server ready and deployed, we need to discuss how we are going to handle server-side features for notebooks which are locally hosted or hosted on a different origin than iodide.io

These are two potential ways to go about this - 
1. Allowing login from any origin
This might be particularly bad considering the security as we would have to allow CORS for all domains. More on this can be found on this [SO thread](https://stackoverflow.com/questions/19322973/security-implications-of-adding-all-domains-to-cors-access-control-allow-origin). There is a difference of opinion with this implementation. Some consider it to be safe if correctly implemented while others don't. Maybe a security expert can help us out here.

2. Creating two versions of the notebook
We can create two versions of Iodide notebook. One for iodide.io and the other for all other origins. We can create a mechanism for funnelling users into iodide.io if they want to implement server related features.

**Comment by hamilton** [comment]
Yep, this sounds right @bcolloran.

**Comment by bcolloran** [comment]
stale, will need a rethink when the time comes
