### ISSUE TITLE
cell cut and paste

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#65]

**Comment by djbarnwal** [comment]
Hey @bcolloran I would like to give this issue a try.

**Comment by bcolloran** [comment]
Go for it @djbarnwal. Are you familiar with how this works in Jupyter?  We want to achieve similar functionality, but maybe we can do a little better.

all of the following will only work in command mode. I think the objectives for now will be something like:
- `ctrl+x` should "cut" the currently selected cell
- `ctrl+c` should "copy" the currently selected cell
- `ctrl+v` should "paste" the cell in the clipboard _below_ the currently selected cell

Juypter also has the possibility of highlighting multiple cells and cut/copy/pasting them. You can work on that too if you want, or just try to achieve the above objectives, but even if you want to stick with the smaller case, try to see if you can write code that will be flexible enough to accommodate the possibility of handling multiple cells.

Please let me know if you have any questions or want advice about how you might implement this. I have some ideas that you I could offer if you get stuck.

**Comment by djbarnwal** [comment]
@bcolloran Yes, I am familiar with Jupyter's working. I will try to incorporate a similar behaviour in iodide with improvements wherever possible. I'll ping you if I stuck somewhere in between :-)

**Comment by djbarnwal** [comment]
@bcolloran I have successfully implemented a basic copy and paste feature on a single cell which can be extended to cut-paste too. I am about to implement this to multiple cells. But before I start, I need to make sure that having multiple `selected` cells does not break anything. I know that `cellUp` and `cellDown` feature depends upon the currently selected cell (and it looks more logical to support multiple cell shift as Jupyter does). But a more thorough check would be required. 

Would it be OK if I send a PR for selecting multiple cells (with the existing features working) first and then follow it up by sending a PR for Cut-Copy-Paste? Moreover, do you want me to add some additional features to any part of this apart from what Jupyter offers?

**Comment by bcolloran** [comment]
@djbarnwal that's great!!

i think that for multiple cell selection, we should actually introduce a new property in the state for each cell, perhaps we could call it "highlighted" or something like that. I'm quite sure that adding the possibility of having more than one cell in the `selected` state will introduce problems -- the entire app is built around the idea that only one cell is in `selected` state at a time.

See `newCell` in `state-prototypes.js` -- that is where we would add the new "highlighted" property. Lmk if you want any more advice, and thanks! :-)
