### ISSUE TITLE
Add a simpler way to add HTML to a Notebook

### ISSUE THREAD

**Issue by jaredkerim** [iodide-project/iodide#652]
Right now it seems like the only way to add some HTML to a notebook is to create a Raw cell, add some HTML literal to it, then convert it to a Markdown cell, then hit the 'run cell' button and finally it turns into some HTML.  This took some finagling to discover and get working, it would be nicer if there was just an HTML cell type that I could edit and would immediately turn into visual HTML.

**Comment by bcolloran** [comment]
@jaredkerim fwiw: you can skip the raw cell step and add HTML directly into a MD cell (without the raw->MD conversion).

that said: we should certainly just have a pure HTML cell in addition to the MD cell. i think this is a no-brainer and an easy fix (@hamilton am i overlooking any reason why this would be a bad idea?)

**Comment by bcolloran** [comment]
@jaredkerim fwiw: you can skip the raw cell step and add HTML directly into a MD cell (without the raw->MD conversion).

that said: we should certainly just have a pure HTML cell in addition to the MD cell. i think this is a no-brainer and an easy fix (@hamilton am i overlooking any reason why this would be a bad idea?)

thanks for filing this jared!

**Comment by hamilton** [comment]
Yes thanks for filing! I think having a pure HTML cell seems unnecessary, since markdown is a superset of html, and all those steps you just outlined could just be done by writing html in the markdown cell now (that's what I do in this situation). The md cell right now does exactly what your describe - take md and return a visual HTML. One possibility is to just change the cell label name to `html / md` or something like that for clarity's sake. Unless I'm misunderstanding!

**Comment by jaredkerim** [comment]
@hamilton Yes I think making it clearer that html belongs in the md cell would be helpful becuase as a first time user it was not clear to me that there was any way to enter HTML into a cell.

**Comment by bcolloran** [comment]
@hamilton talked with adam rule the other day, he thought that an HTML cell would be easier for new users. that, jared's issue, and the fact that it's pretty small amount of work and code convinces me that we should add that cell type

**Comment by bcolloran** [comment]
jsmd recognizes an html chunk now (even tho it's just a pass thru to the md evaluator)
