### ISSUE TITLE
Enable Renovate on this repo

### ISSUE THREAD

**Issue by openjck** [iodide-project/iodide#658]
[Renovate](https://renovatebot.com/) opens pull requests when new versions of NPM packages are available. It could be enabled on this repo to improve the security of the application.

I'd be happy to help if you decide you want to do this.

**Comment by wlach** [comment]
Big +1 on this from me.

**Comment by hamilton** [comment]
@openjck sounds like a great idea! Do you need anything to make this happen?

**Comment by openjck** [comment]
> @openjck sounds like a great idea! Do you need anything to make this happen?

I don't think so. Testing would be helpful once Renovate lands, as it'll be upgrading lots of dependencies. I see the *npm test* command but if there are any other manual acceptance tests you do maybe you could point me in the right direction.

I'm not sure if/how this will be charged. I believe Renovate is free for open-source repos but they may need a credit card on file just in case. I can keep ya posted.

**Comment by hamilton** [comment]
We don't really have any manual ways of testing at the moment.

**Comment by openjck** [comment]
Just as a heads up, my availability is a bit limited for the next month as we prepare to launch Ensemble. But I'll try my hardest to find time to squeeze it in before that.
