### ISSUE TITLE
an array with a single undefined (`[undefined]`)causes an error

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#659]
Try loading and running [this notebook](https://iodide.io/master/?jsmd=%25%25%20meta%0A%7B%0A%20%20%22title%22%3A%20%22Crashes%20of%20the%20last%20few%20days%22%2C%0A%20%20%22lastExport%22%3A%20%222018-06-15T22%3A01%3A29.649Z%22%0A%7D%0A%0A%25%25%20md%0AThis%20is%20an%20iodide%20notebook%2C%20for%20more%20information%20and%20tutorials%20see%20https%3A%2F%2Fiodide.io%0A%0A%25%25%20js%0A%2F%2F%20this%20cell%20fetches%20the%20results%20of%20your%20stmo%20query%20(Crashes%20of%20the%20last%20few%20days)%0Avar%20stmoData%3B%0Alet%20url%20%3D%20'https%3A%2F%2Fsql.telemetry.mozilla.org%2Fapi%2Fqueries%2F1092%2Fresults.json%3Fapi_key%3Df7dac61893e040ca59c76fd616f082479e2a1c85'%3B%0Aiodide.evalQueue.await(%5B%0A%09fetch(url)%0A%20%20%09.then(response%20%3D%3E%20response.json())%0A%20%20%09.then((json)%3D%3E%20%7BstmoData%20%3D%20json%7D)%0A%5D)%0A%0A%25%25%20js%0A%2F%2F%20You%20can%20now%20access%20the%20results%20of%20your%20stmo%20query%20from%20the%20%22stmoData%22%20variable%0A%2F%2F%20As%20an%20example%2C%20we%20are%20going%20to%20assemble%20the%20rows%20of%20the%20query%20into%20a%20simple%0A%2F%2F%20data%20structure%0AstmoData.query_result.data.rows.map(row%3D%3EObject.values(row)))

The page will turn blank and you'll see this error in the console:

<img width="1117" alt="screen shot 2018-06-15 at 3 00 22 pm" src="https://user-images.githubusercontent.com/20569/41491255-ddd130dc-70ac-11e8-8aa5-767892e8cd35.png">

@hamilton -- this is using the new API added in #618.

**Comment by hamilton** [comment]
Yep, this is a bug.

This is pretty reproducible if a Promise returns `undefined` in an `iodide.evalQueue.await` call.

```javascript
iodide.evalQueue.await([
  Promise.resolve(undefined)
])
```

**Comment by hamilton** [comment]
Turns out the issue isn't with `iodide.evalQueue.await`, nor with promises generally, but with the dataframe handler breaking. This, for instance, causes the same issue, which is exactly what's getting passed through in the code block in the preceding comment:

```javascript
var byebye = [undefined]
byebye
```

Going to rename this issue accordingly.
