### ISSUE TITLE
Update the cell type menu options when new plugin(s) loaded

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#663]
Short summary of the bug. Please include the IODIDE version number where you found the bug - if you are just running locally (building for dev or prod) you can put MASTER

Hosted browser version https://iodide.io/master

### What I Did

after loading the python plugin, I clicked the cell type modal but python is not listed there yet.

### What I Expected

all the available cell types

### What Happened 

![image](https://user-images.githubusercontent.com/1578674/41511269-63fac034-7228-11e8-918a-205ebd0e9d21.png)

**Comment by teonbrooks** [comment]
cc: @hamilton, @bcolloran

**Comment by bcolloran** [comment]
closing in favor of #830
