### ISSUE TITLE
add URL parameter to over-ride report view

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#666]
notebooks that open in report view (and hence run-all immediately) can be difficult to debug if they have a cell that crashes. we should add an url param that can override this behavior

**Comment by bcolloran** [comment]
see `handle-url-query.js`

**Comment by iFlameing** [comment]
can you explain the issue I didn't get it regarding the param you mention.I am new to this project.

**Comment by bcolloran** [comment]
@iFlameing the idea here is to be able to add a url parameter to a notebook URL like e.g.:
`iodide.io/someuser/some-notebook.html?viewMode=REPORT`, and to have that URL parameter value override the initial value of `viewMode` that gets pushed into the redux store.
