### ISSUE TITLE
message passing is not filtering out non-iodide messages from other contexts/iframes

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#685]
On `iframe-2`, I'm getting the following error while loading a notebook:

<img width="837" alt="screen shot 2018-06-21 at 9 11 17 pm" src="https://user-images.githubusercontent.com/95735/41757569-b63af9d2-7597-11e8-9de3-2a2dc142f910.png">

EDIT: this appears to only be broken in FF. Chrome keeps marching on despite the same error hitting dev tools.

**Comment by hamilton** [comment]
Further inspection suggests that this is actually caused by `react-devtools-inspector` in FF. A casual `console.log` before the offending line reveals the following:

<img width="781" alt="screen shot 2018-06-21 at 9 25 24 pm" src="https://user-images.githubusercontent.com/95735/41757874-b1953dbe-7599-11e8-8e3c-15112ec17de0.png">

So, we'll definitely need to write tests / conditionals for every message that doesn't contain a `data` attribute. Addons may have messages being passed to the main context, and who knows how many other ways things might break. So we shouldn't count on this message passing working without filtering out every other kind of message in our handler. Also, tests tests tests!

**Comment by hamilton** [comment]
Fixed with #686

**Comment by bcolloran** [comment]
good look -- i think should be totally sufficient. i noticed that it can be done in one `if` clause, and also spotted another problem in there. and while i was in there, i figured out how to completely disconnect message event listener once a port is opened between editor and the eval frame. i think that now the connection is pretty secure and robust :+1:

**Comment by hamilton** [comment]
I'd really like to review this approach a bit better. Is there a reason `.data` is a string and not an object?

**Comment by bcolloran** [comment]
i simplified it a bit further so that the iframe justs post the secret session key, so now just a simple equality check is sufficient, so the message.data doesn't need to be an object, and the message verifier just needs to check that `message.data === window.IODIDE_SESSION_KEY`
