### ISSUE TITLE
autoindent should work if word wrapping is active in the editor

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#724]

**Comment by bcolloran** [comment]
unfortunately the example code linked below does not work plug-and-play :-/

https://github.com/codemirror/CodeMirror/issues/2085

https://codemirror.net/demo/indentwrap.html# (view source of this one)
view-source:https://codemirror.net/demo/indentwrap.html#

**Comment by Algentile** [comment]
Hey @bcolloran,

I will going on vacation on the 30th, but I can look into this issue if no one has this on their task list.

**Comment by bcolloran** [comment]
@Algentile Hi, i'm just getting back from a weekend away, sorry for the delay.

Hmm, I think we want to hold off on work on this, because we're evaluating moving from code-mirror to the Monaco editor (in fact, there is a draft PR out for that: https://github.com/iodide-project/iodide/pull/2013 )

If we decide not to go ahead with Monaco, then we'd love your help on this. Alternatively, if you are interested in working with text editor code, you could jump in on the monaco-3 branch -- there are number of things to do in there, and i can list out some issues in that branch if you are interested

**Comment by Algentile** [comment]
Hey @bcolloran,

I apologize, I just got back from vacation. I will hold off on this issue for now. It appears that monaco-3 was merged, but I can definitely pickup any outstanding issues with the editor that are open.
