### ISSUE TITLE
is it even possible to use iodide without devtools?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#729]

**Comment by DevinBayly** [comment]
A) I feel like I've had some success without the dev-console, but it was during the time when I hadn't figured out how to turn of the redux-logger
B) I use it quite a bit to see what a variable value is, and to view the function options associated with some object. in the scope of iodide work, its mainly to find out if a large cell had an error like you mentioned. GLSL messages currently don't make it back into the cell result editor area, and that keeps me glued to the output of the devtools console.
C) For me having the runtime errors appear in the cells somehow is vital.
D) I'm not sure about this kind of thing
E) I would guess that folks who do this kind of development are at least familiar with devtools. the trouble is how to split the difference of how much iodide should do that devtools console already does  if we encourage people to have the console open.
