### ISSUE TITLE
[Documentation] viewMode

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#733]
I think that there should be a section in the docs that explains the viewMode. I discovered that when viewMode is present in the `meta` cell, and it is assigned to `presentation`, it leads to presentation mode evaluated (which is cool). when it is missing, I guess it defaults to editor mode(?) and I am guessing that is the absence of the key-value pair in the meta cell.

I could add it somewhere but I am not certain if this is complete or if I am missing some details here.

cc: @bcolloran

**Comment by bcolloran** [comment]
That's correct @teonbrooks. At this point, nothing about JSMD is really documented b/c it's all kind of a moving target. At some point it would be good to work toward a somewhat more formal spec+documentation of JSMD in general.

**Comment by mdboom** [comment]
Is this functionality still working?  For example: https://extremely-alpha.iodide.io/notebooks/21/ doesn't seem to drop into report mode, despite the contents in the `%% meta`.

**Comment by bcolloran** [comment]
ah, `meta` is fully deprecated already -- report view is exposed by sharing a link with an url param, e.g.:

https://extremely-alpha.iodide.io/notebooks/21/?viewMode=report

one can manually add this  url param, or can click the "REPORT" button and copy the url from there (the url toggles when you change view). Additionally, using sharing a `viewMode=report` link will run all of the code in the notebook,
