### ISSUE TITLE
[Feature Request] overlay help pane

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/iodide#734]
It would be great if the user could press `h` or `?` and an overlay of all the keybindings could be listed. It's a super helpful tool and it would greatly reduce lookup time or doc hunting if this was available

**Comment by bcolloran** [comment]
per #233, this pane should also link to our GH, api docs, other relevant links; it should app version, etc

**Comment by bcolloran** [comment]
re #763, this pane can include the "file a bug" link that has been removed from the menu
