### ISSUE TITLE
use one html templates file for both js and python

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#744]
currently, webpack fills in a JS template string to create the root html file, and that template strings is also saved within the app JS bundle so that it can be used to create a functioning html file when a user exports. I think that at least for now, we still want to enable the ability to export a runnable html file that a user can host at their own website. In that case, perhaps we can come up with a way to avoid having multiple copies of the html template for the python and js code. i'm not sure how to accomplish this off-hand, b/c i'm not sure what if any template string formats will work well with JS and python. but LMK if you have ideas

**Comment by bcolloran** [comment]
see #740

**Comment by hamilton** [comment]
@bcolloran is this issue stale at this point?

**Comment by bcolloran** [comment]
i reckon it probably is. thanks @hamilton !!
