### ISSUE TITLE
remove the app message components / surface app messages in console

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#761]
now that we have the console, we can move app messages there. this will simplify the code and streamline the UI.

**Comment by wlach** [comment]
hmm, not sure about this, since the console isn't always open. I think some messages are better suited to an app-wide notification system (e.g. feedback that a notebook was saved)

**Comment by bcolloran** [comment]
fair enough, i'm not wedded to this idea. i was thinking we could also add a little badge on the console icon when new messages are available, but we can certainly keep the snackbar (although i think maybe we should move it to the top of the window).

in any case, even if we keep the snackbar, i think directing users to open the console to see the "more" info is equivalent to directing them to the app messages pane, so i'm in favor of decreasing the number of panes we have floating around.

**Comment by wlach** [comment]
Yeah, I'd be in favour of removing the app messages pane I think.

**Comment by bcolloran** [comment]
@hamilton do you have any thoughts about this? particularly in the golden layout world, i wonder if having a separate app message pane really adds much value. I suspect that focusing on the console and surfacing app messages there will be adequate

**Comment by hamilton** [comment]
I would be open to getting rid of the app message pane and putting its output into the console, but I agree with @wlach that removing the snackbar would take away an important app-level alert component that would likely cause more harm than good.

**Comment by hamilton** [comment]
Closed via #1509
