### ISSUE TITLE
a logged in user should be able to view their recently changed notebooks at <server url>

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#784]
from initial user stories at:
https://docs.google.com/document/d/1nq2mY3L57Wzfno5xj_eVcMECppB7iPA7jdyG5jRIUr4/edit?ts=5b7c6424

assigning @wlach initially, but just so that he can review, update, and assign to others as needed

**Comment by wlach** [comment]
I feel like we need to rethink what we want on the front page, since we already have a user page. How about we discuss at the next sprint planning meeting?

**Comment by bcolloran** [comment]
sounds good to me @wlach

**Comment by hamilton** [comment]
Isn't the idea here to have the front page (when logged in) have a full list of notebooks, as a barebones discovery tool?

**Comment by bcolloran** [comment]
i think this is now obselete
