### ISSUE TITLE
a not logged in user should see a landing page at <server url> that allows log in

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#785]
from initial user stories at:
https://docs.google.com/document/d/1nq2mY3L57Wzfno5xj_eVcMECppB7iPA7jdyG5jRIUr4/edit?ts=5b7c6424

assigning @wlach initially, but just so that he can review, update, and assign to others as needed

**Comment by wlach** [comment]
I think this is basically implemented via #770, but we should probably add some stories fleshing out what we want to see here. I suspect depending on the deployment, we may either want to show a list of recent notebooks (internal mozilla use case) or a splash / promotional page (iodide.io use case).
