### ISSUE TITLE
a logged in user should see their user avatar in the top bar of all nav pages

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#786]
from initial user stories at:
https://docs.google.com/document/d/1nq2mY3L57Wzfno5xj_eVcMECppB7iPA7jdyG5jRIUr4/edit?ts=5b7c6424

assigning @wlach initially, but just so that he can review, update, and assign to others as needed

**Comment by wlach** [comment]
We have a header element in the current implementation:

https://github.com/iodide-project/iodide/blob/10320a605f2f49efb0f5e3dd8764aac63f913a6f/src/server/components/header.jsx

This already has a login/logout button. We should probably just expand it so its styling is consistent with what's in the notebook currently, i.e.:

https://github.com/iodide-project/iodide/blob/10320a605f2f49efb0f5e3dd8764aac63f913a6f/src/components/menu/user-button.jsx

It would be nice to merge these components, in fact, perhaps possible if we abstract the notion of actions between the client (which uses redux) and the server (which doesn't, and IMO shouldn't)

**Comment by wlach** [comment]
@djbarnwal's original PR has an implementation which does this, may be useful for inspiration:

https://github.com/iodide-project/iodide/pull/753/files#diff-e869c43e93465f57150bee2689781a5f
