### ISSUE TITLE
logged in users should be able to create new notebooks from their user landing page

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#789]
- URL should become <server url>/<user>/new
- When I save the notebook, the url changes to <server url>/<user>/<notebook id>

from initial user stories at:
https://docs.google.com/document/d/1nq2mY3L57Wzfno5xj_eVcMECppB7iPA7jdyG5jRIUr4/edit?ts=5b7c6424

assigning @wlach initially, but just so that he can review, update, and assign to others as needed

**Comment by wlach** [comment]
I'm going to be working on this one.
