### ISSUE TITLE
it should be possible to view a list of any user's NBs at `<server url>/<user>`

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#792]
this list should be shown at this url for both logged in users and visitors, and should allow viewing of other users' notebook collections

from initial user stories at:
https://docs.google.com/document/d/1nq2mY3L57Wzfno5xj_eVcMECppB7iPA7jdyG5jRIUr4/edit?ts=5b7c6424

assigning @wlach initially, but just so that he can review, update, and assign to others as needed

**Comment by wlach** [comment]
My implementation in #809 would be useful for reference as to how to make the data flow between components.
