### ISSUE TITLE
Explore alternatives for data frame rep

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#797]
It's a little clunky and spacious.

One alternative to explore is `react-inspector`'s table support.

**Comment by mdboom** [comment]
`react-inspector`'s table support is more compact, but it doesn't do any truncation of pagination like what the current `react-table`.

**Comment by mdboom** [comment]
Ideally, I think something that does "infinite scrolling" by faking a scroll bar that inserts rows above or below is what we want.  The pagination feels really weird in this context.  But I don't think `react-table` can do that.

**Comment by bcolloran** [comment]
closed via #1419
