### ISSUE TITLE
Opening an object rep doesn't cause console to scroll up

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#800]
If you output an object rep (e.g. `window`), and then click the triangle to expand it, the console doesn't scroll up to show the expanded contents.

**Comment by bcolloran** [comment]
do you mean the console doesn't scroll _down_ i.e., that the expanded object flows out the bottom of the  visible area of the pane, and you are required to scroll down manually? fwiw, this is the same behavior as FF devtools, so I think it may be ok. In fact i think automatically scrolling down could be worse in the case of toggling open a huge object with a ton of keys

**Comment by mdboom** [comment]
Yes, that's what I mean.

Where I've encountered it is when there is output at the very bottom of the page and it looks like clicking the arrow did nothing:

![image](https://user-images.githubusercontent.com/38294/46532263-1fc8a100-c86e-11e8-95d6-d6c05175d66b.png)

I agree we should scroll all the way down, but maybe just enough to see a line or two?

**Comment by bcolloran** [comment]
i see. sure we can put this in the backlog for now.

**Comment by bcolloran** [comment]
Turns out that this is the behavior in Chrome and FF devtools as well -- i think autoscrolling would actually introduce a number of weird edge cases, so i think the current behavior is actually ok. closing
