### ISSUE TITLE
`npm run start-and-serve -- reduxVerbose` logs an error

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#813]
`npm run start-and-serve -- reduxVerbose` works, but logs an error:
`ERROR in Entry module not found: Error: Can't resolve 'reduxVerbose' Am I missing something?`

not critical, since it does actually work, but hopefully we can fix it anyway...

**Comment by hamilton** [comment]
This appears to just be a typo - notice the extra space between the `--` and `reduxVerbose`.

Running `npm run start-and-serve --reduxVerbose` appears to work fine without the error.

**Comment by bcolloran** [comment]
@hamilton not a typo unfortunately -- the space is required for the verbose redux logging to work (at least on my system, but lmk if omitting the space enable the verbose logging on your system... that would be weird). This is a quirk in how passing flags to scripts defined in package.json works. I haven't exhausted all possibilities, but I did spend a couple hours on it when i was setting that flag up, and i couldn't find any obvious work around or even figure out what was causing the error.

Anyhoo, i believe that in actual practice the error thrown does not cause any problems. @djbarnwal were you encountering any difficulties from this, or did you just notice the logging? if it's not actually causing problems it's probably low priority

**Comment by djbarnwal** [comment]
@bcolloran I just noticed the error log and thought that notebook wouldn't be functioning as expected. Turns out it works fine despite the error.

**Comment by bcolloran** [comment]
fixed with #879
