### ISSUE TITLE
Plugin definitions stay in a %% meta tag for no apparent reason

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#819]
I don't know why, but after you executed a plugin cell, it stays in the "languages" field of the JSON `%% meta` header.

It is not used if you reopen the script without the plugin cell, as the language it defines is ignored and the cell is converted to JS by default.

**Comment by louisabraham** [comment]
With pyodide-20180623.js, a missing meta header can cause the notebook to fail.
I don't see why it should, or even why the meta contains languages.

**Comment by mdboom** [comment]
The notebook needs to know how to syntax highlight and run code for a new language.

**Comment by louisabraham** [comment]
Sure, that's why the plugin cell is required. 
But I don't see why the exact same information should be put in the meta tag (as it is not sufficient).
It is really minor but can confuse users who directly write the jsmd.

**Comment by bcolloran** [comment]
@louisabraham yes you are correct, language info should not be required in the meta section. Would love a PR on this if you are able :-)

**Comment by louisabraham** [comment]
I think the language in the meta are required by the notebook to recognize the cells (if you remove the language from the meta section, the notebook fails to load), so one should go through the notebook to read the plugin cells.

I was also thinking about executing the language plugins present in the meta cell. That way, a non-js language integration could be done seamlessly, but one should be able to edit the meta cell from the notebook (in the iodide interface).

I see two different ideas here:
- going through the notebook to detect the plugins cells
- moving the plugin cells to a special %%meta or %%imports tag

What do you think? I can try to work on either one, but my react skill are non-existent.

**Comment by bcolloran** [comment]
hmm, i thought that the language info in the meta section should not be required. let me look into this a bit, i haven't looked at this stuff for a few months and appently i don't recall the details :-/

**Comment by louisabraham** [comment]
Try opening this after renaming to `python.html`. I simply removed the "py" language in the %%meta section of https://iodide.io/pyodide-demo/python.html.

I find the behavior of the "languages" part confusing: why is "js" present? and why is the meta tag not sufficient for another language to be supported (still need to execute the plugin cell)?

[python.txt](https://github.com/iodide-project/iodide/files/2354800/python.txt)

**Comment by bcolloran** [comment]
just landed a PR, please review/QA it. Thanks for finding this issue @louisabraham !

**Comment by louisabraham** [comment]
Thanks for this quick fix!
