### ISSUE TITLE
Syntax coloring doesn't always work 

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#828]
I tried with both files:
- https://iodide.io/dist/iodide.pyodide-20180623.js
- https://iodide.io/stable/iodide.stable.js

On https://louisabraham.github.io/domical/, the "mllike" syntax coloring doesn't work, but it works on a local copy.

https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.37.0/mode/mllike/mllike.js is correctly requested and retrieved in both cases.

**Comment by louisabraham** [comment]
Syntax coloring have been tested to work with:
- Google Chrome desktop
- Opera desktop
- Firefox Mobile

It doesn't work on Firefox desktop, unless you disable the cache in the network panel.

**Comment by bcolloran** [comment]
hi @louisabraham, the syntax coloring does appear to work for me in FF when i visit https://louisabraham.github.io/domical/ -- i see the following:

![image](https://user-images.githubusercontent.com/2380975/45174501-e3971780-b1bf-11e8-8de3-be9dae40aa72.png)

Are there other steps that i should try to reproduce this?

**Comment by louisabraham** [comment]
This is a really strange issue that appears only in Firefox Desktop.

I think it is a cache issue. I observed that in 100% of the cases, this syntax coloring issue appears when no "downloading plugin" message is printed, that is when it is already in the cache.

**Comment by bcolloran** [comment]
@hamilton @mdboom can you attempt to reproduce @louisabraham's issue? i could not.

**Comment by mdboom** [comment]
Yes, I can reproduce.  But not sure why that is, yet...

**Comment by louisabraham** [comment]
I cannot explain it either. But https://louisabraham.github.io/domical/ works when the cache is disabled (or when I load the page for the first time in a period of time), and https://iodide.io/iodide-examples/python.html *never* works (the python cells). Maybe those are two separate issues.

**Comment by hamilton** [comment]
@mdboom you had mentioned that this should be fixed with some recent changes. Is that correct?
