### ISSUE TITLE
Deploying server-based assets to ghpages has bugs and limitations

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#829]
So we configured extremely-alpha.iodide.app (the iframe resources) to be deployed from github pages based on master. This has worked mostly ok so far, but I just ran into a strange issue where fetching the resources returns a 404:

![image](https://user-images.githubusercontent.com/20569/44947738-cb9a4f00-addf-11e8-8627-5728f1ca89a8.png)

After doing some investigation, I determined that the problem is that we just tagged v0.6, and our script thus determined that we should only produce the tagged versions of the files:

* https://github.com/iodide-project/iodide/blob/2d8b54eaebcce46d2c5b516f2eb5ace823b948d9/webpack.config.js#L55
* https://github.com/iodide-project/master-eval

The easiest workaround would be to simply unconditonally produce the dev versions of the files in ghpages, but that's a bit ugly. It also doesn't completely solve the problem where you would want to test both client and server changes simultaneously in a PR. Is there any reason we can't just make extremely-alpha.iodide.app point to the heroku server and skip this github pages step altogether? Heroku seems happy to serve the same application from multiple domains from what I can tell. It should also be easy to configure Django so that requests to the untrusted eval frame (iodide.app) don't have access to login or anything but the static content.

@bcolloran @mdboom what do you think?

**Comment by mdboom** [comment]
@wlach: I think serving everything from Heroku makes sense, and is a little closer to dogfooding what we'll be doing for private installs in the future, too.  But I have to admit I don't fully understand all the details around Heroku -- I defer to you there.

The ghpages could probably be made to work, too, though -- ugly, yes, but that's sort of a part of the discussion we've had elsewhere about cleaning up the build stuff that seems to have accrued a lot of ugliness by now.

I've fixed it for now by adding a trivial commit to master, but that will break again the next time we make a tag so is not a real solution.
