### ISSUE TITLE
creating python cells in the web GUI

### ISSUE THREAD

**Issue by mash-graz** [iodide-project/iodide#830]
as already reported in the pyodide issue tracker (https://github.com/iodide-project/pyodide/issues/133), it doesn't look possible to add new python cells or change existing ones to this type of cell.

this also effects the [official pyodide demo notebook](https://github.com/iodide-project/pyodide/issues/133) and the explanations given there...

![](http://users.mur.at/ms/attachments/pyodide1.png)

and:
![](http://users.mur.at/ms/attachments/pyodide2.png)

**Comment by mash-graz** [comment]
found another open issue report concerning this flaw: #663

**Comment by mdboom** [comment]
It is possible using the keybinding ("P"), but, yes, it should be visible on the menu as well, but isn't.

**Comment by mash-graz** [comment]
thanks for this really important hint!

looks like nice *cheat code* to enter the next hidden level of practical usability/productivity. ;)

**Comment by djbarnwal** [comment]
Working on a fix for this issue.

**Comment by bcolloran** [comment]
see PR #832

**Comment by mash-graz** [comment]
thanks for this really useful improvement!
