### ISSUE TITLE
Be able to trace origins of forked notebooks

### ISSUE THREAD

**Issue by wlach** [iodide-project/iodide#836]
Follow-on from #791. I want to be able to fork a notebook from another user and for people viewing my notebook to be able to trace it back to the original.

I believe this has three parts:

* Adding a "forked_from" field (can be `null` for new notebooks) to the notebook model: https://github.com/iodide-project/iodide/blob/99f7883a996d16361094b08819fcd6bc9b7ade8b/server/notebooks/models.py#L5
* Adding this metadata to the various notebook API methods
* Exposing this information in the UI

**Comment by bcolloran** [comment]
related to (and probably blocked by) #841 -- in addition to (or perhaps even instead of?) pointing to a notebook, the "forked_from" should point to a specific NB revision.

**Comment by bcolloran** [comment]
cc @hamilton
