### ISSUE TITLE
add a field in the Notebook model to track the latest revision

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#841]
Suggested in #838, to get the latest revision of a notebook requires filtering all revisions by notebook id, then finding the latest. We can easily add a field to the Notebook model that does this for us.

**Comment by bcolloran** [comment]
@hamilton haven't we had this for a long while at this point? can we close?

**Comment by bcolloran** [comment]
(assuming fixed; if not obsolete/not burning)
