### ISSUE TITLE
log _out_ does not persist in localhost dev mode

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#849]
@wlach, this seems to be the flip side of #758 ;-)

steps:
1) open a localhost:8000 in a private window (to ensure logins are cleared)
2) log in
3) click the "logout" button
4) refresh
5) the button will once again say "logout", and your user icon is shown in any notebook that you open

The same thing happens if you attempt to log out from within a notebook (and you see a snackbar that says you've logged out even tho it doesn't persist)

**Comment by bcolloran** [comment]
this may be a bug on chrome only

**Comment by wlach** [comment]
Argh, right, we already have this on file. I will take a look tomorrow if no one gets to it before me. Probably easy to solve.

**Comment by wlach** [comment]
Hmm, I can't reproduce this anymore. Nor #912.

**Comment by wlach** [comment]
Let's tackle this in #912.
