### ISSUE TITLE
phishing attacks via Report view?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#866]
we should be thinking about attacks along the lines of:

1) an example notebook loads some js library that is written by the attacker
2) when another user looks at that notebook in report view, the attackers library detects that they are in report view and simulates a copy of the editor when the user attempts to go back to "EXPLORE" view.
3) the simulated editor says that the user has been logged out and prompts the user for a password.

this kind of phishing attack is possible even with the security advantages we gain from the iframe, b/c in report view the iframe covers the whole window, and so an attacker can draw whatever they want. they can't get user data directly, but they could simulate the editor, user pages, login pages, etc.

not sure what to do about this other than keeping the iframe from being able to draw over the whole screen in report view. If we always keep our header bar on top of the viewport and never let the iframe draw on the top 40 px, then at least we can show the correct login status etc.

@wlach @hamilton @mdboom @djbarnwal any other ideas?

(i guess leaving the header bar at the top in report view could be ok. we could make it a bit less obtrusive that the heavy black bar, and i think readers could still have a good reading experience with it there, while making sure that there is some screen real estate that attackers can never paint over. I guess e.g. Medium always has it's header bar at top, and the reading experience is ok there.)

**Comment by wlach** [comment]
Could also provide the *user* an option to remove the black bar on top, if they really want a report without any Chrome.

**Comment by bcolloran** [comment]
i was thinking about this a bit more while exploring the Golden Layout  tab-based UX over the weekend, and i'm a bit less concerned about this than when i wrote up the issue, b/c i think i was not correctly understanding how z-index works with iframes.  _think_ that we can guarantee that our "EXPLORE" button is always shown higher in the z-index stack than the iframe, and that whenever that button is pressed the iframe layer is sent behind the editor layer. So i think that we still need to be mindful of phishing attacks, but maybe we don't need to keep the full bar up there.

However, I wonder if it would make sense to add the login badge to the explore/report button, so that the user will always be able to see their logged in status from that button (even in report view), so that if a hostile report tries to tell them they are logged out, it will conflict with what is shown on that button?

**Comment by bcolloran** [comment]
@hamilton any thoughts/ideas/suggestions on this?
