### ISSUE TITLE
Save notebook option missing from menu

### ISSUE THREAD

**Issue by mdboom** [iodide-project/iodide#875]
Ctrl+S still works, however.

I think this is a recent regression, but I haven't figured out from when yet.

**Comment by hamilton** [comment]
I'll investigate.

**Comment by hamilton** [comment]
Struggled to replicate this, as did @bcolloran, so I'm going to additionally assign mike. @mdboom happy to help you triage it over video / screen sharing so we can see what might be causing this issue.

**Comment by mdboom** [comment]
Seems to have resolved after updating this morning.  Closing.
