### ISSUE TITLE
avatar not shown upon log in after log out; and clicking "Go to Profile" errors

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#883]
### What I Did

on localhost:8000, under FF

from the iodide landing page, in a logged in state:
(1) log out via the user menu
(2) refresh the browser
(3) click "LOG IN"

result:
- interstitial window pops, and i appear to be logged in
- user avatar is not shown
- if i click the user menu (which just shows a little down arrow), i get the following:

```
Page not found (404)
Request Method:    GET
Request URL:    http://localhost:8000/undefined/
Raised by:    server.views.user
No User matches the given query.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

see video on gitter at 
https://files.gitter.im/iodide-project/iodide/0oca/Peek-2018-09-12-14-29.webm

**Comment by hamilton** [comment]
hmm, this seems to be something I probably messed up when I implemented the new user menu. I'll take a look at this.
