### ISSUE TITLE
As a user, I want an easy way to delete a notebook and revisions I've created

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#888]
Users will want a way to delete notebooks (include all their revisions), as well as specific revisions.

If I am logged in and on my user page, there should be an easy way to delete the notebook from that page. Either that, or I should be able to go to something like `/notebooks/<notebook-id>/revisions/` and delete the whole notebook + revisions there.

Any deletion requires the creation of an "are you sure?" modal, which will have to be an additional component created for general server work.

Assigning to @bcolloran for proper triaging and @wlach for additional ideas & method for going about accomplishing this, but I am happy to do the actual work for this. Feel free to un-assign yourselves accordingly!

**Comment by wlach** [comment]
We could always just use a javascript confirm dialog for the "are you sure?" logic for a first pass, and defer the modal work to later.

**Comment by hamilton** [comment]
@wlach Yeah, the modal is the easy part :). Here are my questions:

- Deleting a record is pretty straightforward, but we'll need a url. I suppose given this is REST I can implement DELETE on `/notebooks/${notebookID}`, and then wire the view appropriately. Does this seem like the right approach?
- I'm assuming that from the client, the idea is to issue something like:
```javascript
fetch(`/notebooks/${notebookID}`, {
  method: 'DELETE',
  body: {userName, isAuthenticated}
})
``` 
and check to see if the current user is authenticated and owns that notebook. Is there anything else I'm missing there?

**Comment by wlach** [comment]
@hamilton actually you shouldn't need to add any API at all. Just verified. You can already delete from the rest api browser when looking at notebook (when logged in):

http://localhost:8000/api/v1/notebooks/<notebook id>/

I believe it should already be checking permissions but it would be good to add some basic unit tests verifying that this is the case.

**Comment by hamilton** [comment]
@wlach perfect, thanks for the pointer! didn't realize the api already had it. This should be fairly easy to put together.
