### ISSUE TITLE
re-implement localStorage-based autosaving

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#894]
Our previous localStorage story (discussed in #351) has been deprecated, but as @louisabraham pointed out, there are still some very useful cases where localStorage might make sense (including auto-saving on a non-server instance).

There is probably some interaction around the server instance and a localStorage autosave feature as well, though I imagine that'll probably fall away as we get per-keystroke-chunk saving on by default on the server component.

With this in mind, we should come up with a design for this that solves the issue (a user loses editor progress if they accidentally close a tab or navigate away from the notebook in some settings).

**Comment by bcolloran** [comment]
see also #853, #1018

**Comment by SimonBiggs** [comment]
Not sure if this is helpful or not but I found IndexedDB far better for purposes like this. Also if it helped http://dexie.org is a great wrapper around IndexedDB.

**Comment by wlach** [comment]
Ok, have been hacking on this a bit over the past few days. Here are my ideas on how this should work (have implemented a good chunk):

We store the following structure locally (currently in localStorage, but could be indexdb):

```js
{
   originalCopy: <jsmd>,
   originalSaved: "<date in isoformat>",
   dirtyCopy: <jsmd>,
   dirtySaved: "<date in isoformat>"
}
```

We update the dirty copy every 15 seconds or so if there are changes.

On first load of a notebook, we serialize the original contents and the last modified date to the original values. On any modification, we update the dirty copy with the current state of the jsmd and the save date.

Behaviour will be slightly different depending on which mode the notebook is operating: server-based or standalone.

Server based:
* We will clear the dirty copy and reset the original copy on any save
* On subsequent loads, if there is a dirty copy, then set the content to that, but offer in a banner to let user revert to server-based version (this will need to somehow cooperate with the other banners we have for other things, like the message we show when the user doesn't own the notebook)

Standalone:
* On any modification, warn that the changes are only saved locally. Offer to let user revert to original.
