### ISSUE TITLE
add interstitial banner state for "this notebook is in standalone mode"

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#896]
For a notebook that is not connected to iodide.io, the warning banner should give a message that warns the user they're not connect, and offers them the opportunity to load their work at iodide.io (which will require a server API of some kind), or dismiss the banner if they want to work in standalone mode

**Comment by mdboom** [comment]
How do we know whether to recommend the public server or some other server?  We're just defaulting to the public one for now?

**Comment by bcolloran** [comment]
I think we'll be able to read that from the .env file right? we'll have to change the host names in that file for each deployment anyway.

**Comment by mdboom** [comment]
For standalone, the stuff in .env relates to where the standalone js is served from.  I don't there's a notion of pointing to "another thing" yet...

**Comment by bcolloran** [comment]
i think we'll need to clarify what we mean by "standalone" mode a little bit next week -- i'm thinking of it as meaning the files that are served from an exported archive, and which are not served from any iodide server instance (including the one at localhost).

Under that interpretation, i was imagining the following:
- for a given iodide server deployment (whether our main deployement at iodide.io, a  private deployment at mozilla etc, or a localhost deployment for testing/development), you have to set the correct URIs in the .env
- those propogate forward into the webpack build of the JS assets
- so if you're using an iodide NB from a server deployment and you export an archive, when the archive is run the URI from the originating deployment will be available (iodide.io or iodide.mozilla.org or localhost (this latter will still be useful for testing))

i suspect we're just talking about different things? what did you have in mind?

**Comment by mdboom** [comment]
I see.  I think currently, we have a notion of a standalone build, which is totally unaware of any server.  I think you are suggesting that when you export a notebook from a server, that exported notebook would be able to link back to the server it was created from...?

**Comment by bcolloran** [comment]
blocked by #1008
fyi @hamilton
