### ISSUE TITLE
Saved Notebook shows other Local Storage Keys

### ISSUE THREAD

**Issue by thejeshgn** [iodide-project/iodide#905]
I have hosted the iodide on a domain. On the same domain I have other application that uses PouchDB.
Both these applications use the Local Storage, since the local storage is same for both the apps. If I go to save notes it shows pouchDB related keys

### What I Did
I have pouchDB based app and iodide on the same domain.

### What I Expected
iodide to shows only the notebook it saved.

### What Happened 
It shows other random note book names in saved notebooks which doesnt belong.
![screenshot from 2018-09-15 17-30-37](https://user-images.githubusercontent.com/76114/45586078-fd4a0480-b90d-11e8-9d0a-ff4eee2f0a1b.png)

### What can be done

May be start all the iodide keys with  **_iodide** so it can be filtered and also other JS libraries can ignore these keys.

**Comment by bcolloran** [comment]
Thanks for filing this @thejeshgn -- overhauling how localstorage is used is on our roadmap, we'll make sure to address this!

**Comment by bcolloran** [comment]
obsolete via #894 etc
