### ISSUE TITLE
make sure correct MIME types being served

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#911]
```Refused to apply style from 'http://localhost:8000/server.home.dev.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.```

**Comment by mdboom** [comment]
I think for the most part mimetypes are working correctly.  For this specific file, it's a 404, which is returning HTML, thus the error.  Looking into the cause of the 404...

**Comment by mdboom** [comment]
Is this file even necessary?  It seems to be inlining a bunch of style into the header of these server pages right now...  

Cc: @hamilton -- since I know you've been working on CSS things lately.

**Comment by hamilton** [comment]
This file is not necessary. We're not building `server.home.dev.css` as far as I can tell, and are instead endeavoring for a css-in-js solution along with an `injectGlobal` call for server-side components. So we should probably close this issue.
