### ISSUE TITLE
authenticated actions not working with some instances of chromium?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#912]
see #849; also, i was having trouble with saving notebooks and forking notebooks ("make a copy" link) under chrome

**Comment by bcolloran** [comment]
Actually, I realize that I had not tried testing chromium at extremely-alpha, and saving/forking/logout errors there as well as on localhost.

FWIW, from chrome://settings/help:
`Version 67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)`

Chrome works fine on my windows box, so I have no idea what is going on with this.

on localhost, i get the following error:
```
POST http://localhost:8000/api/v1/notebooks/2/revisions/ 403 (Forbidden)

fetchWithCSRFToken | @ | fetch-with-csrf-token.js:23
fetchWithCSRFTokenAndJSONContent | @ | fetch-with-csrf-token.js:39
saveNotebookRequest | @ | actions.js:277
(anonymous) | @ | actions.js:327
(anonymous) | @ | index.js:8
setInterval | @ | server-autosave.js:14
setInterval (async) |   |  
checkForServerAutosave | @ | server-autosave.js:11
./src/index.jsx | @ | index.jsx:53
__webpack_require__ | @ | bootstrap:19
./node_modules/@babel/runtime/helpers/arrayWithoutHoles.js.module.exports | @ | bootstrap:83
(anonymous) | @ | bootstrap:83
```

(I also get a 403 when POSTing to extremely-alpha, but the minified code doesn't give a useful stack trace)

**Comment by bcolloran** [comment]
update: doing a complete uninstall of chromium, then manually deleting `~/.config/chromium` and `~/.cache/chromium`, then reinstalling did not clear the problem

**Comment by wlach** [comment]
@bcolloran I just tried reproducing on my Fedora machine with the Chromium instance there, and everything worked fine. I feel like this is likely an issue with your specific Linux distribution / machine, or the interaction between it and iodide. Not saying there isn't a bug here, but it doesn't seem to be universally reproducible with the same browser / operating system combination.

**Comment by bcolloran** [comment]
great! as long as it's a weirdly specific flaky intermittent thing i won't lose sleep. Having a failure to reproduce on another linux box is reassuring, thanks @wlach :-)

**Comment by bcolloran** [comment]
closing -- no one has yet been able to reproduce
