### ISSUE TITLE
"create new notebook" button takes me to the /new URL, but I also get an interstitial saying "this notebook is owned by another user"

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#917]
<img width="716" alt="screen shot 2018-09-18 at 12 27 08 pm" src="https://user-images.githubusercontent.com/95735/45711372-3668bb80-bb3e-11e8-8daa-eebb7571e6b0.png">

**Comment by hamilton** [comment]
@mdboom @bcolloran I can take this on.

**Comment by mdboom** [comment]
Ok.  Ping me if you have questions -- I suspect the `user_can_save` value is incorrect because the notebook isn't served from its final URL?  Also, related to this, it should probably change the URL to `/notebooks/XXX` so there's a copyable link there for sharing.

**Comment by hamilton** [comment]
@mdboom it seems that there is no place (when you have a new notebook) that the function `getNotebookInfo` is called & the store is not updated accordingly. This happens on `index.jsx` with `handleInitialJsmd`, but since there is no jsmd in a new notebook, the app doesn't look at `notebookInfo`.

I'm going to unassign myself from this for now since I don't have time at the moment to get to it, so feel free to tackle this if you've got an idea :)

**Comment by hamilton** [comment]
nvm this took 5 minutes. Re-assigning. PR forthcoming.
