### ISSUE TITLE
code mirror perf problems

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#92]
We have seen that CodeMirror (or at least how we're using it / how it interacts with our app) has some performance issues.

We are welcoming PRs for replacing CodeMirror with any of the other JS-based editors.

**Comment by bcolloran** [comment]
try the following to see the performance choke:
1) on /dev, open the following NB with the url trick ?url=https://iodide-project.github.io/iodide-examples/eviction-notices-by-sf-neighborhood--1999-2015.html 
2) load the notebook, then go down to the css cell at the bottom and type a bit.
3) typing speed will be slow
4) also try adding cells at the end of the NB

Note: this may be a Firefox-specific problem, so a fix for this issue MUST TEST ON FF AND CHROME

**Comment by hamilton** [comment]
@bcolloran on second thought, I really don't see any performance issues with CodeMirror on large cells. I'd be happy to close this issue, since the main problem - severe hangs which negatively impacts the UX - seems to have been solved with your PR.

**Comment by hamilton** [comment]
@bcolloran I believe this has been fixed. Going to close. If it seems slow again we can reopen.
