### ISSUE TITLE
how should we handle testing?

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#94]
[Jest](https://facebook.github.io/jest/docs/en/getting-started.html) is a simple testing framework for Javascript, developed by Facebook. It seems both straightforward enough to getting the ball rolling for writing tests, and streamlined enough to make test-writing itself a breeze. Redux gives us an imminently testable framework to compare state changes easily, so we can ensure that our actions and reducers do what we expect any time we make a change to the code.

**Comment by hamilton** [comment]
@bcolloran would you argue that we should keep this open / put as an issue for 0.4a and hope to get enough of the testing story done that we can close it?

**Comment by bcolloran** [comment]
i think move it to 0.4a
