### ISSUE TITLE
logging into the server still surfaces interstitial: "This notebook is owned by another user" even if I own the notebook

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#958]
Refreshing the page corrects this issue, but there shouldn't be an interstitial when I click "log in". Perhaps the `notebookInfo` part of the store needs to be updated when one logs in.

**Comment by bcolloran** [comment]
@hamilton @mdboom was this one fixed?

**Comment by bcolloran** [comment]
well, if we can't reproduce the bug anymore, that's good enough for me! the specific PR matters less :-)
