### ISSUE TITLE
because pages don't reload after login / logout on server anymore, the page does not update accordingly upon login/logout

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#960]
If we are not going to reload the server page upon login / logout, we will have to re-engineer the components to hide whatever pieces are not pertinent to the viewer.

**Comment by wlach** [comment]
I would personally be in favor of just refreshing pages upon login/logout, this shouldn't be hard to do.

**Comment by wlach** [comment]
Just because it isn't entirely clear, one example problem caused by this is that the "Delete notebook" option doesn't become available/unavailable as you'd expect before or after logging in.
