### ISSUE TITLE
remove IODIDE_BUILD_TYPE

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#980]
with #979 IODIDE_BUILD_TYPE is now redundant. let's remove all references to it. perhaps going forward we can use the redux store to manage the relevant state (for things liek showing/hiding the user menu) rather than the variables

cc @hamilton  and @wlach cuz i see you guys have code that looks at this flag.

**Comment by mdboom** [comment]
This is also somewhat related to #916 as well -- to indicate to the user when they are connected to the server or not at runtime.

**Comment by hamilton** [comment]
@mdboom at this point we've removed any reference to `IODIDE_BUILD_TYPE` from the client-side code, so once #978 is merged we'll be ready to close this issue.

**Comment by hamilton** [comment]
Closed with the merge of #978.
