### ISSUE TITLE
"EXPLORE" button should be more prominent in report view (funnel optimization)

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#984]
we want to make the "EXPLORE" button more prominent and visible so that it doesn't get overlooked during a user's first encounter with iodide

**Comment by iFlameing** [comment]
@bcolloran what are you expecting in the pr of this issue ?

**Comment by bcolloran** [comment]
this is basically a styling change -- the explore button should not have a white background, which results in it appearing as white-on-white by default. It just needs to be a little more noticeable to make people more likely to click on it. This could be as simple as changing it to be very to light gray and/or adding a slight border, but i'm not wedded to any particular option -- we just need it have a little more visual pop to attract clicks.

@hamilton do you have thoughts?
