### ISSUE TITLE
it should be possible to inspect the `window` object with reps (expanding `window` contents in console causes error)

### ISSUE THREAD

**Issue by DevinBayly** [iodide-project/iodide#992]
In the process of attempting to show the contents of the window object I whited out the entire suite of console,report,workspace options. 
this 
![image](https://user-images.githubusercontent.com/11687631/46249477-a13bb180-c3de-11e8-8997-bfa13faf8a59.png)
becomes this
![image](https://user-images.githubusercontent.com/11687631/46249469-9123d200-c3de-11e8-89df-0352aa9ec7c4.png)

Following my steps is easy enough, just evaluate a js cell with window in it, and try to click on the console result to show more.

### What I Did

code sample or exact steps that causes the bug

### What I Expected

explanation, imgs, etc.

### What Happened 

explanation, imgs. etc.

### (OPTIONAL) notebook that reproduces bug 

link to the notebook that reproduces the bug, or just inline it in the issue

**Comment by hamilton** [comment]
Good catch! We actually found some similar behavior this last week but
thought the bug was localized to something else. Yikes

**Comment by hamilton** [comment]
@DevinBayly Howdy - trying with all my might to recreate this bug, but can't seem to on FF nor on Chrome. Out of curiosity, what are you running on?

**Comment by DevinBayly** [comment]
I found another place this shows up. If you start a notebook when the dev console is open in the bottom on extremely alpha then console,report ... are all black windows no matter what gets executed.

**Comment by bcolloran** [comment]
@DevinBayly could you give detailed steps to reproduce? i could not reproduce doing the following:

1) in FF, open extremely alpha
2) while still on the landing page, press ctrl+shift+i to open devtools
3) navigate to a notebook by clicking the topmost notebook link on the iodide landing page

result: everything seems to function normally

**Comment by DevinBayly** [comment]
Yea it just worked for me again too. ok back to just the original issue of this thread

**Comment by hamilton** [comment]
Thanks to @mdboom the error is now handled as such:

<img width="834" alt="screen shot 2019-02-26 at 9 15 43 pm" src="https://user-images.githubusercontent.com/95735/53467646-eefb2b00-3a0b-11e9-96c0-9aa3bc99fc63.png">

Big improvement, obviously, over blowing up the eval frame.

In this sense, this issue could be considered "closed" - @bcolloran thoughts here>

**Comment by bcolloran** [comment]
i think the underlying issue is still valid, so i'll update the title of this to reflect that.

**Comment by hamilton** [comment]
All for that. I suspect the solution would likely have to be on the `iodide-react-inspector` front, since it seems to be reading the first few keys from `window` in the collapsed version.

**Comment by bcolloran** [comment]
hey hey, this is long since fixed!
