### ISSUE TITLE
make sure all reducers are pure functions, move side effects and impure data access to action creators

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#995]
we're long overdue to go back and clean up some of the reducer code we wrote in our early days writing Iodide, and in particular before we had redux-thunk to help us manage asyncronous dispatch. One thing we can do is take a sweep through all of our reducers to make sure that they are pure functions, which will make them deterministic and more easily testable.

(and of course, we should also make sure we're not adding more such code before we get to this issue)

**Comment by hamilton** [comment]
@bcolloran This is probably pretty close to being closable, yeah?

**Comment by bcolloran** [comment]
hopefully. it's in scope for #1250
