### ISSUE TITLE
local dev server via `npm run start-and-serve` needs to serve from two ports for adequate dev testing

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#999]
We're missing a whole class of bugs and issues by not replicating our server environment enough here. I cannot adequately test and patch #992 locally, for instance. It also prevents us from uncovering issues such as #996. 

Ideally the `EVAL_FRAME_ORIGIN` in `.env` can be set and the appropriate additional server can be spun up to replicate the issue.

**Comment by bcolloran** [comment]
+1
adding a second origin is easy, we just need need to serve on two ports eg
localhost:8000 and localhost:5000 or whatevs,, but it will probably take a
little bit of doing to package it up in a way that is not too much work for
users; previously, i was doing this by manually opening two terminals and
running two copies of python simpleHttpServer with two distinct ports.

also there are two cases to consider:
- start-and-serve mode (which uses webpack dev server)
- the django server

i suspect getting django to serve from two ports will be easier than
getting webpack-dev-server to do so, but i'm not really sure.
